/*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*
  This code is generated by JAC version 5.6 by
  Agent Oriented Software. http://www.agent-software.com.au

    DO NOT ALTER THIS CODE AND DO NOT REMOVE THIS COMMENT
 *=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*/
package NeonAffect;
import aos.jack.jak.agent.Capability;
import aos.jack.jak.agent.NameSpace;
import aos.jack.jak.agent.Agent;
import aos.jack.util.thread.Semaphore;

/**
 * 
 */

public class ImpatienceAffectCapability extends aos.jack.jak.agent.Capability {
    public NeonAffect.PlanContextName planContextName;
    public NeonAffect.Behavior behaviorName;
    public aos.jack.util.thread.Semaphore mutex;
    public aos.jack.util.thread.Semaphore mutex2;
    public NeonAffect.NA_Debug debug;
    public NeonAffect.ContextEvent ce;
    public java.lang.String getDocumentation()
    {
        return "/**\n * \n */\n";
    }
    
    public void __init1()
    {
        setNamedCreator("planContextName","NeonAffect.PlanContextName",new aos.jack.jak.agent.DataCreator(false){
            public java.lang.Object create()
            {
                return __named_data_planContextName();
            }
            
        },true);
        setNamedCreator("behaviorName","NeonAffect.Behavior",new aos.jack.jak.agent.DataCreator(false){
            public java.lang.Object create()
            {
                return __named_data_behaviorName();
            }
            
        },true);
        setNamedCreator("mutex","aos.jack.util.thread.Semaphore",new aos.jack.jak.agent.DataCreator(false){
            public java.lang.Object create()
            {
                return __named_data_mutex();
            }
            
        },true);
        setNamedCreator("mutex2","aos.jack.util.thread.Semaphore",new aos.jack.jak.agent.DataCreator(false){
            public java.lang.Object create()
            {
                return __named_data_mutex2();
            }
            
        },true);
        setNamedCreator("debug","NeonAffect.NA_Debug",new aos.jack.jak.agent.DataCreator(false){
            public java.lang.Object create()
            {
                return __named_data_debug();
            }
            
        },true);
    }
    
    public void __init2()
    {
        ce = (NeonAffect.ContextEvent) findEvent("NeonAffect.ContextEvent");
        planContextName = (NeonAffect.PlanContextName) getNamedObject("planContextName","NeonAffect.PlanContextName");
        behaviorName = (NeonAffect.Behavior) getNamedObject("behaviorName","NeonAffect.Behavior");
        mutex = (aos.jack.util.thread.Semaphore) getNamedObject("mutex","aos.jack.util.thread.Semaphore");
        mutex2 = (aos.jack.util.thread.Semaphore) getNamedObject("mutex2","aos.jack.util.thread.Semaphore");
        debug = (NeonAffect.NA_Debug) getNamedObject("debug","NeonAffect.NA_Debug");
        autorun();
    }
    
    synchronized public void __init_desc()
    {
        externals.put("debug","debug");
        externals.put("mutex2","mutex2");
        externals.put("mutex","mutex");
        externals.put("behaviorName","behaviorName");
        externals.put("planContextName","planContextName");
        externals.put("NeonAffect.SetPlanContextEvent","NeonAffect.SetPlanContextEvent");
        externals.put("NeonAffect.Level4NegAffectEvent","NeonAffect.Level4NegAffectEvent");
        addEvent("NeonAffect.Level4NegAffectEvent",aos.jack.jak.agent.Agent.HANDLED_EVENT);
        addEvent("NeonAffect.SetPlanContextEvent",aos.jack.jak.agent.Agent.HANDLED_EVENT);
        addEvent("NeonAffect.ContextEvent",aos.jack.jak.agent.Agent.SENT_EVENT);
        addPlan("NeonAffect.ScowlingPlan",0);
        addPlan("NeonAffect.LookingUpwardImpatiencePlan",0);
        addPlan("NeonAffect.ArmsCrosseImpatiencePlan",0);
        addPlan("NeonAffect.StiffPostureImpatiencePlan",0);
        addPlan("NeonAffect.TappingFootPlan",0);
        addPlan("NeonAffect.PurseLipsImpatiencePlan",0);
        addPlan("NeonAffect.CheckWatchPlan",0);
        addPlan("NeonAffect.ClenchedTeethPlan",0);
        addPlan("NeonAffect.FidgetingImpatiencePlan",0);
        addPlan("NeonAffect.SquintEyesImpatiencePlan",0);
        addPlan("NeonAffect.TalkingOverOthersPlan",0);
        addPlan("NeonAffect.AbnoxiousImpatiencePlan",0);
        addPlan("NeonAffect.NotEasilyDistractedImpatiencePlan",0);
        addPlan("NeonAffect.FrownImpatiencePlan",0);
        addPlan("NeonAffect.SharpTonePlan",0);
        addPlan("NeonAffect.MassagingTemplesPlan",0);
        addPlan("NeonAffect.SensitiveNoiseImpatiencePlan",0);
        addPlan("NeonAffect.DeepExhalePlan",0);
        addPlan("NeonAffect.ShakingHeadImpatiencePlan",0);
        addPlan("NeonAffect.SarcasmPatiencePlan",0);
        addPlan("NeonAffect.GetThingsGoingPlan",0);
        addPlan("NeonAffect.YellingImpatiencePlan",0);
        addPlan("NeonAffect.InattentiveImpatiencePlan",0);
        addPlan("NeonAffect.InterruptingImpatiencePlan",0);
        addPlan("NeonAffect.GettingToPointSpeechPlan",0);
        addPlan("NeonAffect.SetTimeLimitPlan",0);
        addPlan("NeonAffect.MakeDemandsPlan",0);
        addPlan("NeonAffect.SetPlanContextImpatiencePlan",0);
    }
    
    public ImpatienceAffectCapability(aos.jack.jak.agent.NameSpace outer)
    {
        super(outer);
    }
    
    synchronized public void __bindNames()
    {
        super.__bindNames();
        __bindToPlan("NeonAffect.ScowlingPlan");
        __bindToPlan("NeonAffect.LookingUpwardImpatiencePlan");
        __bindToPlan("NeonAffect.ArmsCrosseImpatiencePlan");
        __bindToPlan("NeonAffect.StiffPostureImpatiencePlan");
        __bindToPlan("NeonAffect.TappingFootPlan");
        __bindToPlan("NeonAffect.PurseLipsImpatiencePlan");
        __bindToPlan("NeonAffect.CheckWatchPlan");
        __bindToPlan("NeonAffect.ClenchedTeethPlan");
        __bindToPlan("NeonAffect.FidgetingImpatiencePlan");
        __bindToPlan("NeonAffect.SquintEyesImpatiencePlan");
        __bindToPlan("NeonAffect.TalkingOverOthersPlan");
        __bindToPlan("NeonAffect.AbnoxiousImpatiencePlan");
        __bindToPlan("NeonAffect.NotEasilyDistractedImpatiencePlan");
        __bindToPlan("NeonAffect.FrownImpatiencePlan");
        __bindToPlan("NeonAffect.SharpTonePlan");
        __bindToPlan("NeonAffect.MassagingTemplesPlan");
        __bindToPlan("NeonAffect.SensitiveNoiseImpatiencePlan");
        __bindToPlan("NeonAffect.DeepExhalePlan");
        __bindToPlan("NeonAffect.ShakingHeadImpatiencePlan");
        __bindToPlan("NeonAffect.SarcasmPatiencePlan");
        __bindToPlan("NeonAffect.GetThingsGoingPlan");
        __bindToPlan("NeonAffect.YellingImpatiencePlan");
        __bindToPlan("NeonAffect.InattentiveImpatiencePlan");
        __bindToPlan("NeonAffect.InterruptingImpatiencePlan");
        __bindToPlan("NeonAffect.GettingToPointSpeechPlan");
        __bindToPlan("NeonAffect.SetTimeLimitPlan");
        __bindToPlan("NeonAffect.MakeDemandsPlan");
        __bindToPlan("NeonAffect.SetPlanContextImpatiencePlan");
    }
    
    private NeonAffect.PlanContextName __named_data_planContextName()
    {
        planContextName = (NeonAffect.PlanContextName) getNamedObject("planContextName","NeonAffect.PlanContextName");
        return planContextName;
    }
    
    private NeonAffect.Behavior __named_data_behaviorName()
    {
        behaviorName = (NeonAffect.Behavior) getNamedObject("behaviorName","NeonAffect.Behavior");
        return behaviorName;
    }
    
    private aos.jack.util.thread.Semaphore __named_data_mutex()
    {
        mutex = (aos.jack.util.thread.Semaphore) getNamedObject("mutex","aos.jack.util.thread.Semaphore");
        return mutex;
    }
    
    private aos.jack.util.thread.Semaphore __named_data_mutex2()
    {
        mutex2 = (aos.jack.util.thread.Semaphore) getNamedObject("mutex2","aos.jack.util.thread.Semaphore");
        return mutex2;
    }
    
    private NeonAffect.NA_Debug __named_data_debug()
    {
        debug = (NeonAffect.NA_Debug) getNamedObject("debug","NeonAffect.NA_Debug");
        return debug;
    }
    
}
