/*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*
  This code is generated by JAC version 5.6 by
  Agent Oriented Software. http://www.agent-software.com.au

    DO NOT ALTER THIS CODE AND DO NOT REMOVE THIS COMMENT
 *=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*/
package NeonAffect;
import aos.jack.jak.agent.Capability;
import aos.jack.jak.agent.NameSpace;
import aos.jack.jak.agent.Agent;
import aos.jack.util.thread.Semaphore;

/**
 * 
 */

public class FriendlyAffectCapability extends aos.jack.jak.agent.Capability {
    public NeonAffect.PlanContextName planContextName;
    public NeonAffect.Behavior behaviorName;
    public aos.jack.util.thread.Semaphore mutex;
    public aos.jack.util.thread.Semaphore mutex2;
    public NeonAffect.NA_Debug debug;
    public NeonAffect.ContextEvent ce;
    public java.lang.String getDocumentation()
    {
        return "/**\n * \n */\n";
    }
    
    public void __init1()
    {
        setNamedCreator("planContextName","NeonAffect.PlanContextName",new aos.jack.jak.agent.DataCreator(false){
            public java.lang.Object create()
            {
                return __named_data_planContextName();
            }
            
        },true);
        setNamedCreator("behaviorName","NeonAffect.Behavior",new aos.jack.jak.agent.DataCreator(false){
            public java.lang.Object create()
            {
                return __named_data_behaviorName();
            }
            
        },true);
        setNamedCreator("mutex","aos.jack.util.thread.Semaphore",new aos.jack.jak.agent.DataCreator(false){
            public java.lang.Object create()
            {
                return __named_data_mutex();
            }
            
        },true);
        setNamedCreator("mutex2","aos.jack.util.thread.Semaphore",new aos.jack.jak.agent.DataCreator(false){
            public java.lang.Object create()
            {
                return __named_data_mutex2();
            }
            
        },true);
        setNamedCreator("debug","NeonAffect.NA_Debug",new aos.jack.jak.agent.DataCreator(false){
            public java.lang.Object create()
            {
                return __named_data_debug();
            }
            
        },true);
    }
    
    public void __init2()
    {
        ce = (NeonAffect.ContextEvent) findEvent("NeonAffect.ContextEvent");
        planContextName = (NeonAffect.PlanContextName) getNamedObject("planContextName","NeonAffect.PlanContextName");
        behaviorName = (NeonAffect.Behavior) getNamedObject("behaviorName","NeonAffect.Behavior");
        mutex = (aos.jack.util.thread.Semaphore) getNamedObject("mutex","aos.jack.util.thread.Semaphore");
        mutex2 = (aos.jack.util.thread.Semaphore) getNamedObject("mutex2","aos.jack.util.thread.Semaphore");
        debug = (NeonAffect.NA_Debug) getNamedObject("debug","NeonAffect.NA_Debug");
        autorun();
    }
    
    synchronized public void __init_desc()
    {
        externals.put("debug","debug");
        externals.put("mutex2","mutex2");
        externals.put("mutex","mutex");
        externals.put("behaviorName","behaviorName");
        externals.put("planContextName","planContextName");
        externals.put("NeonAffect.SetPlanContextEvent","NeonAffect.SetPlanContextEvent");
        externals.put("NeonAffect.Level2PosAffectEvent","NeonAffect.Level2PosAffectEvent");
        addEvent("NeonAffect.Level2PosAffectEvent",aos.jack.jak.agent.Agent.HANDLED_EVENT);
        addEvent("NeonAffect.SetPlanContextEvent",aos.jack.jak.agent.Agent.HANDLED_EVENT);
        addEvent("NeonAffect.ContextEvent",aos.jack.jak.agent.Agent.SENT_EVENT);
        addPlan("NeonAffect.BeingOpenMindedPlan",0);
        addPlan("NeonAffect.ExpressingInterestPlan",0);
        addPlan("NeonAffect.InitiatingConversationFriendlyPlan",0);
        addPlan("NeonAffect.LaughingFriendlyPlan",0);
        addPlan("NeonAffect.NoddingFriendlyPlan",0);
        addPlan("NeonAffect.OfferingComplementFriendlyPlan",0);
        addPlan("NeonAffect.OfferingToHelpFriendlyPlan",0);
        addPlan("NeonAffect.OpenBodyPostureFriendlyPlan",0);
        addPlan("NeonAffect.RememberingDetailsPlan",0);
        addPlan("NeonAffect.SeekingCommonGroundPlan",0);
        addPlan("NeonAffect.SharingExperienceFriendlyPlan",0);
        addPlan("NeonAffect.ShowingEmpathyFriendlyPlan",0);
        addPlan("NeonAffect.ShowingInterestPlan",0);
        addPlan("NeonAffect.SmilingFriendlyPlan",0);
        addPlan("NeonAffect.UsingGentleHandGesturesPlan",0);
        addPlan("NeonAffect.UsingSupportiveLanguagePlan",0);
        addPlan("NeonAffect.UsingWarmGreetingsPlan",0);
        addPlan("NeonAffect.SetPlanContextFriendlyPlan",0);
    }
    
    public FriendlyAffectCapability(aos.jack.jak.agent.NameSpace outer)
    {
        super(outer);
    }
    
    synchronized public void __bindNames()
    {
        super.__bindNames();
        __bindToPlan("NeonAffect.BeingOpenMindedPlan");
        __bindToPlan("NeonAffect.ExpressingInterestPlan");
        __bindToPlan("NeonAffect.InitiatingConversationFriendlyPlan");
        __bindToPlan("NeonAffect.LaughingFriendlyPlan");
        __bindToPlan("NeonAffect.NoddingFriendlyPlan");
        __bindToPlan("NeonAffect.OfferingComplementFriendlyPlan");
        __bindToPlan("NeonAffect.OfferingToHelpFriendlyPlan");
        __bindToPlan("NeonAffect.OpenBodyPostureFriendlyPlan");
        __bindToPlan("NeonAffect.RememberingDetailsPlan");
        __bindToPlan("NeonAffect.SeekingCommonGroundPlan");
        __bindToPlan("NeonAffect.SharingExperienceFriendlyPlan");
        __bindToPlan("NeonAffect.ShowingEmpathyFriendlyPlan");
        __bindToPlan("NeonAffect.ShowingInterestPlan");
        __bindToPlan("NeonAffect.SmilingFriendlyPlan");
        __bindToPlan("NeonAffect.UsingGentleHandGesturesPlan");
        __bindToPlan("NeonAffect.UsingSupportiveLanguagePlan");
        __bindToPlan("NeonAffect.UsingWarmGreetingsPlan");
        __bindToPlan("NeonAffect.SetPlanContextFriendlyPlan");
    }
    
    private NeonAffect.PlanContextName __named_data_planContextName()
    {
        planContextName = (NeonAffect.PlanContextName) getNamedObject("planContextName","NeonAffect.PlanContextName");
        return planContextName;
    }
    
    private NeonAffect.Behavior __named_data_behaviorName()
    {
        behaviorName = (NeonAffect.Behavior) getNamedObject("behaviorName","NeonAffect.Behavior");
        return behaviorName;
    }
    
    private aos.jack.util.thread.Semaphore __named_data_mutex()
    {
        mutex = (aos.jack.util.thread.Semaphore) getNamedObject("mutex","aos.jack.util.thread.Semaphore");
        return mutex;
    }
    
    private aos.jack.util.thread.Semaphore __named_data_mutex2()
    {
        mutex2 = (aos.jack.util.thread.Semaphore) getNamedObject("mutex2","aos.jack.util.thread.Semaphore");
        return mutex2;
    }
    
    private NeonAffect.NA_Debug __named_data_debug()
    {
        debug = (NeonAffect.NA_Debug) getNamedObject("debug","NeonAffect.NA_Debug");
        return debug;
    }
    
}
