/*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*
  This code is generated by JAC version 5.6 by
  Agent Oriented Software. http://www.agent-software.com.au

    DO NOT ALTER THIS CODE AND DO NOT REMOVE THIS COMMENT
 *=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*/
package NeonAffect;
import aos.jack.jak.agent.Capability;
import aos.jack.jak.agent.NameSpace;
import aos.jack.jak.agent.Agent;
import aos.jack.util.thread.Semaphore;

/**
 * 
 */

public class KindAffectCapability extends aos.jack.jak.agent.Capability {
    public NeonAffect.PlanContextName planContextName;
    public NeonAffect.Behavior behaviorName;
    public aos.jack.util.thread.Semaphore mutex;
    public aos.jack.util.thread.Semaphore mutex2;
    public NeonAffect.NA_Debug debug;
    public NeonAffect.ContextEvent ce;
    public java.lang.String getDocumentation()
    {
        return "/**\n * \n */\n";
    }
    
    public void __init1()
    {
        setNamedCreator("planContextName","NeonAffect.PlanContextName",new aos.jack.jak.agent.DataCreator(false){
            public java.lang.Object create()
            {
                return __named_data_planContextName();
            }
            
        },true);
        setNamedCreator("behaviorName","NeonAffect.Behavior",new aos.jack.jak.agent.DataCreator(false){
            public java.lang.Object create()
            {
                return __named_data_behaviorName();
            }
            
        },true);
        setNamedCreator("mutex","aos.jack.util.thread.Semaphore",new aos.jack.jak.agent.DataCreator(false){
            public java.lang.Object create()
            {
                return __named_data_mutex();
            }
            
        },true);
        setNamedCreator("mutex2","aos.jack.util.thread.Semaphore",new aos.jack.jak.agent.DataCreator(false){
            public java.lang.Object create()
            {
                return __named_data_mutex2();
            }
            
        },true);
        setNamedCreator("debug","NeonAffect.NA_Debug",new aos.jack.jak.agent.DataCreator(false){
            public java.lang.Object create()
            {
                return __named_data_debug();
            }
            
        },true);
    }
    
    public void __init2()
    {
        ce = (NeonAffect.ContextEvent) findEvent("NeonAffect.ContextEvent");
        planContextName = (NeonAffect.PlanContextName) getNamedObject("planContextName","NeonAffect.PlanContextName");
        behaviorName = (NeonAffect.Behavior) getNamedObject("behaviorName","NeonAffect.Behavior");
        mutex = (aos.jack.util.thread.Semaphore) getNamedObject("mutex","aos.jack.util.thread.Semaphore");
        mutex2 = (aos.jack.util.thread.Semaphore) getNamedObject("mutex2","aos.jack.util.thread.Semaphore");
        debug = (NeonAffect.NA_Debug) getNamedObject("debug","NeonAffect.NA_Debug");
        autorun();
    }
    
    synchronized public void __init_desc()
    {
        externals.put("debug","debug");
        externals.put("mutex2","mutex2");
        externals.put("mutex","mutex");
        externals.put("behaviorName","behaviorName");
        externals.put("planContextName","planContextName");
        externals.put("NeonAffect.SetPlanContextEvent","NeonAffect.SetPlanContextEvent");
        externals.put("NeonAffect.Level1PosAffectEvent","NeonAffect.Level1PosAffectEvent");
        addEvent("NeonAffect.Level1PosAffectEvent",aos.jack.jak.agent.Agent.HANDLED_EVENT);
        addEvent("NeonAffect.SetPlanContextEvent",aos.jack.jak.agent.Agent.HANDLED_EVENT);
        addEvent("NeonAffect.ContextEvent",aos.jack.jak.agent.Agent.SENT_EVENT);
        addPlan("NeonAffect.AcknowledgingEffortKindPlan",0);
        addPlan("NeonAffect.BeingGenerousPlan",0);
        addPlan("NeonAffect.CalmExteriorKindPlan",0);
        addPlan("NeonAffect.ConsideringOthersPerspectivesPlan",0);
        addPlan("NeonAffect.ExpressingGratitudePlan",0);
        addPlan("NeonAffect.ForgivenessKindPlan",0);
        addPlan("NeonAffect.GivingComplementsKindPlan",0);
        addPlan("NeonAffect.GivingPraiseKindPlan",0);
        addPlan("NeonAffect.GivingThumbsUpKindPlan",0);
        addPlan("NeonAffect.ListeningKindPlan",0);
        addPlan("NeonAffect.NoddingKindPlan",0);
        addPlan("NeonAffect.OfferingEncouragementPlan",0);
        addPlan("NeonAffect.OfferingToHelpKindPlan",0);
        addPlan("NeonAffect.PatientlyWaitingPlan",0);
        addPlan("NeonAffect.PerformingActsOfKindnessKindPlan",0);
        addPlan("NeonAffect.SharingPositiveFeedbackPlan",0);
        addPlan("NeonAffect.ShowingConcernKindPlan",0);
        addPlan("NeonAffect.ShowingEmpathyPlan",0);
        addPlan("NeonAffect.SmilingKindPlan",0);
        addPlan("NeonAffect.SpeakingGentlyKindPlan",0);
        addPlan("NeonAffect.ThinkingPositivelyPlan",0);
        addPlan("NeonAffect.UsingPoliteLanguagePlan",0);
        addPlan("NeonAffect.SetPlanContextKindPlan",0);
    }
    
    public KindAffectCapability(aos.jack.jak.agent.NameSpace outer)
    {
        super(outer);
    }
    
    synchronized public void __bindNames()
    {
        super.__bindNames();
        __bindToPlan("NeonAffect.AcknowledgingEffortKindPlan");
        __bindToPlan("NeonAffect.BeingGenerousPlan");
        __bindToPlan("NeonAffect.CalmExteriorKindPlan");
        __bindToPlan("NeonAffect.ConsideringOthersPerspectivesPlan");
        __bindToPlan("NeonAffect.ExpressingGratitudePlan");
        __bindToPlan("NeonAffect.ForgivenessKindPlan");
        __bindToPlan("NeonAffect.GivingComplementsKindPlan");
        __bindToPlan("NeonAffect.GivingPraiseKindPlan");
        __bindToPlan("NeonAffect.GivingThumbsUpKindPlan");
        __bindToPlan("NeonAffect.ListeningKindPlan");
        __bindToPlan("NeonAffect.NoddingKindPlan");
        __bindToPlan("NeonAffect.OfferingEncouragementPlan");
        __bindToPlan("NeonAffect.OfferingToHelpKindPlan");
        __bindToPlan("NeonAffect.PatientlyWaitingPlan");
        __bindToPlan("NeonAffect.PerformingActsOfKindnessKindPlan");
        __bindToPlan("NeonAffect.SharingPositiveFeedbackPlan");
        __bindToPlan("NeonAffect.ShowingConcernKindPlan");
        __bindToPlan("NeonAffect.ShowingEmpathyPlan");
        __bindToPlan("NeonAffect.SmilingKindPlan");
        __bindToPlan("NeonAffect.SpeakingGentlyKindPlan");
        __bindToPlan("NeonAffect.ThinkingPositivelyPlan");
        __bindToPlan("NeonAffect.UsingPoliteLanguagePlan");
        __bindToPlan("NeonAffect.SetPlanContextKindPlan");
    }
    
    private NeonAffect.PlanContextName __named_data_planContextName()
    {
        planContextName = (NeonAffect.PlanContextName) getNamedObject("planContextName","NeonAffect.PlanContextName");
        return planContextName;
    }
    
    private NeonAffect.Behavior __named_data_behaviorName()
    {
        behaviorName = (NeonAffect.Behavior) getNamedObject("behaviorName","NeonAffect.Behavior");
        return behaviorName;
    }
    
    private aos.jack.util.thread.Semaphore __named_data_mutex()
    {
        mutex = (aos.jack.util.thread.Semaphore) getNamedObject("mutex","aos.jack.util.thread.Semaphore");
        return mutex;
    }
    
    private aos.jack.util.thread.Semaphore __named_data_mutex2()
    {
        mutex2 = (aos.jack.util.thread.Semaphore) getNamedObject("mutex2","aos.jack.util.thread.Semaphore");
        return mutex2;
    }
    
    private NeonAffect.NA_Debug __named_data_debug()
    {
        debug = (NeonAffect.NA_Debug) getNamedObject("debug","NeonAffect.NA_Debug");
        return debug;
    }
    
}
