/*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*
  This code is generated by JAC version 5.6 by
  Agent Oriented Software. http://www.agent-software.com.au

    DO NOT ALTER THIS CODE AND DO NOT REMOVE THIS COMMENT
 *=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*/
package NeonAffect;
import aos.jack.jak.plan.Plan;
import aos.jack.jak.plan.PlanFSM;
import aos.jack.jak.plan.ExMap;
import aos.jack.jak.agent.NameSpace;
import aos.jack.jak.event.Event;
import aos.jack.jak.task.Task;
import aos.jack.jak.core.Generator;
import aos.jack.jak.logic.Signature;
import aos.jack.util.thread.Semaphore;
import java.lang.Object;
import aos.jack.jak.cursor.Cursor;
import aos.jack.jak.fsm.FSM;
import aos.jack.jak.core.Jak;

/**
 * 
 */

public class AffectAppraisalPlan extends aos.jack.jak.plan.Plan {
    private static java.lang.Class __exClass_0 = aos.jack.jak.fsm.FSM.loadClass("java.lang.Exception");
    public NeonAffect.AffectAppraisalEvent aae;
    public NeonAffect.NeonAffectAgent enc;
    public aos.jack.util.thread.Semaphore appraisalMutex;
    public NeonAffect.NA_Debug debug;
    private static aos.jack.jak.plan.ExMap[] __exMap_body = {
            new aos.jack.jak.plan.ExMap(10,17,18,__exClass_0),
            new aos.jack.jak.plan.ExMap(10,19,20,null)};
    private static java.lang.String[] __tt__body = {
            "NeonAffect/AffectAppraisalPlan.plan",
            "body",
            "38",
            "39",
            "41",
            "43",
            "45",
            "47",
            "52",
            "54",
            "57",
            "59",
            "63",
            "62",
            "33"};
    private final static java.lang.String[] __planVariableNames = {
            "aae",
            "enc",
            "appraisalMutex",
            "debug"};
    private final static java.lang.String[] __planVariableTypes = {
            "NeonAffect.AffectAppraisalEvent",
            "NeonAffectAgent",
            "aos.jack.util.thread.Semaphore",
            "NeonAffect.NA_Debug"};
    private final static java.lang.String[] __reasoningMethods = {
            "body"};
    private final static java.lang.String[] __fsmVariableNames_body = {
            "$debug",
            "bDebug",
            "iAffectType",
            "e"};
    private final static java.lang.String[] __fsmTypes_body = {
            "logical boolean",
            "boolean",
            "int",
            "Exception"};
    private final static java.lang.String[] __fsmLocalNames_body = {
            "__local__33_0",
            "__local__33_1",
            "__local__33_2",
            "__local__33_3"};
    static boolean relevant(NeonAffect.AffectAppraisalEvent aae)
    {
        return true;
    }
    
    public java.lang.String getDocumentation()
    {
        return "/**\n * \n */\n";
    }
    
    public AffectAppraisalPlan()
    {
    }
    
    private AffectAppraisalPlan(aos.jack.jak.task.Task __t, NeonAffect.AffectAppraisalPlan __env)
    {
        __agent = __env.__agent;
        __ns = __env.__ns;
        __planTask = __t;
        __logic = __t.logic;
        aae = __env.aae;
        enc = (NeonAffect.NeonAffectAgent) __ns.getIF(NeonAffect.NeonAffectAgent.class);
        appraisalMutex = __env.appraisalMutex;
        debug = __env.debug;
    }
    
    public boolean init_sentinel(aos.jack.jak.agent.NameSpace __a)
    {
        aae = (NeonAffect.AffectAppraisalEvent) __a.findEvent("NeonAffect.AffectAppraisalEvent");
        if (aae == null) {
            warning("AffectAppraisalEvent aae: is not found in the capability/agent this plan comes from");
            return false;
        }
        appraisalMutex = (aos.jack.util.thread.Semaphore) lookupNamedObject("appraisalMutex","aos.jack.util.thread.Semaphore",0);
        if (appraisalMutex == null) {
            warning("Semaphore appraisalMutex: is not found in the capability/agent this plan comes from");
            return false;
        }
        debug = (NeonAffect.NA_Debug) lookupNamedObject("debug","NeonAffect.NA_Debug",0);
        if (debug == null) {
            warning("NA_Debug debug: is not found in the capability/agent this plan comes from");
            return false;
        }
        return true;
    }
    
    public aos.jack.jak.plan.Plan freeze()
    {
        return this;
    }
    
    public aos.jack.jak.plan.Plan unfreeze()
    {
        return this;
    }
    
    public java.lang.Object genObject(int __index)
    {
        switch (__index) {
        }
        aos.jack.jak.core.Jak.error("illegal Object Construction");
        return null;
    }
    
    public aos.jack.jak.cursor.Cursor genCursor(int __index)
        throws java.lang.Exception
    {
        switch (__index) {
        }
        aos.jack.jak.core.Jak.error("illegal Cursor Construction");
        return null;
    }
    
    public aos.jack.jak.fsm.FSM genFSM(int __index)
        throws java.lang.Exception
    {
        switch (__index) {
        }
        aos.jack.jak.core.Jak.error("illegal FSM Construction");
        return null;
    }
    
    public boolean testCondition(int __index)
        throws java.lang.Exception
    {
        switch (__index) {
        }
        aos.jack.jak.core.Jak.error("illegal test Construction");
        return false;
    }
    
    public aos.jack.jak.plan.PlanFSM body()
    {
        return new NeonAffect.AffectAppraisalPlan.__bodyFSM();
    }
    
    private AffectAppraisalPlan(NeonAffect.AffectAppraisalEvent __ev, aos.jack.jak.task.Task __t, NeonAffect.AffectAppraisalPlan __env)
    {
        this(__t,__env);
        this.aae = __ev;
    }
    
    protected aos.jack.jak.logic.Signature eventSignature(int __log)
    {
        return aae.getSignature(__log);
    }
    
    public java.lang.String handledEvent()
    {
        return "NeonAffect.AffectAppraisalEvent";
    }
    
    public boolean __relevant(aos.jack.jak.event.Event __e)
    {
        return __ns.isEnabled() && relevant(((NeonAffect.AffectAppraisalEvent) __e));
    }
    
    public aos.jack.jak.plan.Plan createPlan(aos.jack.jak.event.Event __e, aos.jack.jak.task.Task __t)
    {
        if (!(__e instanceof NeonAffect.AffectAppraisalEvent)) 
            return null;
        NeonAffect.AffectAppraisalEvent __e1 = (NeonAffect.AffectAppraisalEvent) __e;
        return new NeonAffect.AffectAppraisalPlan(__e1,__t,this);
    }
    
    public java.lang.String[] variableNames()
    {
        return __planVariableNames;
    }
    
    public java.lang.String[] variableTypes()
    {
        return __planVariableTypes;
    }
    
    public java.lang.Object getVariable(int n)
    {
        switch (n) {
            case 0: 
            {
                return aos.util.ToObject.box(aae);
            }
            case 1: 
            {
                return aos.util.ToObject.box(enc);
            }
            case 2: 
            {
                return aos.util.ToObject.box(appraisalMutex);
            }
            case 3: 
            {
                return aos.util.ToObject.box(debug);
            }
            default: 
            {
                throw new java.lang.IndexOutOfBoundsException("Plan " + this + " does not have variable number " + n);
            }
        }
    }
    
    public java.lang.String[] reasoningMethods()
    {
        return mergeReasoningMethods(__reasoningMethods,super.reasoningMethods());
    }
    
    public aos.jack.jak.cursor.Cursor context()
    {
        try {
            return (((true)?aos.jack.jak.cursor.Cursor.trueCursor:aos.jack.jak.cursor.Cursor.falseCursor));
        }
        catch (java.lang.Exception e) {
            e.printStackTrace();
            return aos.jack.jak.cursor.Cursor.falseCursor;
        }
    }
    
    class __bodyFSM extends aos.jack.jak.plan.PlanFSM implements aos.jack.jak.core.Generator {
        aos.jack.jak.logic.BooleanVariable __local__33_0;
        boolean __local__33_1;
        int __local__33_2;
        java.lang.Exception __local__33_3;
        private int __breakLevel = 0;
        public int run(int __status)
            throws java.lang.Throwable
        {
            do {
                try {
                    if (__tothrow != null) 
                        throw __tothrow;
                    if ((aos.jack.jak.core.Jak.debugging & aos.jack.jak.core.Jak.LOG_PLANS) != 0) 
                        aos.util.logging.LogMsg.log(this,aos.jack.jak.core.Jak.LOG_PLANS,__task + "-AffectAppraisalPlan.body:" + java.lang.Integer.toString(__state));
                    if (__task.nsteps > 0) {
                        __task.nsteps-- ;
                        if (__task.nsteps == 0) 
                            agent.changeFocus();
                    }
                    if (__state < 10) {
                        __status = super.stdrun(NeonAffect.AffectAppraisalPlan.this,__status);
                        if (__status != CONTINUE || agent.changing_focus) 
                            return __status;
                        continue;
                    }
                    __curstate = __state;
                    switch (__state) {
                        default: 
                        {
                            aos.jack.jak.core.Jak.error("AffectAppraisalPlan.body: Illegal state");
                            return FAILED_STATE;
                        }
                        //* (38)             logical boolean $debug;
                        case 10: 
                        {
                            __breakLevel = 2;
                            __local__33_0 = (aos.jack.jak.logic.BooleanVariable) __logic.new_variable(java.lang.Boolean.TYPE);
                            __state = 11;
                            break;
                        }
                        //* (39)             debug.get($debug).next();
                        case 11: 
                        {
                            if (debug.get(__local__33_0).next()) 
                                __state = 12;
                             else 
                                throw planfailed;
                            break;
                        }
                        //* (41)             boolean bDebug = $debug.as_boolean();
                        case 12: 
                        {
                            __local__33_1 = __local__33_0.as_boolean();
                            __state = 13;
                            break;
                        }
                        //* (43)             int iAffectType = aae.iAffectType;
                        case 13: 
                        {
                            __local__33_2 = aae.iAffectType;
                            __state = 14;
                            break;
                        }
                        //* (45)             if (bDebug)
                        case 14: 
                        {
                            if (__local__33_1) 
                                __state = 15;
                             else 
                                __state = 16;
                            break;
                        }
                        //* (47)                 System.out.println("NeonAffectAgent.AffectAppraisalPlan: AffectType: [" + Integer.toString(iAffectType) + "]");
                        case 15: 
                        {
                            __breakLevel = 4;
                            __state = 16;
                            java.lang.System.out.println("NeonAffectAgent.AffectAppraisalPlan: AffectType: [" + java.lang.Integer.toString(__local__33_2) + "]");
                            break;
                        }
                        //* (52)             if (bDebug)
                        case 16: 
                        {
                            if (__local__33_1) 
                                __state = 17;
                             else 
                                __state = 20;
                            break;
                        }
                        //* (54)                 System.out.println("NeonAffectAgent.AffectAppraisalPlan: After setting emotion");
                        case 17: 
                        {
                            __breakLevel = 4;
                            __state = 20;
                            java.lang.System.out.println("NeonAffectAgent.AffectAppraisalPlan: After setting emotion");
                            break;
                        }
                        //* (57)         catch (Exception e)
                        case 18: 
                        {
                            __breakLevel = 2;
                            __state = 19;
                            __local__33_3 = (java.lang.Exception) __current;
                            break;
                        }
                        //* (59)             e.printStackTrace();            
                        case 19: 
                        {
                            __breakLevel = 4;
                            __state = 20;
                            __local__33_3.printStackTrace();
                            break;
                        }
                        //* (63)             appraisalMutex.signal();            
                        case 20: 
                        {
                            __breakLevel = 2;
                            __state = 21;
                            appraisalMutex.signal();
                            break;
                        }
                        //* (62)         {
                        case 21: 
                        {
                            __state = 22;
                            if (__breakLevel < 2) 
                                __state = 22;
                            __tothrow = __pending;
                            break;
                        }
                        //* (33)     #reasoning method
                        case 22: 
                        {
                            if (__pending == null) 
                                __state = PASSED_STATE;
                            __tothrow = __pending;
                            break;
                        }
                    }
                }
                catch (java.lang.Throwable e) {
                    handleException(e,__exMap_body);
                }
            }
             while (!agent.changing_focus);
            return CONTINUE;
        }
        
        public java.lang.String methodName()
        {
            return "body";
        }
        
        __bodyFSM()
        {
        }
        
        public java.lang.String stateInfo()
        {
            int n = __curstate;
            java.lang.String file = __tt__body[0];
            java.lang.String method = __tt__body[1];
            if (n < 0) 
                n = -n;
            n -= (10 - 2);
            java.lang.String line = (n < 2)?"??":__tt__body[n];
            return file + ":" + line + " " + method + " [" + __curstate + "]";
        }
        
        public java.lang.Object genObject(int __index)
        {
            switch (__index) {
            }
            aos.jack.jak.core.Jak.error("illegal Object Construction");
            return null;
        }
        
        public aos.jack.jak.cursor.Cursor genCursor(int __index)
            throws java.lang.Exception
        {
            switch (__index) {
            }
            aos.jack.jak.core.Jak.error("illegal Cursor Construction");
            return null;
        }
        
        public aos.jack.jak.fsm.FSM genFSM(int __index)
            throws java.lang.Exception
        {
            switch (__index) {
            }
            aos.jack.jak.core.Jak.error("illegal FSM Construction");
            return null;
        }
        
        public boolean testCondition(int __index)
            throws java.lang.Exception
        {
            switch (__index) {
            }
            aos.jack.jak.core.Jak.error("illegal test Construction");
            return false;
        }
        
        public aos.jack.jak.plan.Plan getPlan()
        {
            return NeonAffect.AffectAppraisalPlan.this;
        }
        
        protected aos.jack.jak.fsm.FSM fail()
        {
            return getPlan().fail();
        }
        
        protected aos.jack.jak.fsm.FSM pass()
        {
            return getPlan().pass();
        }
        
        public void enter()
        {
            __trace = agent.trace("NeonAffect.AffectAppraisalPlan.body");
        }
        
        public java.lang.Object getVariable(int n)
        {
            switch (n) {
                case 0: 
                {
                    return aos.util.ToObject.box(__local__33_0);
                }
                case 1: 
                {
                    return aos.util.ToObject.box(__local__33_1);
                }
                case 2: 
                {
                    return aos.util.ToObject.box(__local__33_2);
                }
                case 3: 
                {
                    return aos.util.ToObject.box(__local__33_3);
                }
                default: 
                {
                    throw new java.lang.IndexOutOfBoundsException("Reasoning Method " + methodName() + " does not have variable number " + n);
                }
            }
        }
        
        public java.lang.String[] variableNames()
        {
            return __fsmVariableNames_body;
        }
        
        public java.lang.String[] variableTypes()
        {
            return __fsmTypes_body;
        }
        
        public java.lang.String[] variableLocalNames()
        {
            return __fsmLocalNames_body;
        }
        
    }
}
