/*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*
  This code is generated by JAC version 5.6 by
  Agent Oriented Software. http://www.agent-software.com.au

    DO NOT ALTER THIS CODE AND DO NOT REMOVE THIS COMMENT
 *=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*/
package NeonAffect;
import aos.jack.jak.agent.Agent;
import aos.jack.jak.event.Event;
import aos.jack.jak.task.TaskManager;
import WaitLibrary.WaitCapability;
import aos.jack.util.thread.Semaphore;
import aos.cojack.base.CatMan;
import java.util.ArrayList;
import DebugLibrary.DebugBeliefSet;
import aos.jack.jak.util.timer.DilatedClock;
import aos.jack.jak.plan.Plan;

/**
 * 
 */

public class AbstractMiniAgent extends aos.jack.jak.agent.Agent {
    private boolean bDebug = false;
    private int iAffectType = -1;
    private java.lang.String strInteractionType = "";
    private java.util.ArrayList plansWithFormulas = new java.util.ArrayList();
    private java.util.ArrayList selectedPlans = new java.util.ArrayList();
    private java.lang.String strBehavior = "";
    private aos.jack.jak.logic.BooleanVariable $debug;
    public WaitLibrary.WaitCapability wc;
    public NeonAffect.AbstractAffectCapability cap1;
    public NeonAffect.GetSetFormulasCapability gsfc;
    public NeonAffect.PlansWithFormulas plansFormulas;
    public NeonAffect.PlanContextName planContextName;
    public NeonAffect.Behavior behaviorName;
    public aos.jack.util.thread.Semaphore mutex;
    public aos.jack.util.thread.Semaphore mutex2;
    public NeonAffect.NA_Debug debug;
    private NeonAffect.AbstractAffectEvent ev1;
    private NeonAffect.GetSelectedPlansEvent gspe;
    private NeonAffect.SetPlanContextEvent2 spce2;
    private NeonAffect.GetBehaviorEvent gbe;
    private NeonAffect.GetPlanFormulasEvent gpfe;
    private NeonAffect.PlanSelectorEvent pse;
    public AbstractMiniAgent(java.lang.String name, java.lang.String strInteractionType1, int iAffectType1, boolean bDebug1)
    {
        super(name);
        boolean __b = getAgentType() == NeonAffect.AbstractMiniAgent.class;
        if (__b) {
            __init1();
            __init2();
        }
        Init();
        iAffectType = iAffectType1;
        strInteractionType = strInteractionType1;
        bDebug = bDebug1;
        if (__b) 
            startAgent();
    }
    
    public void Init()
    {
        this.timer = new aos.jack.jak.util.timer.DilatedClock(1d,this.timer);
        this.timer.setTime(0L);
    }
    
    public int GetAffectType()
    {
        return iAffectType;
    }
    
    public java.lang.String GetBehavior(java.lang.String strModeratorType)
    {
        try {
            if (bDebug) {
                java.lang.System.out.println("Inside AddAffectHistoryPlan.");
            }
            java.util.ArrayList planNames = GetPlans();
            if (bDebug) {
                java.lang.System.out.println("Inside SetPlanContextPlan: printing plans:");
                int iSize = planNames.size();
                for (int i = 0; i < iSize; i++ ) {
                    java.lang.String strPlanName = (java.lang.String) planNames.get(i);
                    java.lang.System.out.println("planName [" + strPlanName + "]");
                }
            }
            java.util.ArrayList planNamesWithFormulas = GetPlansWithFormulas(strModeratorType,planNames);
            if (bDebug) {
                int iSize = planNamesWithFormulas.size();
                java.lang.System.out.println("Inside AbstractMiniAgent.GetBehavior: after call to GetPlansWithFormulas: planNamesWithFormulas size: " + java.lang.Integer.toString(iSize));
            }
            java.util.ArrayList selectedPlans = GetSelectedPlans(strInteractionType,planNamesWithFormulas);
            if (bDebug) {
                int iSize = selectedPlans.size();
                java.lang.System.out.println("Inside AbstractMiniAgent.GetBehavior: after GetSelectedPlans. size: " + java.lang.Integer.toString(iSize));
            }
            for (int i = 0; i < selectedPlans.size(); i++ ) {
                NeonAffect.SelectedPlan item = (NeonAffect.SelectedPlan) selectedPlans.get(i);
                java.lang.String strPlanName = item.GetPlanName();
                java.lang.String strPlanFormula = item.GetFormula();
                if (bDebug) {
                    java.lang.System.out.println("Inside AbstractMiniAgent.GetBehavior: SelectedPlan Name [" + strPlanName + "] Formula: [" + strPlanFormula + "]");
                }
                SetCognitiveFormula(strModeratorType,strPlanName,strPlanFormula);
            }
            if (bDebug) {
                java.lang.System.out.println("Inside AbstractMiniAgent.GetBehavior: before set plan context.");
            }
            //set plan context

            postEvent(spce2.post(NeonAffect.PlanConstants.ALL_PLANS));
            mutex.threadWait();
            if (bDebug) {
                java.lang.System.out.println("Inside AbstractMiniAgent.GetBehavior: before call to level plan.");
            }
            if (bDebug) {
                java.lang.System.out.println("Inside AbstractMiniAgent.GetBehavior: event class name: [" + ev1.getClass().getName() + "]");
                java.lang.System.out.println("Inside AbstractMiniAgent.GetBehavior: getting events.");
            }
            PostEvent();
            if (bDebug) {
                java.lang.System.out.println("Inside AbstractMiniAgent.GetBehavior: before call to get behavior.");
            }
            //grab behavior beliefSet

            postEvent(gbe.post(iAffectType));
            mutex.threadWait();
        }
        catch (java.lang.Exception e) {
            e.printStackTrace();
            mutex.signal();
        }
        return strBehavior;
    }
    
    public void PostEvent()
    {
    }
    
    protected aos.jack.jak.event.Event GetLevelEvent()
        throws java.lang.Exception
    {
        aos.jack.jak.event.Event[] events = cap1.getAgent().getKnownEvents();
        int iSize = events.length;
        for (int i = 0; i < iSize; i++ ) {
            aos.jack.jak.event.Event event1 = (aos.jack.jak.event.Event) events[i];
            java.lang.String strEventName = event1.getEventName();
            if (bDebug) {
                java.lang.System.out.println("Inside AbstractMiniAgent.GetBehavior: event name: [" + strEventName + "]");
            }
            if (strEventName.contains(NeonAffect.Constants.NEON_LEVEL_EVENT) == true) {
                return event1;
            }
        }
        throw new java.lang.Exception("AbstractMiniAgent: GetLeveLEvent: couldn\'t find level event!");
    }
    
    private java.util.ArrayList GetPlans()
    {
        java.util.ArrayList ret = new java.util.ArrayList();
        try {
            if (bDebug) {
                java.lang.System.out.println("Inside AbstractMiniAgent: GetPlans");
            }
            aos.jack.jak.plan.Plan[] plans = cap1.getAgent().getKnownPlans();
            int iLength = plans.length;
            for (int i = 0; i < iLength; i++ ) {
                aos.jack.jak.plan.Plan plan1 = plans[i];
                java.lang.String strPlanName = plan1.getPlanName();
                if (bDebug) {
                    java.lang.System.out.println("Inside AbstractMiniAgent: GetPlans PlanName [" + strPlanName + "]");
                }
                if (NeonAffect.PlanUtils.ContainsCorrectPlan(strPlanName)) {
                    ret.add(strPlanName);
                }
            }
        }
        catch (java.lang.Exception e) {
            e.printStackTrace();
        }
        return ret;
    }
    
    private java.util.ArrayList GetPlansWithFormulas(java.lang.String strModeratorType, java.util.ArrayList planNames)
    {
        try {
            if (bDebug) {
                java.lang.System.out.println("Inside AbstractMiniAgent: GetPlansWithFormulas before post strModeratorType [" + strModeratorType + "] plans.size: " + java.lang.Integer.toString(planNames.size()));
            }
            //get formulas

            postEvent(gsfc.gfc.gfe.post(strModeratorType,planNames));
            mutex.threadWait();
            if (bDebug) {
                java.lang.System.out.println("Inside AbstractMiniAgent: GetPlansWithFormulas before grab formula beliefset.");
            }
            //grab formulas

            postEvent(gpfe.post(iAffectType));
            mutex.threadWait();
        }
        catch (java.lang.Exception e) {
            e.printStackTrace();
            mutex.signal();
        }
        return plansWithFormulas;
    }
    
    private java.util.ArrayList GetSelectedPlans(java.lang.String strInteractionType, java.util.ArrayList planNames)
    {
        try {
            if (bDebug) {
                java.lang.System.out.println("Inside AbstractMiniAgent. before GetSelectPlans post plans.size: " + java.lang.Integer.toString(planNames.size()));
            }
            postEvent(gspe.post(iAffectType,strInteractionType,planNames));
            mutex.threadWait();
            if (bDebug) {
                java.lang.System.out.println("Inside AbstractMiniAgent. after GetSelectPlans post.");
            }
            if (bDebug) {
                java.lang.System.out.println("Inside AbstractMiniAgent.GetSelectPlans: before return: selectedPlans.size: " + java.lang.Integer.toString(selectedPlans.size()));
            }
        }
        catch (java.lang.Exception e) {
            e.printStackTrace();
            mutex.signal();
        }
        return selectedPlans;
    }
    
    public void SetSelectedPlans(java.util.ArrayList selectedPlans1)
    {
        if (bDebug) {
            java.lang.System.out.println("Inside AbstractMiniAgent.SetSelectedPlans");
            int iSize = selectedPlans1.size();
            java.lang.System.out.println("Inside AbstractMiniAgent.SetSelectedPlans: selectedPlans size: " + java.lang.Integer.toString(iSize));
        }
        selectedPlans = (java.util.ArrayList) selectedPlans1.clone();
        if (bDebug) {
            java.lang.System.out.println("Inside AbstractMiniAgent.SetSelectedPlans. after clone method");
        }
    }
    
    public void SetPlansWithFormulas(java.util.ArrayList plansWithFormulas1)
    {
        if (bDebug) {
            java.lang.System.out.println("Inside AbstractMiniAgent.SetPlansWithFormulas");
            int iSize = plansWithFormulas1.size();
            java.lang.System.out.println("Inside AbstractMiniAgent.SetPlanWithFormulas: size: " + java.lang.Integer.toString(iSize));
        }
        plansWithFormulas = (java.util.ArrayList) plansWithFormulas1.clone();
    }
    
    public void SetBehavior(java.lang.String strBehavior1)
    {
        strBehavior = strBehavior1;
    }
    
    public void SetReservoirFormula(java.lang.String strModeratorType, java.lang.String strPlanName, java.lang.String strFormula)
    {
        postEvent(gsfc.sfc.srfe.post(strModeratorType,strPlanName,strFormula));
        mutex.threadWait();
    }
    
    public void SetCognitiveFormula(java.lang.String strModeratorType, java.lang.String strPlanName, java.lang.String strFormula)
    {
        postEvent(gsfc.sfc.scfe.post(strModeratorType,strPlanName,strFormula));
        mutex.threadWait();
    }
    
    public DebugLibrary.DebugBeliefSet GetDebugBeliefSetFormulaCap()
    {
        return gsfc.sfc.dc.debug;
    }
    
    public void SetDebug(boolean bDebug1)
    {
        bDebug = bDebug1;
        postEvent(gsfc.sfc.dc.sde.post(bDebug1));
        mutex.threadWait();
    }
    
    public void Wait(double dValue1)
    {
        postEvent(wc.we.post(dValue1));
        mutex.threadWait();
    }
    
    public java.lang.String getDocumentation()
    {
        return "/**\n * \n */\n";
    }
    
    public java.lang.Class getAgentType()
    {
        return NeonAffect.AbstractMiniAgent.class;
    }
    
    public void __init1()
    {
        super.__init1();
        if (wc == null) {
            wc = new WaitLibrary.WaitCapability(this);
            wc.__initCapability(this,"wc");
        }
        wc.__init1();
        if (cap1 == null) {
            cap1 = new NeonAffect.AbstractAffectCapability(this);
            cap1.__initCapability(this,"cap1");
        }
        cap1.__init1();
        if (gsfc == null) {
            gsfc = new NeonAffect.GetSetFormulasCapability(this);
            gsfc.__initCapability(this,"gsfc");
        }
        gsfc.__init1();
        setNamedCreator("plansFormulas","NeonAffect.PlansWithFormulas",new aos.jack.jak.agent.DataCreator(true){
            public java.lang.Object create()
            {
                return __named_data_plansFormulas();
            }
            
        },true);
        setNamedCreator("planContextName","NeonAffect.PlanContextName",new aos.jack.jak.agent.DataCreator(true){
            public java.lang.Object create()
            {
                return __named_data_planContextName();
            }
            
        },true);
        setNamedCreator("behaviorName","NeonAffect.Behavior",new aos.jack.jak.agent.DataCreator(true){
            public java.lang.Object create()
            {
                return __named_data_behaviorName();
            }
            
        },true);
        setNamedCreator("mutex","aos.jack.util.thread.Semaphore",new aos.jack.jak.agent.DataCreator(true){
            public java.lang.Object create()
            {
                return __named_data_mutex();
            }
            
        },true);
        setNamedCreator("mutex2","aos.jack.util.thread.Semaphore",new aos.jack.jak.agent.DataCreator(true){
            public java.lang.Object create()
            {
                return __named_data_mutex2();
            }
            
        },true);
        setNamedCreator("debug","NeonAffect.NA_Debug",new aos.jack.jak.agent.DataCreator(true){
            public java.lang.Object create()
            {
                return __named_data_debug();
            }
            
        },true);
    }
    
    public void __init2()
    {
        super.__init2();
        wc.__init2();
        cap1.__init2();
        gsfc.__init2();
        ev1 = (NeonAffect.AbstractAffectEvent) findEvent("NeonAffect.AbstractAffectEvent");
        gspe = (NeonAffect.GetSelectedPlansEvent) findEvent("NeonAffect.GetSelectedPlansEvent");
        spce2 = (NeonAffect.SetPlanContextEvent2) findEvent("NeonAffect.SetPlanContextEvent2");
        gbe = (NeonAffect.GetBehaviorEvent) findEvent("NeonAffect.GetBehaviorEvent");
        gpfe = (NeonAffect.GetPlanFormulasEvent) findEvent("NeonAffect.GetPlanFormulasEvent");
        pse = (NeonAffect.PlanSelectorEvent) findEvent("NeonAffect.PlanSelectorEvent");
        getNamedObject("plansFormulas","NeonAffect.PlansWithFormulas");
        getNamedObject("planContextName","NeonAffect.PlanContextName");
        getNamedObject("behaviorName","NeonAffect.Behavior");
        getNamedObject("mutex","aos.jack.util.thread.Semaphore");
        getNamedObject("mutex2","aos.jack.util.thread.Semaphore");
        getNamedObject("debug","NeonAffect.NA_Debug");
    }
    
    synchronized private void __init_desc()
    {
        wc = new WaitLibrary.WaitCapability(this);
        wc.__initCapability(this,"wc");
        wc.init_desc();
        cap1 = new NeonAffect.AbstractAffectCapability(this);
        cap1.__initCapability(this,"cap1");
        cap1.init_desc();
        gsfc = new NeonAffect.GetSetFormulasCapability(this);
        gsfc.__initCapability(this,"gsfc");
        gsfc.init_desc();
        addNamedObject("plansFormulas","NeonAffect.PlansWithFormulas",aos.jack.jak.agent.Agent.WRITEABLE);
        addNamedObject("planContextName","NeonAffect.PlanContextName",aos.jack.jak.agent.Agent.WRITEABLE);
        addNamedObject("behaviorName","NeonAffect.Behavior",aos.jack.jak.agent.Agent.WRITEABLE);
        addNamedObject("mutex","aos.jack.util.thread.Semaphore",0);
        addNamedObject("mutex2","aos.jack.util.thread.Semaphore",aos.jack.jak.agent.Agent.WRITEABLE);
        addNamedObject("debug","NeonAffect.NA_Debug",0);
        addEvent("NeonAffect.AbstractAffectEvent",aos.jack.jak.agent.Agent.HANDLED_EVENT);
        addEvent("NeonAffect.AbstractAffectEvent",aos.jack.jak.agent.Agent.POSTED_EVENT);
        addEvent("NeonAffect.GetSelectedPlansEvent",aos.jack.jak.agent.Agent.HANDLED_EVENT);
        addEvent("NeonAffect.GetSelectedPlansEvent",aos.jack.jak.agent.Agent.POSTED_EVENT);
        addEvent("NeonAffect.SetPlanContextEvent2",aos.jack.jak.agent.Agent.HANDLED_EVENT);
        addEvent("NeonAffect.SetPlanContextEvent2",aos.jack.jak.agent.Agent.POSTED_EVENT);
        addEvent("NeonAffect.GetBehaviorEvent",aos.jack.jak.agent.Agent.HANDLED_EVENT);
        addEvent("NeonAffect.GetBehaviorEvent",aos.jack.jak.agent.Agent.POSTED_EVENT);
        addEvent("NeonAffect.GetPlanFormulasEvent",aos.jack.jak.agent.Agent.HANDLED_EVENT);
        addEvent("NeonAffect.GetPlanFormulasEvent",aos.jack.jak.agent.Agent.POSTED_EVENT);
        addEvent("NeonAffect.PlanSelectorEvent",aos.jack.jak.agent.Agent.SENT_EVENT);
        addPlan("NeonAffect.GetBehaviorPlan",0);
        addPlan("NeonAffect.GetPlanFormulasPlan",0);
        addPlan("NeonAffect.GetSelectedPlansPlan",0);
        addPlan("NeonAffect.SetPlanContextPlan2",0);
    }
    
    public void init_desc()
    {
        newAgentDesc("AbstractMiniAgent");
        super.init_desc();
        __init_desc();
    }
    
    synchronized public void __bindNames()
    {
        super.__bindNames();
        wc.__bindNames();
        cap1.__bindNames();
        gsfc.__bindNames();
    }
    
    public void setEnabled(boolean t)
    {
        super.setEnabled(t);
        wc.setEnabled(t);
        cap1.setEnabled(t);
        gsfc.setEnabled(t);
    }
    
    private NeonAffect.PlansWithFormulas __named_data_plansFormulas()
    {
        if (plansFormulas != null) 
            return plansFormulas;
        plansFormulas = new NeonAffect.PlansWithFormulas();
        if (!plansFormulas.attach(this)) 
            plansFormulas = null;
        setNamedObject("plansFormulas","NeonAffect.PlansWithFormulas",plansFormulas);
        return plansFormulas;
    }
    
    private NeonAffect.PlanContextName __named_data_planContextName()
    {
        if (planContextName != null) 
            return planContextName;
        planContextName = new NeonAffect.PlanContextName();
        if (!planContextName.attach(this)) 
            planContextName = null;
        setNamedObject("planContextName","NeonAffect.PlanContextName",planContextName);
        return planContextName;
    }
    
    private NeonAffect.Behavior __named_data_behaviorName()
    {
        if (behaviorName != null) 
            return behaviorName;
        behaviorName = new NeonAffect.Behavior();
        if (!behaviorName.attach(this)) 
            behaviorName = null;
        setNamedObject("behaviorName","NeonAffect.Behavior",behaviorName);
        return behaviorName;
    }
    
    private aos.jack.util.thread.Semaphore __named_data_mutex()
    {
        if (mutex != null) 
            return mutex;
        mutex = (aos.jack.util.thread.Semaphore) findShared("mutex","aos.jack.util.thread.Semaphore");
        if (mutex != null) {
            setNamedObject("mutex","aos.jack.util.thread.Semaphore",mutex);
            return mutex;
        }
        mutex = new aos.jack.util.thread.Semaphore();
        addShared("mutex","aos.jack.util.thread.Semaphore",mutex);
        setNamedObject("mutex","aos.jack.util.thread.Semaphore",mutex);
        return mutex;
    }
    
    private aos.jack.util.thread.Semaphore __named_data_mutex2()
    {
        if (mutex2 != null) 
            return mutex2;
        mutex2 = new aos.jack.util.thread.Semaphore();
        setNamedObject("mutex2","aos.jack.util.thread.Semaphore",mutex2);
        return mutex2;
    }
    
    private NeonAffect.NA_Debug __named_data_debug()
    {
        if (debug != null) 
            return debug;
        debug = (NeonAffect.NA_Debug) findGlobal("debug","NeonAffect.NA_Debug");
        if (debug != null) {
            setNamedObject("debug","NeonAffect.NA_Debug",debug);
            return debug;
        }
        debug = new NeonAffect.NA_Debug(true);
        if (!debug.attach(this)) 
            debug = null;
        addGlobal("debug","NeonAffect.NA_Debug",debug);
        setNamedObject("debug","NeonAffect.NA_Debug",debug);
        return debug;
    }
    
    public aos.jack.jak.task.TaskManager createTaskManager()
    {
        return new aos.cojack.base.CatMan(this);
    }
    
}
