/*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*
  This code is generated by JAC version 5.6 by
  Agent Oriented Software. http://www.agent-software.com.au

    DO NOT ALTER THIS CODE AND DO NOT REMOVE THIS COMMENT
 *=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*/
package NeonAffect;
import aos.jack.jak.core.Jak;
import aos.jack.jak.event.EventRecipient;
import aos.jack.jak.beliefset.OpenWorld;
import aos.jack.jak.beliefset.OpenWorldCursor;
import aos.jack.jak.beliefset.BeliefSetCursor;
import aos.jack.jak.beliefset.BeliefSetException;
import aos.jack.jak.beliefset.Tuple;
import aos.jack.jak.beliefset.BeliefSet;
import aos.jack.jak.logic.ChoicePoint;
import aos.jack.jak.logic.Variable;
import aos.jack.jak.cursor.BeliefState;
import aos.jack.jak.cursor.Cursor;

/**
 * 
 */

public class Expectancy extends aos.jack.jak.beliefset.OpenWorld {
    static public NeonAffect.Expectancy__Tuple __hole = new NeonAffect.Expectancy__Tuple(true);
    public NeonAffect.Expectancy__Tuple[][] __tables;
    public java.lang.String getDocumentation()
    {
        return "/**\n * \n */\n";
    }
    
    public boolean attach(aos.jack.jak.event.EventRecipient __h)
    {
        java.lang.Object __o = __h;
        if (!super.attach(__h)) 
            return false;
        return true;
    }
    
    public aos.jack.jak.beliefset.BeliefSetCursor get(int __v0, aos.jack.jak.logic.DoubleVariable __v1)
        throws aos.jack.jak.beliefset.BeliefSetException
    {
        NeonAffect.Expectancy__Tuple __t = new NeonAffect.Expectancy__Tuple();
        NeonAffect.Expectancy.__Cursor __c = new NeonAffect.Expectancy.__Cursor(__t);
        __t.id = __v0;
        if (!__v1.check_unifiable(java.lang.Double.TYPE)) 
            throw new aos.jack.jak.beliefset.BeliefSetException("Expectancy:get:IO: arg 1 dValue Incorrect Variable type");
        if (__v1.isGround()) {
            try {
                __t.dValue = __v1.as_double();
            }
            catch (java.lang.Exception e) {
                throw new aos.jack.jak.beliefset.BeliefSetException("Expectancy:get:IO: got " + e.toString());
            }
        }
         else 
            __c.dValue = __v1;
        __c.init(0,this);
        return __c;
    }
    
    public int keyIndex()
    {
        return 0;
    }
    
    public int fullIndex()
    {
        return 0;
    }
    
    public int nIndexes()
    {
        return 1;
    }
    
    public aos.jack.jak.beliefset.Tuple newTuple()
    {
        return new NeonAffect.Expectancy__Tuple();
    }
    
    public aos.jack.jak.beliefset.Tuple getTuple(int t, int l)
    {
        return __tables[t][l];
    }
    
    public aos.jack.jak.beliefset.Tuple[] newTable(int t)
    {
        return new NeonAffect.Expectancy__Tuple[t];
    }
    
    public aos.jack.jak.beliefset.Tuple[][] newTables(int t)
    {
        return new NeonAffect.Expectancy__Tuple[t][];
    }
    
    public aos.jack.jak.beliefset.Tuple[] getTable(int t)
    {
        return __tables[t];
    }
    
    public aos.jack.jak.beliefset.Tuple[][] getTables()
    {
        return __tables;
    }
    
    public void setTables(aos.jack.jak.beliefset.Tuple[][] t)
    {
        __tables = (NeonAffect.Expectancy__Tuple[][]) t;
    }
    
    public aos.jack.jak.beliefset.BeliefSetCursor newCursor(aos.jack.jak.beliefset.Tuple __t)
    {
        if (__t instanceof NeonAffect.Expectancy__Tuple) 
            return new NeonAffect.Expectancy.__Cursor((NeonAffect.Expectancy__Tuple) __t);
        return null;
    }
    
    public void add(int __v0, double __v1)
        throws aos.jack.jak.beliefset.BeliefSetException
    {
        add(__v0,__v1,aos.jack.jak.cursor.Cursor.TRUE);
    }
    
    public void add(int __v0, double __v1, aos.jack.jak.cursor.BeliefState __d)
        throws aos.jack.jak.beliefset.BeliefSetException
    {
        NeonAffect.Expectancy__Tuple __t = new NeonAffect.Expectancy__Tuple();
        __t.id = __v0;
        __t.dValue = __v1;
        super.assertTuple(__t,__d);
    }
    
    public void remove(int __v0, double __v1)
        throws aos.jack.jak.beliefset.BeliefSetException
    {
        remove(__v0,__v1,aos.jack.jak.cursor.Cursor.TRUE);
    }
    
    public void remove(int __v0, double __v1, aos.jack.jak.cursor.BeliefState __d)
        throws aos.jack.jak.beliefset.BeliefSetException
    {
        NeonAffect.Expectancy__Tuple __t = new NeonAffect.Expectancy__Tuple();
        __t.id = __v0;
        __t.dValue = __v1;
        super.retractTuple(__t,__d);
    }
    
    public Expectancy()
    {
    }
    
    public Expectancy(java.lang.String n)
    {
        super();
        read(n);
    }
    
    class __Cursor extends aos.jack.jak.beliefset.OpenWorldCursor {
        public NeonAffect.Expectancy__Tuple __tuple = null;
        public aos.jack.jak.logic.Variable id;
        public aos.jack.jak.logic.Variable dValue;
        public __Cursor()
        {
            __tuple = __hole;
        }
        
        public __Cursor(NeonAffect.Expectancy__Tuple __t)
        {
            super();
            __tuple = __t;
        }
        
        public int match(int __ti, int __st, int __c, boolean __k, int __ind)
        {
            NeonAffect.Expectancy__Tuple[] __tab = __tables[__ti];
            NeonAffect.Expectancy__Tuple __t;
            int __sz = __tab.length;
            int __i;
            if ((aos.jack.jak.core.Jak.debugging & aos.jack.jak.core.Jak.LOG_DB) != 0) {
                aos.jack.jak.core.Jak.log.log("Expectancy__Tuple:match:" + __ti + ":" + __st + ":" + __c + ":" + __k + ":" + __ind);
                aos.jack.jak.core.Jak.log.log("Tuple=" + __tuple);
                aos.jack.jak.core.Jak.log.log("Outputs are");
                aos.jack.jak.core.Jak.log.log("  id:" + id);
                aos.jack.jak.core.Jak.log.log("  dValue:" + dValue);
            }
            for (__i = __st; __c > 0; __i = (__i + 1) % __sz, __c-- ) {
                __t = __tab[__i];
                if (__t == null) {
                    if (__ind < 0) 
                        continue;
                    return -1;
                }
                if (__t == __hole) 
                    continue;
                if (__t.isFree) {
                    __tab[__i] = __hole;
                    continue;
                }
                if ((aos.jack.jak.core.Jak.debugging & aos.jack.jak.core.Jak.LOG_DB) != 0) 
                    aos.jack.jak.core.Jak.log.log("t" + __i + ":" + __t);
                try {
                    if (cp != null) 
                        cp.backtrack();
                    if (id == null) {
                        if (__tuple.id != __t.id) 
                            continue;
                    }
                     else {
                        if (!id.unify(__t.id)) 
                            continue;
                    }
                    if (__k) 
                        return __i;
                    if (dValue == null) {
                        if (__tuple.dValue != __t.dValue) 
                            continue;
                    }
                     else {
                        if (!dValue.unify(__t.dValue)) 
                            continue;
                    }
                }
                catch (java.lang.Exception e) {
                    continue;
                }
                return __i;
            }
            return -1;
        }
        
        public int hash(int __i)
        {
            return (__tuple == null?0:__tuple.hash(__i));
        }
        
        public aos.jack.jak.logic.ChoicePoint getChoicePoint()
        {
            if (id != null) 
                return id.getEnv().newChoicePoint();
            if (dValue != null) 
                return dValue.getEnv().newChoicePoint();
            return null;
        }
        
        public boolean isKeyGround()
        {
            if (id != null) 
                return false;
            return true;
        }
        
    }
}
