/*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*
  This code is generated by JAC version 5.6 by
  Agent Oriented Software. http://www.agent-software.com.au

    DO NOT ALTER THIS CODE AND DO NOT REMOVE THIS COMMENT
 *=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*/
package NeonAffect;
import aos.jack.jak.agent.Capability;
import aos.jack.jak.agent.NameSpace;
import aos.jack.jak.agent.Agent;
import aos.jack.util.thread.Semaphore;

/**
 * 
 */

public class ConcentratingAffectCapability extends aos.jack.jak.agent.Capability {
    public NeonAffect.PlanContextName planContextName;
    public NeonAffect.Behavior behaviorName;
    public aos.jack.util.thread.Semaphore mutex;
    public aos.jack.util.thread.Semaphore mutex2;
    public NeonAffect.NA_Debug debug;
    public NeonAffect.ContextEvent ce;
    public java.lang.String getDocumentation()
    {
        return "/**\n * \n */\n";
    }
    
    public void __init1()
    {
        setNamedCreator("planContextName","NeonAffect.PlanContextName",new aos.jack.jak.agent.DataCreator(false){
            public java.lang.Object create()
            {
                return __named_data_planContextName();
            }
            
        },true);
        setNamedCreator("behaviorName","NeonAffect.Behavior",new aos.jack.jak.agent.DataCreator(false){
            public java.lang.Object create()
            {
                return __named_data_behaviorName();
            }
            
        },true);
        setNamedCreator("mutex","aos.jack.util.thread.Semaphore",new aos.jack.jak.agent.DataCreator(false){
            public java.lang.Object create()
            {
                return __named_data_mutex();
            }
            
        },true);
        setNamedCreator("mutex2","aos.jack.util.thread.Semaphore",new aos.jack.jak.agent.DataCreator(false){
            public java.lang.Object create()
            {
                return __named_data_mutex2();
            }
            
        },true);
        setNamedCreator("debug","NeonAffect.NA_Debug",new aos.jack.jak.agent.DataCreator(false){
            public java.lang.Object create()
            {
                return __named_data_debug();
            }
            
        },true);
    }
    
    public void __init2()
    {
        ce = (NeonAffect.ContextEvent) findEvent("NeonAffect.ContextEvent");
        planContextName = (NeonAffect.PlanContextName) getNamedObject("planContextName","NeonAffect.PlanContextName");
        behaviorName = (NeonAffect.Behavior) getNamedObject("behaviorName","NeonAffect.Behavior");
        mutex = (aos.jack.util.thread.Semaphore) getNamedObject("mutex","aos.jack.util.thread.Semaphore");
        mutex2 = (aos.jack.util.thread.Semaphore) getNamedObject("mutex2","aos.jack.util.thread.Semaphore");
        debug = (NeonAffect.NA_Debug) getNamedObject("debug","NeonAffect.NA_Debug");
        autorun();
    }
    
    synchronized public void __init_desc()
    {
        externals.put("debug","debug");
        externals.put("mutex2","mutex2");
        externals.put("mutex","mutex");
        externals.put("behaviorName","behaviorName");
        externals.put("planContextName","planContextName");
        externals.put("NeonAffect.SetPlanContextEvent","NeonAffect.SetPlanContextEvent");
        externals.put("NeonAffect.Level1PosAffectEvent","NeonAffect.Level1PosAffectEvent");
        addEvent("NeonAffect.Level1PosAffectEvent",aos.jack.jak.agent.Agent.HANDLED_EVENT);
        addEvent("NeonAffect.SetPlanContextEvent",aos.jack.jak.agent.Agent.HANDLED_EVENT);
        addEvent("NeonAffect.ContextEvent",aos.jack.jak.agent.Agent.SENT_EVENT);
        addPlan("NeonAffect.AnalyzingDetailsPlan",0);
        addPlan("NeonAffect.ArticulatingThoughtsCarefullyPlan",0);
        addPlan("NeonAffect.AskQuestionsConcentratingPlan",0);
        addPlan("NeonAffect.BreathingStoppedBrieflyPlan",0);
        addPlan("NeonAffect.BlinkingSlowlyConcentratingPlan",0);
        addPlan("NeonAffect.DelayedResponseConcentratingPlan",0);
        addPlan("NeonAffect.FocusedAttentionPlan",0);
        addPlan("NeonAffect.FocusingOnTasksConcentratingPlan",0);
        addPlan("NeonAffect.IgnoringDisruptionsConcentratingPlan",0);
        addPlan("NeonAffect.IgnoringSurroundingsPlan",0);
        addPlan("NeonAffect.LimitingConversationPlan",0);
        addPlan("NeonAffect.LipBitingConcentrationPlan",0);
        addPlan("NeonAffect.MentallyOrganzingThoughtsPlan",0);
        addPlan("NeonAffect.MinimizingUnnecessaryTalkPlan",0);
        addPlan("NeonAffect.MutteringCalculationsPlan",0);
        addPlan("NeonAffect.ProcessingInformationDeeplyPlan",0);
        addPlan("NeonAffect.RepeatToSelfPlan",0);
        addPlan("NeonAffect.RequestingQuietPlan",0);
        addPlan("NeonAffect.SlowBodyMovementsConcentratingPlan",0);
        addPlan("NeonAffect.SpeakSlowlyConcentratingPlan",0);
        addPlan("NeonAffect.SquintEyesConcentratingPlan",0);
        addPlan("NeonAffect.StaringConcentratingPlan",0);
        addPlan("NeonAffect.TiltHeadConcentratingPlan",0);
        addPlan("NeonAffect.UsingFocusedLanguagePlan",0);
        addPlan("NeonAffect.VerbalizingStepsPlan",0);
        addPlan("NeonAffect.VisualizingProblemsPlan",0);
        addPlan("NeonAffect.SetPlanContextConcentratingPlan",0);
    }
    
    public ConcentratingAffectCapability(aos.jack.jak.agent.NameSpace outer)
    {
        super(outer);
    }
    
    synchronized public void __bindNames()
    {
        super.__bindNames();
        __bindToPlan("NeonAffect.AnalyzingDetailsPlan");
        __bindToPlan("NeonAffect.ArticulatingThoughtsCarefullyPlan");
        __bindToPlan("NeonAffect.AskQuestionsConcentratingPlan");
        __bindToPlan("NeonAffect.BreathingStoppedBrieflyPlan");
        __bindToPlan("NeonAffect.BlinkingSlowlyConcentratingPlan");
        __bindToPlan("NeonAffect.DelayedResponseConcentratingPlan");
        __bindToPlan("NeonAffect.FocusedAttentionPlan");
        __bindToPlan("NeonAffect.FocusingOnTasksConcentratingPlan");
        __bindToPlan("NeonAffect.IgnoringDisruptionsConcentratingPlan");
        __bindToPlan("NeonAffect.IgnoringSurroundingsPlan");
        __bindToPlan("NeonAffect.LimitingConversationPlan");
        __bindToPlan("NeonAffect.LipBitingConcentrationPlan");
        __bindToPlan("NeonAffect.MentallyOrganzingThoughtsPlan");
        __bindToPlan("NeonAffect.MinimizingUnnecessaryTalkPlan");
        __bindToPlan("NeonAffect.MutteringCalculationsPlan");
        __bindToPlan("NeonAffect.ProcessingInformationDeeplyPlan");
        __bindToPlan("NeonAffect.RepeatToSelfPlan");
        __bindToPlan("NeonAffect.RequestingQuietPlan");
        __bindToPlan("NeonAffect.SlowBodyMovementsConcentratingPlan");
        __bindToPlan("NeonAffect.SpeakSlowlyConcentratingPlan");
        __bindToPlan("NeonAffect.SquintEyesConcentratingPlan");
        __bindToPlan("NeonAffect.StaringConcentratingPlan");
        __bindToPlan("NeonAffect.TiltHeadConcentratingPlan");
        __bindToPlan("NeonAffect.UsingFocusedLanguagePlan");
        __bindToPlan("NeonAffect.VerbalizingStepsPlan");
        __bindToPlan("NeonAffect.VisualizingProblemsPlan");
        __bindToPlan("NeonAffect.SetPlanContextConcentratingPlan");
    }
    
    private NeonAffect.PlanContextName __named_data_planContextName()
    {
        planContextName = (NeonAffect.PlanContextName) getNamedObject("planContextName","NeonAffect.PlanContextName");
        return planContextName;
    }
    
    private NeonAffect.Behavior __named_data_behaviorName()
    {
        behaviorName = (NeonAffect.Behavior) getNamedObject("behaviorName","NeonAffect.Behavior");
        return behaviorName;
    }
    
    private aos.jack.util.thread.Semaphore __named_data_mutex()
    {
        mutex = (aos.jack.util.thread.Semaphore) getNamedObject("mutex","aos.jack.util.thread.Semaphore");
        return mutex;
    }
    
    private aos.jack.util.thread.Semaphore __named_data_mutex2()
    {
        mutex2 = (aos.jack.util.thread.Semaphore) getNamedObject("mutex2","aos.jack.util.thread.Semaphore");
        return mutex2;
    }
    
    private NeonAffect.NA_Debug __named_data_debug()
    {
        debug = (NeonAffect.NA_Debug) getNamedObject("debug","NeonAffect.NA_Debug");
        return debug;
    }
    
}
