/*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*
  This code is generated by JAC version 5.6 by
  Agent Oriented Software. http://www.agent-software.com.au

    DO NOT ALTER THIS CODE AND DO NOT REMOVE THIS COMMENT
 *=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*/
package NeonAffect;
import aos.jack.jak.agent.Capability;
import aos.jack.jak.agent.NameSpace;
import aos.jack.jak.agent.Agent;
import aos.jack.util.thread.Semaphore;

/**
 * 
 */

public class InfluentialAffectCapability extends aos.jack.jak.agent.Capability {
    public NeonAffect.PlanContextName planContextName;
    public NeonAffect.Behavior behaviorName;
    public aos.jack.util.thread.Semaphore mutex;
    public aos.jack.util.thread.Semaphore mutex2;
    public NeonAffect.NA_Debug debug;
    public NeonAffect.ContextEvent ce;
    public java.lang.String getDocumentation()
    {
        return "/**\n * \n */\n";
    }
    
    public void __init1()
    {
        setNamedCreator("planContextName","NeonAffect.PlanContextName",new aos.jack.jak.agent.DataCreator(false){
            public java.lang.Object create()
            {
                return __named_data_planContextName();
            }
            
        },true);
        setNamedCreator("behaviorName","NeonAffect.Behavior",new aos.jack.jak.agent.DataCreator(false){
            public java.lang.Object create()
            {
                return __named_data_behaviorName();
            }
            
        },true);
        setNamedCreator("mutex","aos.jack.util.thread.Semaphore",new aos.jack.jak.agent.DataCreator(false){
            public java.lang.Object create()
            {
                return __named_data_mutex();
            }
            
        },true);
        setNamedCreator("mutex2","aos.jack.util.thread.Semaphore",new aos.jack.jak.agent.DataCreator(false){
            public java.lang.Object create()
            {
                return __named_data_mutex2();
            }
            
        },true);
        setNamedCreator("debug","NeonAffect.NA_Debug",new aos.jack.jak.agent.DataCreator(false){
            public java.lang.Object create()
            {
                return __named_data_debug();
            }
            
        },true);
    }
    
    public void __init2()
    {
        ce = (NeonAffect.ContextEvent) findEvent("NeonAffect.ContextEvent");
        planContextName = (NeonAffect.PlanContextName) getNamedObject("planContextName","NeonAffect.PlanContextName");
        behaviorName = (NeonAffect.Behavior) getNamedObject("behaviorName","NeonAffect.Behavior");
        mutex = (aos.jack.util.thread.Semaphore) getNamedObject("mutex","aos.jack.util.thread.Semaphore");
        mutex2 = (aos.jack.util.thread.Semaphore) getNamedObject("mutex2","aos.jack.util.thread.Semaphore");
        debug = (NeonAffect.NA_Debug) getNamedObject("debug","NeonAffect.NA_Debug");
        autorun();
    }
    
    synchronized public void __init_desc()
    {
        externals.put("debug","debug");
        externals.put("mutex2","mutex2");
        externals.put("mutex","mutex");
        externals.put("behaviorName","behaviorName");
        externals.put("planContextName","planContextName");
        externals.put("NeonAffect.SetPlanContextEvent","NeonAffect.SetPlanContextEvent");
        externals.put("NeonAffect.Level5PosAffectEvent","NeonAffect.Level5PosAffectEvent");
        addEvent("NeonAffect.Level5PosAffectEvent",aos.jack.jak.agent.Agent.HANDLED_EVENT);
        addEvent("NeonAffect.SetPlanContextEvent",aos.jack.jak.agent.Agent.HANDLED_EVENT);
        addEvent("NeonAffect.ContextEvent",aos.jack.jak.agent.Agent.SENT_EVENT);
        addPlan("NeonAffect.AdaptiveLeadershipPlan",0);
        addPlan("NeonAffect.AskQuestionsInfluentialPlan",0);
        addPlan("NeonAffect.AttentiveBodyLanguagePlan",0);
        addPlan("NeonAffect.CharmingDemeanorPlan",0);
        addPlan("NeonAffect.CharmingEloquencePlan",0);
        addPlan("NeonAffect.CommandingPresencePlan",0);
        addPlan("NeonAffect.ConfidentPostureInfluentialPlan",0);
        addPlan("NeonAffect.ConfidentVoiceInfluentialPlan",0);
        addPlan("NeonAffect.EffectiveNegotiationPlan",0);
        addPlan("NeonAffect.EmpatheticUnderstandingPlan",0);
        addPlan("NeonAffect.EmpoweringEncouragmentPlan",0);
        addPlan("NeonAffect.EyeContactInfluentialPlan",0);
        addPlan("NeonAffect.FacialExpressionsInfluentialPlan",0);
        addPlan("NeonAffect.GracefulHandGesutresPlan",0);
        addPlan("NeonAffect.InnovativeThinkingInfluentialPlan",0);
        addPlan("NeonAffect.ListeningIntentlyInfluentialPlan",0);
        addPlan("NeonAffect.PersuasiveSpeechInfluentialPlan",0);
        addPlan("NeonAffect.SmilingInfluentialPlan",0);
        addPlan("NeonAffect.SpeakToInspireInfluentialPlan",0);
        addPlan("NeonAffect.StrategicNetworkingPlan",0);
        addPlan("NeonAffect.StrategicWordChoicePlan",0);
        addPlan("NeonAffect.TrendSettingPlan",0);
        addPlan("NeonAffect.VisionarySolutionsPlan",0);
        addPlan("NeonAffect.SetPlanContextInfluentialPlan",0);
    }
    
    public InfluentialAffectCapability(aos.jack.jak.agent.NameSpace outer)
    {
        super(outer);
    }
    
    synchronized public void __bindNames()
    {
        super.__bindNames();
        __bindToPlan("NeonAffect.AdaptiveLeadershipPlan");
        __bindToPlan("NeonAffect.AskQuestionsInfluentialPlan");
        __bindToPlan("NeonAffect.AttentiveBodyLanguagePlan");
        __bindToPlan("NeonAffect.CharmingDemeanorPlan");
        __bindToPlan("NeonAffect.CharmingEloquencePlan");
        __bindToPlan("NeonAffect.CommandingPresencePlan");
        __bindToPlan("NeonAffect.ConfidentPostureInfluentialPlan");
        __bindToPlan("NeonAffect.ConfidentVoiceInfluentialPlan");
        __bindToPlan("NeonAffect.EffectiveNegotiationPlan");
        __bindToPlan("NeonAffect.EmpatheticUnderstandingPlan");
        __bindToPlan("NeonAffect.EmpoweringEncouragmentPlan");
        __bindToPlan("NeonAffect.EyeContactInfluentialPlan");
        __bindToPlan("NeonAffect.FacialExpressionsInfluentialPlan");
        __bindToPlan("NeonAffect.GracefulHandGesutresPlan");
        __bindToPlan("NeonAffect.InnovativeThinkingInfluentialPlan");
        __bindToPlan("NeonAffect.ListeningIntentlyInfluentialPlan");
        __bindToPlan("NeonAffect.PersuasiveSpeechInfluentialPlan");
        __bindToPlan("NeonAffect.SmilingInfluentialPlan");
        __bindToPlan("NeonAffect.SpeakToInspireInfluentialPlan");
        __bindToPlan("NeonAffect.StrategicNetworkingPlan");
        __bindToPlan("NeonAffect.StrategicWordChoicePlan");
        __bindToPlan("NeonAffect.TrendSettingPlan");
        __bindToPlan("NeonAffect.VisionarySolutionsPlan");
        __bindToPlan("NeonAffect.SetPlanContextInfluentialPlan");
    }
    
    private NeonAffect.PlanContextName __named_data_planContextName()
    {
        planContextName = (NeonAffect.PlanContextName) getNamedObject("planContextName","NeonAffect.PlanContextName");
        return planContextName;
    }
    
    private NeonAffect.Behavior __named_data_behaviorName()
    {
        behaviorName = (NeonAffect.Behavior) getNamedObject("behaviorName","NeonAffect.Behavior");
        return behaviorName;
    }
    
    private aos.jack.util.thread.Semaphore __named_data_mutex()
    {
        mutex = (aos.jack.util.thread.Semaphore) getNamedObject("mutex","aos.jack.util.thread.Semaphore");
        return mutex;
    }
    
    private aos.jack.util.thread.Semaphore __named_data_mutex2()
    {
        mutex2 = (aos.jack.util.thread.Semaphore) getNamedObject("mutex2","aos.jack.util.thread.Semaphore");
        return mutex2;
    }
    
    private NeonAffect.NA_Debug __named_data_debug()
    {
        debug = (NeonAffect.NA_Debug) getNamedObject("debug","NeonAffect.NA_Debug");
        return debug;
    }
    
}
