/*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*
  This code is generated by JAC version 5.6 by
  Agent Oriented Software. http://www.agent-software.com.au

    DO NOT ALTER THIS CODE AND DO NOT REMOVE THIS COMMENT
 *=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*/
package NeonAffect;
import aos.jack.jak.agent.Capability;
import aos.jack.jak.agent.NameSpace;
import aos.jack.jak.agent.Agent;
import aos.jack.util.thread.Semaphore;

/**
 * 
 */

public class RageAffectCapability extends aos.jack.jak.agent.Capability {
    public NeonAffect.PlanContextName planContextName;
    public aos.jack.util.thread.Semaphore mutex;
    public aos.jack.util.thread.Semaphore mutex2;
    public NeonAffect.Behavior behaviorName;
    public NeonAffect.NA_Debug debug;
    public NeonAffect.ContextEvent ce;
    public java.lang.String getDocumentation()
    {
        return "/**\n * \n */\n";
    }
    
    public void __init1()
    {
        setNamedCreator("planContextName","NeonAffect.PlanContextName",new aos.jack.jak.agent.DataCreator(false){
            public java.lang.Object create()
            {
                return __named_data_planContextName();
            }
            
        },true);
        setNamedCreator("mutex","aos.jack.util.thread.Semaphore",new aos.jack.jak.agent.DataCreator(false){
            public java.lang.Object create()
            {
                return __named_data_mutex();
            }
            
        },true);
        setNamedCreator("mutex2","aos.jack.util.thread.Semaphore",new aos.jack.jak.agent.DataCreator(false){
            public java.lang.Object create()
            {
                return __named_data_mutex2();
            }
            
        },true);
        setNamedCreator("behaviorName","NeonAffect.Behavior",new aos.jack.jak.agent.DataCreator(false){
            public java.lang.Object create()
            {
                return __named_data_behaviorName();
            }
            
        },true);
        setNamedCreator("debug","NeonAffect.NA_Debug",new aos.jack.jak.agent.DataCreator(false){
            public java.lang.Object create()
            {
                return __named_data_debug();
            }
            
        },true);
    }
    
    public void __init2()
    {
        ce = (NeonAffect.ContextEvent) findEvent("NeonAffect.ContextEvent");
        planContextName = (NeonAffect.PlanContextName) getNamedObject("planContextName","NeonAffect.PlanContextName");
        mutex = (aos.jack.util.thread.Semaphore) getNamedObject("mutex","aos.jack.util.thread.Semaphore");
        mutex2 = (aos.jack.util.thread.Semaphore) getNamedObject("mutex2","aos.jack.util.thread.Semaphore");
        behaviorName = (NeonAffect.Behavior) getNamedObject("behaviorName","NeonAffect.Behavior");
        debug = (NeonAffect.NA_Debug) getNamedObject("debug","NeonAffect.NA_Debug");
        autorun();
    }
    
    synchronized public void __init_desc()
    {
        externals.put("debug","debug");
        externals.put("behaviorName","behaviorName");
        externals.put("mutex2","mutex2");
        externals.put("mutex","mutex");
        externals.put("planContextName","planContextName");
        externals.put("NeonAffect.SetPlanContextEvent","NeonAffect.SetPlanContextEvent");
        externals.put("NeonAffect.Level6NegAffectEvent","NeonAffect.Level6NegAffectEvent");
        addEvent("NeonAffect.Level6NegAffectEvent",aos.jack.jak.agent.Agent.HANDLED_EVENT);
        addEvent("NeonAffect.SetPlanContextEvent",aos.jack.jak.agent.Agent.HANDLED_EVENT);
        addEvent("NeonAffect.ContextEvent",aos.jack.jak.agent.Agent.SENT_EVENT);
        addPlan("NeonAffect.HoldingBackCriticismPlan",0);
        addPlan("NeonAffect.UpsetOverLittleThingPlan",0);
        addPlan("NeonAffect.PickFightPlan",0);
        addPlan("NeonAffect.CrackKnucklesIntimidatePlan",0);
        addPlan("NeonAffect.ScreamPlan",0);
        addPlan("NeonAffect.StaringDownRagePlan",0);
        addPlan("NeonAffect.ManipulatePlan",0);
        addPlan("NeonAffect.PainSuspensionPlan",0);
        addPlan("NeonAffect.IncreasedStrengthPlan",0);
        addPlan("NeonAffect.TwitchyFeelingPlan",0);
        addPlan("NeonAffect.NoConsequencesPlan",0);
        addPlan("NeonAffect.DominateControlPlan",0);
        addPlan("NeonAffect.HardToConcentratePlan",0);
        addPlan("NeonAffect.DepressionPlan",0);
        addPlan("NeonAffect.FatiguePlan",0);
        addPlan("NeonAffect.SetPlanContextRagePlan",0);
    }
    
    public RageAffectCapability(aos.jack.jak.agent.NameSpace outer)
    {
        super(outer);
    }
    
    synchronized public void __bindNames()
    {
        super.__bindNames();
        __bindToPlan("NeonAffect.HoldingBackCriticismPlan");
        __bindToPlan("NeonAffect.UpsetOverLittleThingPlan");
        __bindToPlan("NeonAffect.PickFightPlan");
        __bindToPlan("NeonAffect.CrackKnucklesIntimidatePlan");
        __bindToPlan("NeonAffect.ScreamPlan");
        __bindToPlan("NeonAffect.StaringDownRagePlan");
        __bindToPlan("NeonAffect.ManipulatePlan");
        __bindToPlan("NeonAffect.PainSuspensionPlan");
        __bindToPlan("NeonAffect.IncreasedStrengthPlan");
        __bindToPlan("NeonAffect.TwitchyFeelingPlan");
        __bindToPlan("NeonAffect.NoConsequencesPlan");
        __bindToPlan("NeonAffect.DominateControlPlan");
        __bindToPlan("NeonAffect.HardToConcentratePlan");
        __bindToPlan("NeonAffect.DepressionPlan");
        __bindToPlan("NeonAffect.FatiguePlan");
        __bindToPlan("NeonAffect.SetPlanContextRagePlan");
    }
    
    private NeonAffect.PlanContextName __named_data_planContextName()
    {
        planContextName = (NeonAffect.PlanContextName) getNamedObject("planContextName","NeonAffect.PlanContextName");
        return planContextName;
    }
    
    private aos.jack.util.thread.Semaphore __named_data_mutex()
    {
        mutex = (aos.jack.util.thread.Semaphore) getNamedObject("mutex","aos.jack.util.thread.Semaphore");
        return mutex;
    }
    
    private aos.jack.util.thread.Semaphore __named_data_mutex2()
    {
        mutex2 = (aos.jack.util.thread.Semaphore) getNamedObject("mutex2","aos.jack.util.thread.Semaphore");
        return mutex2;
    }
    
    private NeonAffect.Behavior __named_data_behaviorName()
    {
        behaviorName = (NeonAffect.Behavior) getNamedObject("behaviorName","NeonAffect.Behavior");
        return behaviorName;
    }
    
    private NeonAffect.NA_Debug __named_data_debug()
    {
        debug = (NeonAffect.NA_Debug) getNamedObject("debug","NeonAffect.NA_Debug");
        return debug;
    }
    
}
