/*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*
  This code is generated by JAC version 5.6 by
  Agent Oriented Software. http://www.agent-software.com.au

    DO NOT ALTER THIS CODE AND DO NOT REMOVE THIS COMMENT
 *=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*/
package NeonAffect;
import aos.jack.jak.plan.PlanFSM;
import aos.jack.jak.plan.ExMap;
import aos.jack.jak.agent.NameSpace;
import aos.jack.jak.event.Event;
import aos.jack.jak.task.Task;
import aos.jack.jak.core.Generator;
import aos.jack.jak.logic.Signature;
import aos.jack.jak.plan.Plan;
import aos.jack.util.thread.Semaphore;
import java.util.ArrayList;
import CoJACKConfigParserXML.parser;
import java.lang.Object;
import aos.jack.jak.cursor.Cursor;
import aos.jack.jak.fsm.FSM;
import aos.jack.jak.core.Jak;

/**
 * 
 */

public class GetFormulasPlan extends aos.jack.jak.plan.Plan {
    private boolean bDebug = false;
    private java.lang.String strPlanWithFormula = "";
    private static java.lang.Class __exClass_0 = aos.jack.jak.fsm.FSM.loadClass("java.lang.Exception");
    public NeonAffect.GetFormulasEvent gfe;
    public NeonAffect.PlansWithFormulas plansFormulas;
    public aos.jack.util.thread.Semaphore mutex;
    public NeonAffect.NA_Debug debug;
    private static aos.jack.jak.plan.ExMap[] __exMap_body = {
            new aos.jack.jak.plan.ExMap(28,28,29,__exClass_0),
            new aos.jack.jak.plan.ExMap(10,35,36,__exClass_0),
            new aos.jack.jak.plan.ExMap(10,37,38,null)};
    private static java.lang.String[] __tt__body = {
            "NeonAffect/GetFormulasPlan.plan",
            "body",
            "48",
            "49",
            "51",
            "53",
            "55",
            "58",
            "59",
            "61",
            "63",
            "66",
            "68",
            "68",
            "70",
            "72",
            "73",
            "75",
            "77",
            "79",
            "84",
            "86",
            "88",
            "91",
            "93",
            "96",
            "99",
            "68",
            "103",
            "105",
            "109",
            "108",
            "43"};
    private final static java.lang.String[] __planVariableNames = {
            "bDebug",
            "strPlanWithFormula",
            "gfe",
            "plansFormulas",
            "mutex",
            "debug"};
    private final static java.lang.String[] __planVariableTypes = {
            "boolean",
            "String",
            "NeonAffect.GetFormulasEvent",
            "NeonAffect.PlansWithFormulas",
            "aos.jack.util.thread.Semaphore",
            "NeonAffect.NA_Debug"};
    private final static java.lang.String[] __reasoningMethods = {
            "body"};
    private final static java.lang.String[] __fsmVariableNames_body = {
            "$debug",
            "strModeratorType",
            "planNames",
            "iSize",
            "i",
            "strPlanName",
            "strParameterGroupName",
            "strConfigPlanName",
            "strPlanNameValue",
            "e",
            "e"};
    private final static java.lang.String[] __fsmTypes_body = {
            "logical boolean",
            "String",
            "ArrayList",
            "int",
            "int",
            "String",
            "String",
            "String",
            "String",
            "Exception",
            "Exception"};
    private final static java.lang.String[] __fsmLocalNames_body = {
            "__local__1114_0",
            "__local__1114_1",
            "__local__1114_2",
            "__local__1114_3",
            "__local__1114_4",
            "__local__1114_5",
            "__local__1114_6",
            "__local__1114_7",
            "__local__1114_8",
            "__local__1114_9",
            "__local__1114_10"};
    static boolean relevant(NeonAffect.GetFormulasEvent gfe)
    {
        return true;
    }
    
    public java.lang.String getDocumentation()
    {
        return "/**\n * \n */\n";
    }
    
    public GetFormulasPlan()
    {
    }
    
    private GetFormulasPlan(aos.jack.jak.task.Task __t, NeonAffect.GetFormulasPlan __env)
    {
        __agent = __env.__agent;
        __ns = __env.__ns;
        __planTask = __t;
        __logic = __t.logic;
        gfe = __env.gfe;
        plansFormulas = __env.plansFormulas;
        mutex = __env.mutex;
        debug = __env.debug;
    }
    
    public boolean init_sentinel(aos.jack.jak.agent.NameSpace __a)
    {
        gfe = (NeonAffect.GetFormulasEvent) __a.findEvent("NeonAffect.GetFormulasEvent");
        if (gfe == null) {
            warning("GetFormulasEvent gfe: is not found in the capability/agent this plan comes from");
            return false;
        }
        plansFormulas = (NeonAffect.PlansWithFormulas) lookupNamedObject("plansFormulas","NeonAffect.PlansWithFormulas",0);
        if (plansFormulas == null) {
            warning("PlansWithFormulas plansFormulas: is not found in the capability/agent this plan comes from");
            return false;
        }
        mutex = (aos.jack.util.thread.Semaphore) lookupNamedObject("mutex","aos.jack.util.thread.Semaphore",0);
        if (mutex == null) {
            warning("Semaphore mutex: is not found in the capability/agent this plan comes from");
            return false;
        }
        debug = (NeonAffect.NA_Debug) lookupNamedObject("debug","NeonAffect.NA_Debug",0);
        if (debug == null) {
            warning("NA_Debug debug: is not found in the capability/agent this plan comes from");
            return false;
        }
        return true;
    }
    
    public aos.jack.jak.plan.Plan freeze()
    {
        return this;
    }
    
    public aos.jack.jak.plan.Plan unfreeze()
    {
        return this;
    }
    
    public java.lang.Object genObject(int __index)
    {
        switch (__index) {
        }
        aos.jack.jak.core.Jak.error("illegal Object Construction");
        return null;
    }
    
    public aos.jack.jak.cursor.Cursor genCursor(int __index)
        throws java.lang.Exception
    {
        switch (__index) {
        }
        aos.jack.jak.core.Jak.error("illegal Cursor Construction");
        return null;
    }
    
    public aos.jack.jak.fsm.FSM genFSM(int __index)
        throws java.lang.Exception
    {
        switch (__index) {
        }
        aos.jack.jak.core.Jak.error("illegal FSM Construction");
        return null;
    }
    
    public boolean testCondition(int __index)
        throws java.lang.Exception
    {
        switch (__index) {
        }
        aos.jack.jak.core.Jak.error("illegal test Construction");
        return false;
    }
    
    public aos.jack.jak.plan.PlanFSM body()
    {
        return new NeonAffect.GetFormulasPlan.__bodyFSM();
    }
    
    private GetFormulasPlan(NeonAffect.GetFormulasEvent __ev, aos.jack.jak.task.Task __t, NeonAffect.GetFormulasPlan __env)
    {
        this(__t,__env);
        this.gfe = __ev;
    }
    
    protected aos.jack.jak.logic.Signature eventSignature(int __log)
    {
        return gfe.getSignature(__log);
    }
    
    public java.lang.String handledEvent()
    {
        return "NeonAffect.GetFormulasEvent";
    }
    
    public boolean __relevant(aos.jack.jak.event.Event __e)
    {
        return __ns.isEnabled() && relevant(((NeonAffect.GetFormulasEvent) __e));
    }
    
    public aos.jack.jak.plan.Plan createPlan(aos.jack.jak.event.Event __e, aos.jack.jak.task.Task __t)
    {
        if (!(__e instanceof NeonAffect.GetFormulasEvent)) 
            return null;
        NeonAffect.GetFormulasEvent __e1 = (NeonAffect.GetFormulasEvent) __e;
        return new NeonAffect.GetFormulasPlan(__e1,__t,this);
    }
    
    public java.lang.String[] variableNames()
    {
        return __planVariableNames;
    }
    
    public java.lang.String[] variableTypes()
    {
        return __planVariableTypes;
    }
    
    public java.lang.Object getVariable(int n)
    {
        switch (n) {
            case 0: 
            {
                return aos.util.ToObject.box(bDebug);
            }
            case 1: 
            {
                return aos.util.ToObject.box(strPlanWithFormula);
            }
            case 2: 
            {
                return aos.util.ToObject.box(gfe);
            }
            case 3: 
            {
                return aos.util.ToObject.box(plansFormulas);
            }
            case 4: 
            {
                return aos.util.ToObject.box(mutex);
            }
            case 5: 
            {
                return aos.util.ToObject.box(debug);
            }
            default: 
            {
                throw new java.lang.IndexOutOfBoundsException("Plan " + this + " does not have variable number " + n);
            }
        }
    }
    
    public java.lang.String[] reasoningMethods()
    {
        return mergeReasoningMethods(__reasoningMethods,super.reasoningMethods());
    }
    
    public aos.jack.jak.cursor.Cursor context()
    {
        try {
            return (((true)?aos.jack.jak.cursor.Cursor.trueCursor:aos.jack.jak.cursor.Cursor.falseCursor));
        }
        catch (java.lang.Exception e) {
            e.printStackTrace();
            return aos.jack.jak.cursor.Cursor.falseCursor;
        }
    }
    
    class __bodyFSM extends aos.jack.jak.plan.PlanFSM implements aos.jack.jak.core.Generator {
        aos.jack.jak.logic.BooleanVariable __local__1114_0;
        java.lang.String __local__1114_1;
        java.util.ArrayList __local__1114_2;
        int __local__1114_3;
        int __local__1114_4;
        java.lang.String __local__1114_5;
        java.lang.String __local__1114_6;
        java.lang.String __local__1114_7;
        java.lang.String __local__1114_8;
        java.lang.Exception __local__1114_9;
        java.lang.Exception __local__1114_10;
        private int __breakLevel = 0;
        public int run(int __status)
            throws java.lang.Throwable
        {
            do {
                try {
                    if (__tothrow != null) 
                        throw __tothrow;
                    if ((aos.jack.jak.core.Jak.debugging & aos.jack.jak.core.Jak.LOG_PLANS) != 0) 
                        aos.util.logging.LogMsg.log(this,aos.jack.jak.core.Jak.LOG_PLANS,__task + "-GetFormulasPlan.body:" + java.lang.Integer.toString(__state));
                    if (__task.nsteps > 0) {
                        __task.nsteps-- ;
                        if (__task.nsteps == 0) 
                            agent.changeFocus();
                    }
                    if (__state < 10) {
                        __status = super.stdrun(NeonAffect.GetFormulasPlan.this,__status);
                        if (__status != CONTINUE || agent.changing_focus) 
                            return __status;
                        continue;
                    }
                    __curstate = __state;
                    switch (__state) {
                        default: 
                        {
                            aos.jack.jak.core.Jak.error("GetFormulasPlan.body: Illegal state");
                            return FAILED_STATE;
                        }
                        //* (48)             logical boolean $debug;
                        case 10: 
                        {
                            __breakLevel = 2;
                            __local__1114_0 = (aos.jack.jak.logic.BooleanVariable) __logic.new_variable(java.lang.Boolean.TYPE);
                            __state = 11;
                            break;
                        }
                        //* (49)             debug.get($debug).next();
                        case 11: 
                        {
                            if (debug.get(__local__1114_0).next()) 
                                __state = 12;
                             else 
                                throw planfailed;
                            break;
                        }
                        //* (51)             bDebug = $debug.as_boolean();
                        case 12: 
                        {
                            __state = 13;
                            bDebug = __local__1114_0.as_boolean();
                            break;
                        }
                        //* (53)             if (bDebug)
                        case 13: 
                        {
                            if (bDebug) 
                                __state = 14;
                             else 
                                __state = 15;
                            break;
                        }
                        //* (55)                 System.out.println("Inside GetFormulaPlan:.body.");
                        case 14: 
                        {
                            __breakLevel = 4;
                            __state = 15;
                            java.lang.System.out.println("Inside GetFormulaPlan:.body.");
                            break;
                        }
                        //* (58)             String strModeratorType = gfe.strModeratorType;
                        case 15: 
                        {
                            __local__1114_1 = gfe.strModeratorType;
                            __state = 16;
                            break;
                        }
                        //* (59)             ArrayList planNames = gfe.planNames;
                        case 16: 
                        {
                            __local__1114_2 = gfe.planNames;
                            __state = 17;
                            break;
                        }
                        //* (61)             if (bDebug)
                        case 17: 
                        {
                            if (bDebug) 
                                __state = 18;
                             else 
                                __state = 19;
                            break;
                        }
                        //* (63)                 System.out.println("Inside GetFormulaPlan: Agent name [" + getAgent().getBasename() + "]");
                        case 18: 
                        {
                            __breakLevel = 4;
                            __state = 19;
                            java.lang.System.out.println("Inside GetFormulaPlan: Agent name [" + getAgent().getBasename() + "]");
                            break;
                        }
                        //* (66)             int iSize = planNames.size();
                        case 19: 
                        {
                            __local__1114_3 = __local__1114_2.size();
                            __state = 20;
                            break;
                        }
                        //* (68)             for (int i = 0; i < iSize; i++)
                        case 20: 
                        {
                            __local__1114_4 = 0;
                            __state = 21;
                            break;
                        }
                        //* (68)             for (int i = 0; i < iSize; i++)
                        case 21: 
                        {
                            if (__local__1114_4 < __local__1114_3) 
                                __state = 22;
                             else 
                                __state = 38;
                            break;
                        }
                        //* (70)                 String strPlanName = (String)planNames.get(i);
                        case 22: 
                        {
                            __breakLevel = 6;
                            __local__1114_5 = (java.lang.String) __local__1114_2.get(__local__1114_4);
                            __state = 23;
                            break;
                        }
                        //* (72)                 String strParameterGroupName = "Neon" + strModeratorType;
                        case 23: 
                        {
                            __local__1114_6 = "Neon" + __local__1114_1;
                            __state = 24;
                            break;
                        }
                        //* (73)                 String strConfigPlanName = strPlanName.replace("NeonAffect.", "");
                        case 24: 
                        {
                            __local__1114_7 = __local__1114_5.replace("NeonAffect.","");
                            __state = 25;
                            break;
                        }
                        //* (75)                 String strPlanNameValue = "0"; 
                        case 25: 
                        {
                            __local__1114_8 = "0";
                            __state = 26;
                            break;
                        }
                        //* (77)                 if (bDebug)
                        case 26: 
                        {
                            if (bDebug) 
                                __state = 27;
                             else 
                                __state = 28;
                            break;
                        }
                        //* (79)                     System.out.println("Inside GetFormulaPlan: before call to GetPlanNameValue: strParameterGroupName: [" + strParameterGroupName + "] PlanName: [" + strConfigPlanName + "]");
                        case 27: 
                        {
                            __breakLevel = 8;
                            __state = 28;
                            java.lang.System.out.println("Inside GetFormulaPlan: before call to GetPlanNameValue: strParameterGroupName: [" + __local__1114_6 + "] PlanName: [" + __local__1114_7 + "]");
                            break;
                        }
                        //* (84)                     strPlanNameValue = new parser(Constants.COJACK_COGNITIVE_PATH).GetPlanNameValue(strParameterGroupName, strConfigPlanName);
                        case 28: 
                        {
                            __breakLevel = 8;
                            __state = 31;
                            __local__1114_8 = new CoJACKConfigParserXML.parser(NeonAffect.Constants.COJACK_COGNITIVE_PATH).GetPlanNameValue(__local__1114_6,__local__1114_7);
                            break;
                        }
                        //* (86)                 catch (Exception e)
                        case 29: 
                        {
                            __breakLevel = 8;
                            __state = 30;
                            __local__1114_9 = (java.lang.Exception) __current;
                            break;
                        }
                        //* (88)                     e.printStackTrace();   
                        case 30: 
                        {
                            __breakLevel = 10;
                            __state = 31;
                            __local__1114_9.printStackTrace();
                            break;
                        }
                        //* (91)                 if (bDebug)
                        case 31: 
                        {
                            if (bDebug) 
                                __state = 32;
                             else 
                                __state = 33;
                            break;
                        }
                        //* (93)                     System.out.println("Inside GetFormulaPlan: after call to getFormula: PlanName: [" + strPlanName + "] strPlanNameValue [" + strPlanNameValue + "]");
                        case 32: 
                        {
                            __breakLevel = 8;
                            __state = 33;
                            java.lang.System.out.println("Inside GetFormulaPlan: after call to getFormula: PlanName: [" + __local__1114_5 + "] strPlanNameValue [" + __local__1114_8 + "]");
                            break;
                        }
                        //* (96)                 if (!strPlanNameValue.equals("0"))
                        case 33: 
                        {
                            if (!__local__1114_8.equals("0")) 
                                __state = 34;
                             else 
                                __state = 35;
                            break;
                        }
                        //* (99)                     plansFormulas.add(plansFormulas.nFacts(),  strPlanName);
                        case 34: 
                        {
                            __breakLevel = 8;
                            __state = 35;
                            //add to list

                            plansFormulas.add(plansFormulas.nFacts(),__local__1114_5);
                            break;
                        }
                        //* (68)             for (int i = 0; i < iSize; i++)
                        case 35: 
                        {
                            __state = 21;
                            __local__1114_4++ ;
                            break;
                        }
                        //* (103)         catch (Exception e)
                        case 36: 
                        {
                            __breakLevel = 2;
                            __state = 37;
                            __local__1114_10 = (java.lang.Exception) __current;
                            break;
                        }
                        //* (105)             e.printStackTrace();                
                        case 37: 
                        {
                            __breakLevel = 4;
                            __state = 38;
                            __local__1114_10.printStackTrace();
                            break;
                        }
                        //* (109)             mutex.signal();   
                        case 38: 
                        {
                            __breakLevel = 2;
                            __state = 39;
                            mutex.signal();
                            break;
                        }
                        //* (108)         {
                        case 39: 
                        {
                            __state = 40;
                            if (__breakLevel < 2) 
                                __state = 40;
                            __tothrow = __pending;
                            break;
                        }
                        //* (43)     #reasoning method
                        case 40: 
                        {
                            if (__pending == null) 
                                __state = PASSED_STATE;
                            __tothrow = __pending;
                            break;
                        }
                    }
                }
                catch (java.lang.Throwable e) {
                    handleException(e,__exMap_body);
                }
            }
             while (!agent.changing_focus);
            return CONTINUE;
        }
        
        public java.lang.String methodName()
        {
            return "body";
        }
        
        __bodyFSM()
        {
        }
        
        public java.lang.String stateInfo()
        {
            int n = __curstate;
            java.lang.String file = __tt__body[0];
            java.lang.String method = __tt__body[1];
            if (n < 0) 
                n = -n;
            n -= (10 - 2);
            java.lang.String line = (n < 2)?"??":__tt__body[n];
            return file + ":" + line + " " + method + " [" + __curstate + "]";
        }
        
        public java.lang.Object genObject(int __index)
        {
            switch (__index) {
            }
            aos.jack.jak.core.Jak.error("illegal Object Construction");
            return null;
        }
        
        public aos.jack.jak.cursor.Cursor genCursor(int __index)
            throws java.lang.Exception
        {
            switch (__index) {
            }
            aos.jack.jak.core.Jak.error("illegal Cursor Construction");
            return null;
        }
        
        public aos.jack.jak.fsm.FSM genFSM(int __index)
            throws java.lang.Exception
        {
            switch (__index) {
            }
            aos.jack.jak.core.Jak.error("illegal FSM Construction");
            return null;
        }
        
        public boolean testCondition(int __index)
            throws java.lang.Exception
        {
            switch (__index) {
            }
            aos.jack.jak.core.Jak.error("illegal test Construction");
            return false;
        }
        
        public aos.jack.jak.plan.Plan getPlan()
        {
            return NeonAffect.GetFormulasPlan.this;
        }
        
        protected aos.jack.jak.fsm.FSM fail()
        {
            return getPlan().fail();
        }
        
        protected aos.jack.jak.fsm.FSM pass()
        {
            return getPlan().pass();
        }
        
        public void enter()
        {
            __trace = agent.trace("NeonAffect.GetFormulasPlan.body");
        }
        
        public java.lang.Object getVariable(int n)
        {
            switch (n) {
                case 0: 
                {
                    return aos.util.ToObject.box(__local__1114_0);
                }
                case 1: 
                {
                    return aos.util.ToObject.box(__local__1114_1);
                }
                case 2: 
                {
                    return aos.util.ToObject.box(__local__1114_2);
                }
                case 3: 
                {
                    return aos.util.ToObject.box(__local__1114_3);
                }
                case 4: 
                {
                    return aos.util.ToObject.box(__local__1114_4);
                }
                case 5: 
                {
                    return aos.util.ToObject.box(__local__1114_5);
                }
                case 6: 
                {
                    return aos.util.ToObject.box(__local__1114_6);
                }
                case 7: 
                {
                    return aos.util.ToObject.box(__local__1114_7);
                }
                case 8: 
                {
                    return aos.util.ToObject.box(__local__1114_8);
                }
                case 9: 
                {
                    return aos.util.ToObject.box(__local__1114_9);
                }
                case 10: 
                {
                    return aos.util.ToObject.box(__local__1114_10);
                }
                default: 
                {
                    throw new java.lang.IndexOutOfBoundsException("Reasoning Method " + methodName() + " does not have variable number " + n);
                }
            }
        }
        
        public java.lang.String[] variableNames()
        {
            return __fsmVariableNames_body;
        }
        
        public java.lang.String[] variableTypes()
        {
            return __fsmTypes_body;
        }
        
        public java.lang.String[] variableLocalNames()
        {
            return __fsmLocalNames_body;
        }
        
    }
}
