/*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*
  This code is generated by JAC version 5.6 by
  Agent Oriented Software. http://www.agent-software.com.au

    DO NOT ALTER THIS CODE AND DO NOT REMOVE THIS COMMENT
 *=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*/
package NeonAffect;
import aos.jack.jak.event.Event;

/**
 * 
 */

public class AddAppraisalCriteriaEvent extends aos.jack.jak.event.Event {
    public java.lang.String strPersonalityType = "";
    private final static java.lang.String[] __eventVariableNames = {
            "strPersonalityType"};
    private final static java.lang.String[] __eventVariableTypes = {
            "String"};
    public java.lang.String getDocumentation()
    {
        return "/**\n * \n */\n";
    }
    
    public NeonAffect.AddAppraisalCriteriaEvent post(java.lang.String strPersonalityType1)
    {
        NeonAffect.AddAppraisalCriteriaEvent tmp = new NeonAffect.AddAppraisalCriteriaEvent();
        tmp.init(this);
        return tmp.post_body(strPersonalityType1);
    }
    
    private NeonAffect.AddAppraisalCriteriaEvent post_body(java.lang.String strPersonalityType1)
    {
        strPersonalityType = strPersonalityType1;
        return this;
    }
    
    public AddAppraisalCriteriaEvent()
    {
    }
    
    public java.lang.String stateInfo()
    {
        return "NeonAffect/AddAppraisalCriteriaEvent.event [" + super.stateInfo() + "]";
    }
    
    public java.lang.String[] variableNames()
    {
        return __eventVariableNames;
    }
    
    public java.lang.String[] variableTypes()
    {
        return __eventVariableTypes;
    }
    
    public java.lang.Object getVariable(int n)
    {
        switch (n) {
            case 0: 
            {
                return aos.util.ToObject.box(strPersonalityType);
            }
            default: 
            {
                throw new java.lang.IndexOutOfBoundsException("Event " + this + " does not have variable number " + n);
            }
        }
    }
    
}
