/*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*
  This code is generated by JAC version 5.6 by
  Agent Oriented Software. http://www.agent-software.com.au

    DO NOT ALTER THIS CODE AND DO NOT REMOVE THIS COMMENT
 *=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*/
package NeonAffect;
import aos.jack.jak.agent.Capability;
import aos.jack.jak.agent.NameSpace;
import aos.jack.jak.agent.Agent;
import aos.jack.util.thread.Semaphore;

/**
 * 
 */

public class FreeAffectCapability extends aos.jack.jak.agent.Capability {
    public NeonAffect.PlanContextName planContextName;
    public NeonAffect.Behavior behaviorName;
    public aos.jack.util.thread.Semaphore mutex;
    public aos.jack.util.thread.Semaphore mutex2;
    public NeonAffect.NA_Debug debug;
    public NeonAffect.ContextEvent ce;
    public java.lang.String getDocumentation()
    {
        return "/**\n * \n */\n";
    }
    
    public void __init1()
    {
        setNamedCreator("planContextName","NeonAffect.PlanContextName",new aos.jack.jak.agent.DataCreator(false){
            public java.lang.Object create()
            {
                return __named_data_planContextName();
            }
            
        },true);
        setNamedCreator("behaviorName","NeonAffect.Behavior",new aos.jack.jak.agent.DataCreator(false){
            public java.lang.Object create()
            {
                return __named_data_behaviorName();
            }
            
        },true);
        setNamedCreator("mutex","aos.jack.util.thread.Semaphore",new aos.jack.jak.agent.DataCreator(false){
            public java.lang.Object create()
            {
                return __named_data_mutex();
            }
            
        },true);
        setNamedCreator("mutex2","aos.jack.util.thread.Semaphore",new aos.jack.jak.agent.DataCreator(false){
            public java.lang.Object create()
            {
                return __named_data_mutex2();
            }
            
        },true);
        setNamedCreator("debug","NeonAffect.NA_Debug",new aos.jack.jak.agent.DataCreator(false){
            public java.lang.Object create()
            {
                return __named_data_debug();
            }
            
        },true);
    }
    
    public void __init2()
    {
        ce = (NeonAffect.ContextEvent) findEvent("NeonAffect.ContextEvent");
        planContextName = (NeonAffect.PlanContextName) getNamedObject("planContextName","NeonAffect.PlanContextName");
        behaviorName = (NeonAffect.Behavior) getNamedObject("behaviorName","NeonAffect.Behavior");
        mutex = (aos.jack.util.thread.Semaphore) getNamedObject("mutex","aos.jack.util.thread.Semaphore");
        mutex2 = (aos.jack.util.thread.Semaphore) getNamedObject("mutex2","aos.jack.util.thread.Semaphore");
        debug = (NeonAffect.NA_Debug) getNamedObject("debug","NeonAffect.NA_Debug");
        autorun();
    }
    
    synchronized public void __init_desc()
    {
        externals.put("debug","debug");
        externals.put("mutex2","mutex2");
        externals.put("mutex","mutex");
        externals.put("behaviorName","behaviorName");
        externals.put("planContextName","planContextName");
        externals.put("NeonAffect.SetPlanContextEvent","NeonAffect.SetPlanContextEvent");
        externals.put("NeonAffect.Level5PosAffectEvent","NeonAffect.Level5PosAffectEvent");
        addEvent("NeonAffect.Level5PosAffectEvent",aos.jack.jak.agent.Agent.HANDLED_EVENT);
        addEvent("NeonAffect.SetPlanContextEvent",aos.jack.jak.agent.Agent.HANDLED_EVENT);
        addEvent("NeonAffect.ContextEvent",aos.jack.jak.agent.Agent.SENT_EVENT);
        addPlan("NeonAffect.BreakingRoutinesPlan",0);
        addPlan("NeonAffect.CelebratingIndividualityPlan",0);
        addPlan("NeonAffect.CreativityFreePlan",0);
        addPlan("NeonAffect.DeepBreathsFreePlan",0);
        addPlan("NeonAffect.EmbracingSpontaneityFreePlan",0);
        addPlan("NeonAffect.EngagingPhilosophicalDiscussionsPlan",0);
        addPlan("NeonAffect.ExpressingUnconventionalIdeasPlan",0);
        addPlan("NeonAffect.EyeContactFreePlan",0);
        addPlan("NeonAffect.FacialExpressionsFreePlan",0);
        addPlan("NeonAffect.FluidMovementFreePlan",0);
        addPlan("NeonAffect.FollowingImpulsesPlan",0);
        addPlan("NeonAffect.ImprovisedSpeechPlan",0);
        addPlan("NeonAffect.LaughingFreePlan",0);
        addPlan("NeonAffect.OpenBodyLanguageFreePlan",0);
        addPlan("NeonAffect.RejectingObligationsFreePlan",0);
        addPlan("NeonAffect.SeekingNewOpportunitiesFreePlan",0);
        addPlan("NeonAffect.SharingInformationFreePlan",0);
        addPlan("NeonAffect.SmilingFreePlan",0);
        addPlan("NeonAffect.SpeakingUninhibitedlyPlan",0);
        addPlan("NeonAffect.UsingSpontaneousWordplayPlan",0);
        addPlan("NeonAffect.VocalizingEmotionsOpenlyPlan",0);
        addPlan("NeonAffect.SetPlanContextFreePlan",0);
    }
    
    public FreeAffectCapability(aos.jack.jak.agent.NameSpace outer)
    {
        super(outer);
    }
    
    synchronized public void __bindNames()
    {
        super.__bindNames();
        __bindToPlan("NeonAffect.BreakingRoutinesPlan");
        __bindToPlan("NeonAffect.CelebratingIndividualityPlan");
        __bindToPlan("NeonAffect.CreativityFreePlan");
        __bindToPlan("NeonAffect.DeepBreathsFreePlan");
        __bindToPlan("NeonAffect.EmbracingSpontaneityFreePlan");
        __bindToPlan("NeonAffect.EngagingPhilosophicalDiscussionsPlan");
        __bindToPlan("NeonAffect.ExpressingUnconventionalIdeasPlan");
        __bindToPlan("NeonAffect.EyeContactFreePlan");
        __bindToPlan("NeonAffect.FacialExpressionsFreePlan");
        __bindToPlan("NeonAffect.FluidMovementFreePlan");
        __bindToPlan("NeonAffect.FollowingImpulsesPlan");
        __bindToPlan("NeonAffect.ImprovisedSpeechPlan");
        __bindToPlan("NeonAffect.LaughingFreePlan");
        __bindToPlan("NeonAffect.OpenBodyLanguageFreePlan");
        __bindToPlan("NeonAffect.RejectingObligationsFreePlan");
        __bindToPlan("NeonAffect.SeekingNewOpportunitiesFreePlan");
        __bindToPlan("NeonAffect.SharingInformationFreePlan");
        __bindToPlan("NeonAffect.SmilingFreePlan");
        __bindToPlan("NeonAffect.SpeakingUninhibitedlyPlan");
        __bindToPlan("NeonAffect.UsingSpontaneousWordplayPlan");
        __bindToPlan("NeonAffect.VocalizingEmotionsOpenlyPlan");
        __bindToPlan("NeonAffect.SetPlanContextFreePlan");
    }
    
    private NeonAffect.PlanContextName __named_data_planContextName()
    {
        planContextName = (NeonAffect.PlanContextName) getNamedObject("planContextName","NeonAffect.PlanContextName");
        return planContextName;
    }
    
    private NeonAffect.Behavior __named_data_behaviorName()
    {
        behaviorName = (NeonAffect.Behavior) getNamedObject("behaviorName","NeonAffect.Behavior");
        return behaviorName;
    }
    
    private aos.jack.util.thread.Semaphore __named_data_mutex()
    {
        mutex = (aos.jack.util.thread.Semaphore) getNamedObject("mutex","aos.jack.util.thread.Semaphore");
        return mutex;
    }
    
    private aos.jack.util.thread.Semaphore __named_data_mutex2()
    {
        mutex2 = (aos.jack.util.thread.Semaphore) getNamedObject("mutex2","aos.jack.util.thread.Semaphore");
        return mutex2;
    }
    
    private NeonAffect.NA_Debug __named_data_debug()
    {
        debug = (NeonAffect.NA_Debug) getNamedObject("debug","NeonAffect.NA_Debug");
        return debug;
    }
    
}
