/*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*
  This code is generated by JAC version 5.6 by
  Agent Oriented Software. http://www.agent-software.com.au

    DO NOT ALTER THIS CODE AND DO NOT REMOVE THIS COMMENT
 *=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*/
package NeonAffect;
import aos.jack.jak.agent.Capability;
import aos.jack.jak.agent.NameSpace;
import aos.jack.jak.agent.Agent;
import aos.jack.util.thread.Semaphore;

/**
 * 
 */

public class MeekAffectCapability extends aos.jack.jak.agent.Capability {
    public NeonAffect.PlanContextName planContextName;
    public NeonAffect.Behavior behaviorName;
    public aos.jack.util.thread.Semaphore mutex;
    public aos.jack.util.thread.Semaphore mutex2;
    public NeonAffect.NA_Debug debug;
    public NeonAffect.ContextEvent ce;
    public java.lang.String getDocumentation()
    {
        return "/**\n * \n */\n";
    }
    
    public void __init1()
    {
        setNamedCreator("planContextName","NeonAffect.PlanContextName",new aos.jack.jak.agent.DataCreator(false){
            public java.lang.Object create()
            {
                return __named_data_planContextName();
            }
            
        },true);
        setNamedCreator("behaviorName","NeonAffect.Behavior",new aos.jack.jak.agent.DataCreator(false){
            public java.lang.Object create()
            {
                return __named_data_behaviorName();
            }
            
        },true);
        setNamedCreator("mutex","aos.jack.util.thread.Semaphore",new aos.jack.jak.agent.DataCreator(false){
            public java.lang.Object create()
            {
                return __named_data_mutex();
            }
            
        },true);
        setNamedCreator("mutex2","aos.jack.util.thread.Semaphore",new aos.jack.jak.agent.DataCreator(false){
            public java.lang.Object create()
            {
                return __named_data_mutex2();
            }
            
        },true);
        setNamedCreator("debug","NeonAffect.NA_Debug",new aos.jack.jak.agent.DataCreator(false){
            public java.lang.Object create()
            {
                return __named_data_debug();
            }
            
        },true);
    }
    
    public void __init2()
    {
        ce = (NeonAffect.ContextEvent) findEvent("NeonAffect.ContextEvent");
        planContextName = (NeonAffect.PlanContextName) getNamedObject("planContextName","NeonAffect.PlanContextName");
        behaviorName = (NeonAffect.Behavior) getNamedObject("behaviorName","NeonAffect.Behavior");
        mutex = (aos.jack.util.thread.Semaphore) getNamedObject("mutex","aos.jack.util.thread.Semaphore");
        mutex2 = (aos.jack.util.thread.Semaphore) getNamedObject("mutex2","aos.jack.util.thread.Semaphore");
        debug = (NeonAffect.NA_Debug) getNamedObject("debug","NeonAffect.NA_Debug");
        autorun();
    }
    
    synchronized public void __init_desc()
    {
        externals.put("debug","debug");
        externals.put("mutex2","mutex2");
        externals.put("mutex","mutex");
        externals.put("behaviorName","behaviorName");
        externals.put("planContextName","planContextName");
        externals.put("NeonAffect.SetPlanContextEvent","NeonAffect.SetPlanContextEvent");
        externals.put("NeonAffect.Level2NegAffectEvent","NeonAffect.Level2NegAffectEvent");
        addEvent("NeonAffect.Level2NegAffectEvent",aos.jack.jak.agent.Agent.HANDLED_EVENT);
        addEvent("NeonAffect.SetPlanContextEvent",aos.jack.jak.agent.Agent.HANDLED_EVENT);
        addEvent("NeonAffect.ContextEvent",aos.jack.jak.agent.Agent.SENT_EVENT);
        addPlan("NeonAffect.AgreeingQuicklyPlan",0);
        addPlan("NeonAffect.ApologizingMeekPlan",0);
        addPlan("NeonAffect.AvoidingConflictMeekPlan",0);
        addPlan("NeonAffect.AvoidingConfrontationsMeekPlan",0);
        addPlan("NeonAffect.AvoidingEyeContactMeekPlan",0);
        addPlan("NeonAffect.AvoidingLeadershipPlan",0);
        addPlan("NeonAffect.BadPostureMeekPlan",0);
        addPlan("NeonAffect.BlushingFaceMeekPlan",0);
        addPlan("NeonAffect.DeferringToOthersOpinionsPlan",0);
        addPlan("NeonAffect.DifficultySettingBoundariesPlan",0);
        addPlan("NeonAffect.DownplayingOwnEmotionsPlan",0);
        addPlan("NeonAffect.HesitateToAskHelpMeekPlan",0);
        addPlan("NeonAffect.HesitatingToTakeInitiativeMeekPlan",0);
        addPlan("NeonAffect.HesitationSpeechMeekPlan",0);
        addPlan("NeonAffect.LoweringHeadMeekPlan",0);
        addPlan("NeonAffect.MinimizingOwnAchievementsPlan",0);
        addPlan("NeonAffect.PuttingOthersNeedsFirstPlan",0);
        addPlan("NeonAffect.SecondGuessingMeekPlan",0);
        addPlan("NeonAffect.SeekingApprovalMeekPlan",0);
        addPlan("NeonAffect.SelfDeprecatingRemarksMeekPlan",0);
        addPlan("NeonAffect.SmilingMeekPlan",0);
        addPlan("NeonAffect.SpeakSoflyMeekPlan",0);
        addPlan("NeonAffect.UsingQualifiersMeekPlan",0);
        addPlan("NeonAffect.SetPlanContextMeekPlan",0);
    }
    
    public MeekAffectCapability(aos.jack.jak.agent.NameSpace outer)
    {
        super(outer);
    }
    
    synchronized public void __bindNames()
    {
        super.__bindNames();
        __bindToPlan("NeonAffect.AgreeingQuicklyPlan");
        __bindToPlan("NeonAffect.ApologizingMeekPlan");
        __bindToPlan("NeonAffect.AvoidingConflictMeekPlan");
        __bindToPlan("NeonAffect.AvoidingConfrontationsMeekPlan");
        __bindToPlan("NeonAffect.AvoidingEyeContactMeekPlan");
        __bindToPlan("NeonAffect.AvoidingLeadershipPlan");
        __bindToPlan("NeonAffect.BadPostureMeekPlan");
        __bindToPlan("NeonAffect.BlushingFaceMeekPlan");
        __bindToPlan("NeonAffect.DeferringToOthersOpinionsPlan");
        __bindToPlan("NeonAffect.DifficultySettingBoundariesPlan");
        __bindToPlan("NeonAffect.DownplayingOwnEmotionsPlan");
        __bindToPlan("NeonAffect.HesitateToAskHelpMeekPlan");
        __bindToPlan("NeonAffect.HesitatingToTakeInitiativeMeekPlan");
        __bindToPlan("NeonAffect.HesitationSpeechMeekPlan");
        __bindToPlan("NeonAffect.LoweringHeadMeekPlan");
        __bindToPlan("NeonAffect.MinimizingOwnAchievementsPlan");
        __bindToPlan("NeonAffect.PuttingOthersNeedsFirstPlan");
        __bindToPlan("NeonAffect.SecondGuessingMeekPlan");
        __bindToPlan("NeonAffect.SeekingApprovalMeekPlan");
        __bindToPlan("NeonAffect.SelfDeprecatingRemarksMeekPlan");
        __bindToPlan("NeonAffect.SmilingMeekPlan");
        __bindToPlan("NeonAffect.SpeakSoflyMeekPlan");
        __bindToPlan("NeonAffect.UsingQualifiersMeekPlan");
        __bindToPlan("NeonAffect.SetPlanContextMeekPlan");
    }
    
    private NeonAffect.PlanContextName __named_data_planContextName()
    {
        planContextName = (NeonAffect.PlanContextName) getNamedObject("planContextName","NeonAffect.PlanContextName");
        return planContextName;
    }
    
    private NeonAffect.Behavior __named_data_behaviorName()
    {
        behaviorName = (NeonAffect.Behavior) getNamedObject("behaviorName","NeonAffect.Behavior");
        return behaviorName;
    }
    
    private aos.jack.util.thread.Semaphore __named_data_mutex()
    {
        mutex = (aos.jack.util.thread.Semaphore) getNamedObject("mutex","aos.jack.util.thread.Semaphore");
        return mutex;
    }
    
    private aos.jack.util.thread.Semaphore __named_data_mutex2()
    {
        mutex2 = (aos.jack.util.thread.Semaphore) getNamedObject("mutex2","aos.jack.util.thread.Semaphore");
        return mutex2;
    }
    
    private NeonAffect.NA_Debug __named_data_debug()
    {
        debug = (NeonAffect.NA_Debug) getNamedObject("debug","NeonAffect.NA_Debug");
        return debug;
    }
    
}
