/*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*
  This code is generated by JAC version 5.6 by
  Agent Oriented Software. http://www.agent-software.com.au

    DO NOT ALTER THIS CODE AND DO NOT REMOVE THIS COMMENT
 *=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*/
package NeonAffect;
import aos.jack.jak.agent.Agent;

/**
 * 
 */

public class NeonExcitedAgent extends NeonAffect.AbstractMiniAgent implements NeonAffect.IPost {
    private boolean bDebug = false;
    public NeonAffect.ExcitedAffectCapability cap1;
    private NeonAffect.Level4PosAffectEvent ev1;
    public NeonExcitedAgent(java.lang.String strName, java.lang.String strInteractionType1, boolean bDebug1)
    {
        super(strName,strInteractionType1,NeonAffect.AffectEnum.EXCITED,bDebug1);
        boolean __b = getAgentType() == NeonAffect.NeonExcitedAgent.class;
        if (__b) {
            __init1();
            __init2();
        }
        bDebug = bDebug1;
        if (__b) 
            startAgent();
    }
    
    public void PostEvent()
    {
        try {
            //call level plan            

            postEvent(ev1.post(GetAffectType()));
            mutex.threadWait();
        }
        catch (java.lang.Exception e) {
            e.printStackTrace();
        }
    }
    
    public java.lang.String getDocumentation()
    {
        return "/**\n * \n */\n";
    }
    
    public java.lang.Class getAgentType()
    {
        return NeonAffect.NeonExcitedAgent.class;
    }
    
    public void __init1()
    {
        super.__init1();
        if (cap1 == null) {
            cap1 = new NeonAffect.ExcitedAffectCapability(this);
            cap1.__initCapability(this,"cap1");
        }
        cap1.__init1();
    }
    
    public void __init2()
    {
        super.__init2();
        cap1.__init2();
        ev1 = (NeonAffect.Level4PosAffectEvent) findEvent("NeonAffect.Level4PosAffectEvent");
    }
    
    synchronized private void __init_desc()
    {
        cap1 = new NeonAffect.ExcitedAffectCapability(this);
        cap1.__initCapability(this,"cap1");
        cap1.init_desc();
        addEvent("NeonAffect.Level4PosAffectEvent",aos.jack.jak.agent.Agent.HANDLED_EVENT);
        addEvent("NeonAffect.Level4PosAffectEvent",aos.jack.jak.agent.Agent.POSTED_EVENT);
    }
    
    public void init_desc()
    {
        newAgentDesc("NeonExcitedAgent");
        super.init_desc();
        __init_desc();
    }
    
    synchronized public void __bindNames()
    {
        super.__bindNames();
        cap1.__bindNames();
    }
    
    public void setEnabled(boolean t)
    {
        super.setEnabled(t);
        cap1.setEnabled(t);
    }
    
}
