/*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*
  This code is generated by JAC version 5.6 by
  Agent Oriented Software. http://www.agent-software.com.au

    DO NOT ALTER THIS CODE AND DO NOT REMOVE THIS COMMENT
 *=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*/
package NeonAffect;
import aos.jack.jak.agent.Capability;
import aos.jack.jak.agent.NameSpace;
import aos.jack.jak.agent.Agent;
import aos.jack.util.thread.Semaphore;

/**
 * 
 */

public class JoyfulAffectCapability extends aos.jack.jak.agent.Capability {
    public NeonAffect.PlanContextName planContextName;
    public NeonAffect.Behavior behaviorName;
    public aos.jack.util.thread.Semaphore mutex;
    public aos.jack.util.thread.Semaphore mutex2;
    public NeonAffect.NA_Debug debug;
    public NeonAffect.ContextEvent ce;
    public java.lang.String getDocumentation()
    {
        return "/**\n * \n */\n";
    }
    
    public void __init1()
    {
        setNamedCreator("planContextName","NeonAffect.PlanContextName",new aos.jack.jak.agent.DataCreator(false){
            public java.lang.Object create()
            {
                return __named_data_planContextName();
            }
            
        },true);
        setNamedCreator("behaviorName","NeonAffect.Behavior",new aos.jack.jak.agent.DataCreator(false){
            public java.lang.Object create()
            {
                return __named_data_behaviorName();
            }
            
        },true);
        setNamedCreator("mutex","aos.jack.util.thread.Semaphore",new aos.jack.jak.agent.DataCreator(false){
            public java.lang.Object create()
            {
                return __named_data_mutex();
            }
            
        },true);
        setNamedCreator("mutex2","aos.jack.util.thread.Semaphore",new aos.jack.jak.agent.DataCreator(false){
            public java.lang.Object create()
            {
                return __named_data_mutex2();
            }
            
        },true);
        setNamedCreator("debug","NeonAffect.NA_Debug",new aos.jack.jak.agent.DataCreator(false){
            public java.lang.Object create()
            {
                return __named_data_debug();
            }
            
        },true);
    }
    
    public void __init2()
    {
        ce = (NeonAffect.ContextEvent) findEvent("NeonAffect.ContextEvent");
        planContextName = (NeonAffect.PlanContextName) getNamedObject("planContextName","NeonAffect.PlanContextName");
        behaviorName = (NeonAffect.Behavior) getNamedObject("behaviorName","NeonAffect.Behavior");
        mutex = (aos.jack.util.thread.Semaphore) getNamedObject("mutex","aos.jack.util.thread.Semaphore");
        mutex2 = (aos.jack.util.thread.Semaphore) getNamedObject("mutex2","aos.jack.util.thread.Semaphore");
        debug = (NeonAffect.NA_Debug) getNamedObject("debug","NeonAffect.NA_Debug");
        autorun();
    }
    
    synchronized public void __init_desc()
    {
        externals.put("debug","debug");
        externals.put("mutex2","mutex2");
        externals.put("mutex","mutex");
        externals.put("behaviorName","behaviorName");
        externals.put("planContextName","planContextName");
        externals.put("NeonAffect.SetPlanContextEvent","NeonAffect.SetPlanContextEvent");
        externals.put("NeonAffect.Level3PosAffectEvent","NeonAffect.Level3PosAffectEvent");
        addEvent("NeonAffect.Level3PosAffectEvent",aos.jack.jak.agent.Agent.HANDLED_EVENT);
        addEvent("NeonAffect.SetPlanContextEvent",aos.jack.jak.agent.Agent.HANDLED_EVENT);
        addEvent("NeonAffect.ContextEvent",aos.jack.jak.agent.Agent.SENT_EVENT);
        addPlan("NeonAffect.ComplementOthersPlan",0);
        addPlan("NeonAffect.CreativityJoyfulPlan",0);
        addPlan("NeonAffect.DesireToSpreadHappinessPlan",0);
        addPlan("NeonAffect.EnergenicActivityPlan",0);
        addPlan("NeonAffect.ExcitedChatterPlan",0);
        addPlan("NeonAffect.ExpressingGratitudeJoyfulPlan",0);
        addPlan("NeonAffect.EyesWideOpenJoyfulPlan",0);
        addPlan("NeonAffect.GigglingPlan",0);
        addPlan("NeonAffect.IncreasedProductivityPlan",0);
        addPlan("NeonAffect.LaughingJoyfulPlan",0);
        addPlan("NeonAffect.NodHeadFastJoyfulPlan",0);
        addPlan("NeonAffect.NoticePositiveThingsPlan",0);
        addPlan("NeonAffect.OpenBodyPostureJoyFulPlan",0);
        addPlan("NeonAffect.OptimisticJoyfulPlan",0);
        addPlan("NeonAffect.ProblemSolvingJoyfulPlan",0);
        addPlan("NeonAffect.SeekingOutOthersPlan",0);
        addPlan("NeonAffect.SharingGoodNewsPlan",0);
        addPlan("NeonAffect.SingingHummingJoyfulPlan",0);
        addPlan("NeonAffect.SmilingJoyfulPlan",0);
        addPlan("NeonAffect.SpeakingWithLiltingTonePlan",0);
        addPlan("NeonAffect.TellingJokesJoyfulPlan",0);
        addPlan("NeonAffect.ThumbsUpJoyfulPlan",0);
        addPlan("NeonAffect.UsingPositiveWordsPlan",0);
        addPlan("NeonAffect.WillingnessToHelpJoyfulPlan",0);
        addPlan("NeonAffect.SetPlanContextJoyfulPlan",0);
    }
    
    public JoyfulAffectCapability(aos.jack.jak.agent.NameSpace outer)
    {
        super(outer);
    }
    
    synchronized public void __bindNames()
    {
        super.__bindNames();
        __bindToPlan("NeonAffect.ComplementOthersPlan");
        __bindToPlan("NeonAffect.CreativityJoyfulPlan");
        __bindToPlan("NeonAffect.DesireToSpreadHappinessPlan");
        __bindToPlan("NeonAffect.EnergenicActivityPlan");
        __bindToPlan("NeonAffect.ExcitedChatterPlan");
        __bindToPlan("NeonAffect.ExpressingGratitudeJoyfulPlan");
        __bindToPlan("NeonAffect.EyesWideOpenJoyfulPlan");
        __bindToPlan("NeonAffect.GigglingPlan");
        __bindToPlan("NeonAffect.IncreasedProductivityPlan");
        __bindToPlan("NeonAffect.LaughingJoyfulPlan");
        __bindToPlan("NeonAffect.NodHeadFastJoyfulPlan");
        __bindToPlan("NeonAffect.NoticePositiveThingsPlan");
        __bindToPlan("NeonAffect.OpenBodyPostureJoyFulPlan");
        __bindToPlan("NeonAffect.OptimisticJoyfulPlan");
        __bindToPlan("NeonAffect.ProblemSolvingJoyfulPlan");
        __bindToPlan("NeonAffect.SeekingOutOthersPlan");
        __bindToPlan("NeonAffect.SharingGoodNewsPlan");
        __bindToPlan("NeonAffect.SingingHummingJoyfulPlan");
        __bindToPlan("NeonAffect.SmilingJoyfulPlan");
        __bindToPlan("NeonAffect.SpeakingWithLiltingTonePlan");
        __bindToPlan("NeonAffect.TellingJokesJoyfulPlan");
        __bindToPlan("NeonAffect.ThumbsUpJoyfulPlan");
        __bindToPlan("NeonAffect.UsingPositiveWordsPlan");
        __bindToPlan("NeonAffect.WillingnessToHelpJoyfulPlan");
        __bindToPlan("NeonAffect.SetPlanContextJoyfulPlan");
    }
    
    private NeonAffect.PlanContextName __named_data_planContextName()
    {
        planContextName = (NeonAffect.PlanContextName) getNamedObject("planContextName","NeonAffect.PlanContextName");
        return planContextName;
    }
    
    private NeonAffect.Behavior __named_data_behaviorName()
    {
        behaviorName = (NeonAffect.Behavior) getNamedObject("behaviorName","NeonAffect.Behavior");
        return behaviorName;
    }
    
    private aos.jack.util.thread.Semaphore __named_data_mutex()
    {
        mutex = (aos.jack.util.thread.Semaphore) getNamedObject("mutex","aos.jack.util.thread.Semaphore");
        return mutex;
    }
    
    private aos.jack.util.thread.Semaphore __named_data_mutex2()
    {
        mutex2 = (aos.jack.util.thread.Semaphore) getNamedObject("mutex2","aos.jack.util.thread.Semaphore");
        return mutex2;
    }
    
    private NeonAffect.NA_Debug __named_data_debug()
    {
        debug = (NeonAffect.NA_Debug) getNamedObject("debug","NeonAffect.NA_Debug");
        return debug;
    }
    
}
