/*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*
  This code is generated by JAC version 5.6 by
  Agent Oriented Software. http://www.agent-software.com.au

    DO NOT ALTER THIS CODE AND DO NOT REMOVE THIS COMMENT
 *=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*/
package NeonAffect;
import aos.jack.jak.agent.Capability;
import aos.jack.jak.agent.NameSpace;
import aos.jack.jak.agent.Agent;
import aos.jack.util.thread.Semaphore;

/**
 * 
 */

public class CompassionAffectCapability extends aos.jack.jak.agent.Capability {
    public NeonAffect.PlanContextName planContextName;
    public NeonAffect.Behavior behaviorName;
    public aos.jack.util.thread.Semaphore mutex;
    public aos.jack.util.thread.Semaphore mutex2;
    public NeonAffect.NA_Debug debug;
    public NeonAffect.ContextEvent ce;
    public java.lang.String getDocumentation()
    {
        return "/**\n * \n */\n";
    }
    
    public void __init1()
    {
        setNamedCreator("planContextName","NeonAffect.PlanContextName",new aos.jack.jak.agent.DataCreator(false){
            public java.lang.Object create()
            {
                return __named_data_planContextName();
            }
            
        },true);
        setNamedCreator("behaviorName","NeonAffect.Behavior",new aos.jack.jak.agent.DataCreator(false){
            public java.lang.Object create()
            {
                return __named_data_behaviorName();
            }
            
        },true);
        setNamedCreator("mutex","aos.jack.util.thread.Semaphore",new aos.jack.jak.agent.DataCreator(false){
            public java.lang.Object create()
            {
                return __named_data_mutex();
            }
            
        },true);
        setNamedCreator("mutex2","aos.jack.util.thread.Semaphore",new aos.jack.jak.agent.DataCreator(false){
            public java.lang.Object create()
            {
                return __named_data_mutex2();
            }
            
        },true);
        setNamedCreator("debug","NeonAffect.NA_Debug",new aos.jack.jak.agent.DataCreator(false){
            public java.lang.Object create()
            {
                return __named_data_debug();
            }
            
        },true);
    }
    
    public void __init2()
    {
        ce = (NeonAffect.ContextEvent) findEvent("NeonAffect.ContextEvent");
        planContextName = (NeonAffect.PlanContextName) getNamedObject("planContextName","NeonAffect.PlanContextName");
        behaviorName = (NeonAffect.Behavior) getNamedObject("behaviorName","NeonAffect.Behavior");
        mutex = (aos.jack.util.thread.Semaphore) getNamedObject("mutex","aos.jack.util.thread.Semaphore");
        mutex2 = (aos.jack.util.thread.Semaphore) getNamedObject("mutex2","aos.jack.util.thread.Semaphore");
        debug = (NeonAffect.NA_Debug) getNamedObject("debug","NeonAffect.NA_Debug");
        autorun();
    }
    
    synchronized public void __init_desc()
    {
        externals.put("debug","debug");
        externals.put("mutex2","mutex2");
        externals.put("mutex","mutex");
        externals.put("behaviorName","behaviorName");
        externals.put("planContextName","planContextName");
        externals.put("NeonAffect.SetPlanContextEvent","NeonAffect.SetPlanContextEvent");
        externals.put("NeonAffect.Level5PosAffectEvent","NeonAffect.Level5PosAffectEvent");
        addEvent("NeonAffect.Level5PosAffectEvent",aos.jack.jak.agent.Agent.HANDLED_EVENT);
        addEvent("NeonAffect.SetPlanContextEvent",aos.jack.jak.agent.Agent.HANDLED_EVENT);
        addEvent("NeonAffect.ContextEvent",aos.jack.jak.agent.Agent.SENT_EVENT);
        addPlan("NeonAffect.AskingHowToHelpPlan",0);
        addPlan("NeonAffect.CryingCompassionPlan",0);
        addPlan("NeonAffect.EyeContactCompassionPlan",0);
        addPlan("NeonAffect.FaceConcernedPlan",0);
        addPlan("NeonAffect.GratitudeCompassionPlan",0);
        addPlan("NeonAffect.HeadTiltingToSideCompassionPlan",0);
        addPlan("NeonAffect.OfferingEncouragementSupportCompassionPlan",0);
        addPlan("NeonAffect.OfferingHugPlan",0);
        addPlan("NeonAffect.OfferingToBabysitPlan",0);
        addPlan("NeonAffect.OfferingToHelpCompassionPlan",0);
        addPlan("NeonAffect.OfferingToTeachSkillPlan",0);
        addPlan("NeonAffect.OpenBodyPostureCompassionPlan",0);
        addPlan("NeonAffect.ProvideListeningEarPlan",0);
        addPlan("NeonAffect.SharingSecretsCompassionPlan",0);
        addPlan("NeonAffect.SmilingCompassionPlan",0);
        addPlan("NeonAffect.SpeakingSoflyCompassionPlan",0);
        addPlan("NeonAffect.SpeakingSupportiveWordsPlan",0);
        addPlan("NeonAffect.ValidsatingFeelingsPlan",0);
        addPlan("NeonAffect.SetPlanContextCompassionPlan",0);
    }
    
    public CompassionAffectCapability(aos.jack.jak.agent.NameSpace outer)
    {
        super(outer);
    }
    
    synchronized public void __bindNames()
    {
        super.__bindNames();
        __bindToPlan("NeonAffect.AskingHowToHelpPlan");
        __bindToPlan("NeonAffect.CryingCompassionPlan");
        __bindToPlan("NeonAffect.EyeContactCompassionPlan");
        __bindToPlan("NeonAffect.FaceConcernedPlan");
        __bindToPlan("NeonAffect.GratitudeCompassionPlan");
        __bindToPlan("NeonAffect.HeadTiltingToSideCompassionPlan");
        __bindToPlan("NeonAffect.OfferingEncouragementSupportCompassionPlan");
        __bindToPlan("NeonAffect.OfferingHugPlan");
        __bindToPlan("NeonAffect.OfferingToBabysitPlan");
        __bindToPlan("NeonAffect.OfferingToHelpCompassionPlan");
        __bindToPlan("NeonAffect.OfferingToTeachSkillPlan");
        __bindToPlan("NeonAffect.OpenBodyPostureCompassionPlan");
        __bindToPlan("NeonAffect.ProvideListeningEarPlan");
        __bindToPlan("NeonAffect.SharingSecretsCompassionPlan");
        __bindToPlan("NeonAffect.SmilingCompassionPlan");
        __bindToPlan("NeonAffect.SpeakingSoflyCompassionPlan");
        __bindToPlan("NeonAffect.SpeakingSupportiveWordsPlan");
        __bindToPlan("NeonAffect.ValidsatingFeelingsPlan");
        __bindToPlan("NeonAffect.SetPlanContextCompassionPlan");
    }
    
    private NeonAffect.PlanContextName __named_data_planContextName()
    {
        planContextName = (NeonAffect.PlanContextName) getNamedObject("planContextName","NeonAffect.PlanContextName");
        return planContextName;
    }
    
    private NeonAffect.Behavior __named_data_behaviorName()
    {
        behaviorName = (NeonAffect.Behavior) getNamedObject("behaviorName","NeonAffect.Behavior");
        return behaviorName;
    }
    
    private aos.jack.util.thread.Semaphore __named_data_mutex()
    {
        mutex = (aos.jack.util.thread.Semaphore) getNamedObject("mutex","aos.jack.util.thread.Semaphore");
        return mutex;
    }
    
    private aos.jack.util.thread.Semaphore __named_data_mutex2()
    {
        mutex2 = (aos.jack.util.thread.Semaphore) getNamedObject("mutex2","aos.jack.util.thread.Semaphore");
        return mutex2;
    }
    
    private NeonAffect.NA_Debug __named_data_debug()
    {
        debug = (NeonAffect.NA_Debug) getNamedObject("debug","NeonAffect.NA_Debug");
        return debug;
    }
    
}
