/*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*
  This code is generated by JAC version 5.6 by
  Agent Oriented Software. http://www.agent-software.com.au

    DO NOT ALTER THIS CODE AND DO NOT REMOVE THIS COMMENT
 *=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*/
package NeonAffect;
import aos.jack.jak.plan.Plan;
import aos.jack.jak.plan.PlanFSM;
import aos.jack.jak.plan.ExMap;
import aos.jack.jak.agent.NameSpace;
import aos.jack.jak.event.Event;
import aos.jack.jak.task.Task;
import aos.jack.jak.core.Generator;
import aos.jack.jak.logic.Signature;
import aos.jack.util.thread.Semaphore;
import aos.jack.jak.beliefset.BeliefSetException;
import java.lang.Object;
import aos.jack.jak.cursor.Cursor;
import aos.jack.jak.fsm.FSM;
import aos.jack.jak.core.Jak;

/**
 * 
 */

public class SetPlanContextPlan2 extends aos.jack.jak.plan.Plan {
    private static java.lang.Class __exClass_0 = aos.jack.jak.fsm.FSM.loadClass("aos.jack.jak.beliefset.BeliefSetException");
    public NeonAffect.SetPlanContextEvent2 spce2;
    public NeonAffect.PlanContextName planContextName;
    public NeonAffect.NA_Debug debug;
    public aos.jack.util.thread.Semaphore mutex;
    private static aos.jack.jak.plan.ExMap[] __exMap_body = {
            new aos.jack.jak.plan.ExMap(10,19,20,__exClass_0),
            new aos.jack.jak.plan.ExMap(10,21,22,null)};
    private static java.lang.String[] __tt__body = {
            "NeonAffect/SetPlanContextPlan2.plan",
            "body",
            "42",
            "43",
            "45",
            "47",
            "72",
            "74",
            "76",
            "77",
            "79",
            "81",
            "84",
            "86",
            "90",
            "89",
            "37"};
    private final static java.lang.String[] __planVariableNames = {
            "spce2",
            "planContextName",
            "debug",
            "mutex"};
    private final static java.lang.String[] __planVariableTypes = {
            "NeonAffect.SetPlanContextEvent2",
            "NeonAffect.PlanContextName",
            "NeonAffect.NA_Debug",
            "aos.jack.util.thread.Semaphore"};
    private final static java.lang.String[] __reasoningMethods = {
            "body"};
    private final static java.lang.String[] __fsmVariableNames_body = {
            "$debug",
            "bDebug",
            "$planName",
            "strPlanName",
            "e"};
    private final static java.lang.String[] __fsmTypes_body = {
            "logical boolean",
            "boolean",
            "logical String",
            "String",
            "BeliefSetException"};
    private final static java.lang.String[] __fsmLocalNames_body = {
            "__local__2573_0",
            "__local__2573_1",
            "__local__2573_2",
            "__local__2573_3",
            "__local__2573_4"};
    static boolean relevant(NeonAffect.SetPlanContextEvent2 spce2)
    {
        return true;
    }
    
    public java.lang.String getDocumentation()
    {
        return "/**\n * \n */\n";
    }
    
    public SetPlanContextPlan2()
    {
    }
    
    private SetPlanContextPlan2(aos.jack.jak.task.Task __t, NeonAffect.SetPlanContextPlan2 __env)
    {
        __agent = __env.__agent;
        __ns = __env.__ns;
        __planTask = __t;
        __logic = __t.logic;
        spce2 = __env.spce2;
        planContextName = __env.planContextName;
        debug = __env.debug;
        mutex = __env.mutex;
    }
    
    public boolean init_sentinel(aos.jack.jak.agent.NameSpace __a)
    {
        spce2 = (NeonAffect.SetPlanContextEvent2) __a.findEvent("NeonAffect.SetPlanContextEvent2");
        if (spce2 == null) {
            warning("SetPlanContextEvent2 spce2: is not found in the capability/agent this plan comes from");
            return false;
        }
        planContextName = (NeonAffect.PlanContextName) lookupNamedObject("planContextName","NeonAffect.PlanContextName",0);
        if (planContextName == null) {
            warning("PlanContextName planContextName: is not found in the capability/agent this plan comes from");
            return false;
        }
        debug = (NeonAffect.NA_Debug) lookupNamedObject("debug","NeonAffect.NA_Debug",0);
        if (debug == null) {
            warning("NA_Debug debug: is not found in the capability/agent this plan comes from");
            return false;
        }
        mutex = (aos.jack.util.thread.Semaphore) lookupNamedObject("mutex","aos.jack.util.thread.Semaphore",0);
        if (mutex == null) {
            warning("Semaphore mutex: is not found in the capability/agent this plan comes from");
            return false;
        }
        return true;
    }
    
    public aos.jack.jak.plan.Plan freeze()
    {
        return this;
    }
    
    public aos.jack.jak.plan.Plan unfreeze()
    {
        return this;
    }
    
    public java.lang.Object genObject(int __index)
    {
        switch (__index) {
        }
        aos.jack.jak.core.Jak.error("illegal Object Construction");
        return null;
    }
    
    public aos.jack.jak.cursor.Cursor genCursor(int __index)
        throws java.lang.Exception
    {
        switch (__index) {
        }
        aos.jack.jak.core.Jak.error("illegal Cursor Construction");
        return null;
    }
    
    public aos.jack.jak.fsm.FSM genFSM(int __index)
        throws java.lang.Exception
    {
        switch (__index) {
        }
        aos.jack.jak.core.Jak.error("illegal FSM Construction");
        return null;
    }
    
    public boolean testCondition(int __index)
        throws java.lang.Exception
    {
        switch (__index) {
        }
        aos.jack.jak.core.Jak.error("illegal test Construction");
        return false;
    }
    
    public aos.jack.jak.plan.PlanFSM body()
    {
        return new NeonAffect.SetPlanContextPlan2.__bodyFSM();
    }
    
    private SetPlanContextPlan2(NeonAffect.SetPlanContextEvent2 __ev, aos.jack.jak.task.Task __t, NeonAffect.SetPlanContextPlan2 __env)
    {
        this(__t,__env);
        this.spce2 = __ev;
    }
    
    protected aos.jack.jak.logic.Signature eventSignature(int __log)
    {
        return spce2.getSignature(__log);
    }
    
    public java.lang.String handledEvent()
    {
        return "NeonAffect.SetPlanContextEvent2";
    }
    
    public boolean __relevant(aos.jack.jak.event.Event __e)
    {
        return __ns.isEnabled() && relevant(((NeonAffect.SetPlanContextEvent2) __e));
    }
    
    public aos.jack.jak.plan.Plan createPlan(aos.jack.jak.event.Event __e, aos.jack.jak.task.Task __t)
    {
        if (!(__e instanceof NeonAffect.SetPlanContextEvent2)) 
            return null;
        NeonAffect.SetPlanContextEvent2 __e1 = (NeonAffect.SetPlanContextEvent2) __e;
        return new NeonAffect.SetPlanContextPlan2(__e1,__t,this);
    }
    
    public java.lang.String[] variableNames()
    {
        return __planVariableNames;
    }
    
    public java.lang.String[] variableTypes()
    {
        return __planVariableTypes;
    }
    
    public java.lang.Object getVariable(int n)
    {
        switch (n) {
            case 0: 
            {
                return aos.util.ToObject.box(spce2);
            }
            case 1: 
            {
                return aos.util.ToObject.box(planContextName);
            }
            case 2: 
            {
                return aos.util.ToObject.box(debug);
            }
            case 3: 
            {
                return aos.util.ToObject.box(mutex);
            }
            default: 
            {
                throw new java.lang.IndexOutOfBoundsException("Plan " + this + " does not have variable number " + n);
            }
        }
    }
    
    public java.lang.String[] reasoningMethods()
    {
        return mergeReasoningMethods(__reasoningMethods,super.reasoningMethods());
    }
    
    public aos.jack.jak.cursor.Cursor context()
    {
        try {
            return (((true)?aos.jack.jak.cursor.Cursor.trueCursor:aos.jack.jak.cursor.Cursor.falseCursor));
        }
        catch (java.lang.Exception e) {
            e.printStackTrace();
            return aos.jack.jak.cursor.Cursor.falseCursor;
        }
    }
    
    class __bodyFSM extends aos.jack.jak.plan.PlanFSM implements aos.jack.jak.core.Generator {
        aos.jack.jak.logic.BooleanVariable __local__2573_0;
        boolean __local__2573_1;
        aos.jack.jak.logic.StringVariable __local__2573_2;
        java.lang.String __local__2573_3;
        aos.jack.jak.beliefset.BeliefSetException __local__2573_4;
        private int __breakLevel = 0;
        public int run(int __status)
            throws java.lang.Throwable
        {
            do {
                try {
                    if (__tothrow != null) 
                        throw __tothrow;
                    if ((aos.jack.jak.core.Jak.debugging & aos.jack.jak.core.Jak.LOG_PLANS) != 0) 
                        aos.util.logging.LogMsg.log(this,aos.jack.jak.core.Jak.LOG_PLANS,__task + "-SetPlanContextPlan2.body:" + java.lang.Integer.toString(__state));
                    if (__task.nsteps > 0) {
                        __task.nsteps-- ;
                        if (__task.nsteps == 0) 
                            agent.changeFocus();
                    }
                    if (__state < 10) {
                        __status = super.stdrun(NeonAffect.SetPlanContextPlan2.this,__status);
                        if (__status != CONTINUE || agent.changing_focus) 
                            return __status;
                        continue;
                    }
                    __curstate = __state;
                    switch (__state) {
                        default: 
                        {
                            aos.jack.jak.core.Jak.error("SetPlanContextPlan2.body: Illegal state");
                            return FAILED_STATE;
                        }
                        //* (42)             logical boolean $debug;
                        case 10: 
                        {
                            __breakLevel = 2;
                            __local__2573_0 = (aos.jack.jak.logic.BooleanVariable) __logic.new_variable(java.lang.Boolean.TYPE);
                            __state = 11;
                            break;
                        }
                        //* (43)             debug.get($debug).next();
                        case 11: 
                        {
                            if (debug.get(__local__2573_0).next()) 
                                __state = 12;
                             else 
                                throw planfailed;
                            break;
                        }
                        //* (45)             boolean bDebug = false;
                        case 12: 
                        {
                            __local__2573_1 = false;
                            __state = 13;
                            break;
                        }
                        //* (47)             bDebug = $debug.as_boolean();
                        case 13: 
                        {
                            __state = 14;
                            __local__2573_1 = __local__2573_0.as_boolean();
                            break;
                        }
                        //* (72)             planContextName.add(0, spce2.strName);
                        case 14: 
                        {
                            __state = 15;
                            /*
            if (bDebug)
            {
                System.out.println("Inside SetPlanContextPlan2 strName [" + spce2.strName + "]");
            }
    
            if (bDebug)
            {
                System.out.println("Inside SetPlanContextPlan2. iterating ids:");
            }
    
            Configuration config = Configuration.getInstance();
            
            Set ids = config.getModeratorInstances();
     
            Iterator iter = ids.iterator();
     
            while(iter.hasNext()) {
                System.out.println(iter.next());
            }
      */
//ModeratorEngine engine = getModerator(java.lang.String moderatorId)

                            planContextName.add(0,spce2.strName);
                            break;
                        }
                        //* (74)             if (bDebug)
                        case 15: 
                        {
                            if (__local__2573_1) 
                                __state = 16;
                             else 
                                __state = 22;
                            break;
                        }
                        //* (76)                 logical String $planName;
                        case 16: 
                        {
                            __breakLevel = 4;
                            __local__2573_2 = (aos.jack.jak.logic.StringVariable) __logic.new_variable(java.lang.String.class);
                            __state = 17;
                            break;
                        }
                        //* (77)                 planContextName.get(0, $planName).next();
                        case 17: 
                        {
                            if (planContextName.get(0,__local__2573_2).next()) 
                                __state = 18;
                             else 
                                throw planfailed;
                            break;
                        }
                        //* (79)                 String strPlanName = $planName.as_string();
                        case 18: 
                        {
                            __local__2573_3 = __local__2573_2.as_string();
                            __state = 19;
                            break;
                        }
                        //* (81)                 System.out.println("Inside SetPlanContextPlan2 set to [" + strPlanName + "]");
                        case 19: 
                        {
                            __state = 22;
                            java.lang.System.out.println("Inside SetPlanContextPlan2 set to [" + __local__2573_3 + "]");
                            break;
                        }
                        //* (84)         catch (BeliefSetException e)
                        case 20: 
                        {
                            __breakLevel = 2;
                            __state = 21;
                            __local__2573_4 = (aos.jack.jak.beliefset.BeliefSetException) __current;
                            break;
                        }
                        //* (86)             e.printStackTrace();    
                        case 21: 
                        {
                            __breakLevel = 4;
                            __state = 22;
                            __local__2573_4.printStackTrace();
                            break;
                        }
                        //* (90)             mutex.signal();     
                        case 22: 
                        {
                            __breakLevel = 2;
                            __state = 23;
                            mutex.signal();
                            break;
                        }
                        //* (89)         {
                        case 23: 
                        {
                            __state = 24;
                            if (__breakLevel < 2) 
                                __state = 24;
                            __tothrow = __pending;
                            break;
                        }
                        //* (37)     #reasoning method
                        case 24: 
                        {
                            if (__pending == null) 
                                __state = PASSED_STATE;
                            __tothrow = __pending;
                            break;
                        }
                    }
                }
                catch (java.lang.Throwable e) {
                    handleException(e,__exMap_body);
                }
            }
             while (!agent.changing_focus);
            return CONTINUE;
        }
        
        public java.lang.String methodName()
        {
            return "body";
        }
        
        __bodyFSM()
        {
        }
        
        public java.lang.String stateInfo()
        {
            int n = __curstate;
            java.lang.String file = __tt__body[0];
            java.lang.String method = __tt__body[1];
            if (n < 0) 
                n = -n;
            n -= (10 - 2);
            java.lang.String line = (n < 2)?"??":__tt__body[n];
            return file + ":" + line + " " + method + " [" + __curstate + "]";
        }
        
        public java.lang.Object genObject(int __index)
        {
            switch (__index) {
            }
            aos.jack.jak.core.Jak.error("illegal Object Construction");
            return null;
        }
        
        public aos.jack.jak.cursor.Cursor genCursor(int __index)
            throws java.lang.Exception
        {
            switch (__index) {
            }
            aos.jack.jak.core.Jak.error("illegal Cursor Construction");
            return null;
        }
        
        public aos.jack.jak.fsm.FSM genFSM(int __index)
            throws java.lang.Exception
        {
            switch (__index) {
            }
            aos.jack.jak.core.Jak.error("illegal FSM Construction");
            return null;
        }
        
        public boolean testCondition(int __index)
            throws java.lang.Exception
        {
            switch (__index) {
            }
            aos.jack.jak.core.Jak.error("illegal test Construction");
            return false;
        }
        
        public aos.jack.jak.plan.Plan getPlan()
        {
            return NeonAffect.SetPlanContextPlan2.this;
        }
        
        protected aos.jack.jak.fsm.FSM fail()
        {
            return getPlan().fail();
        }
        
        protected aos.jack.jak.fsm.FSM pass()
        {
            return getPlan().pass();
        }
        
        public void enter()
        {
            __trace = agent.trace("NeonAffect.SetPlanContextPlan2.body");
        }
        
        public java.lang.Object getVariable(int n)
        {
            switch (n) {
                case 0: 
                {
                    return aos.util.ToObject.box(__local__2573_0);
                }
                case 1: 
                {
                    return aos.util.ToObject.box(__local__2573_1);
                }
                case 2: 
                {
                    return aos.util.ToObject.box(__local__2573_2);
                }
                case 3: 
                {
                    return aos.util.ToObject.box(__local__2573_3);
                }
                case 4: 
                {
                    return aos.util.ToObject.box(__local__2573_4);
                }
                default: 
                {
                    throw new java.lang.IndexOutOfBoundsException("Reasoning Method " + methodName() + " does not have variable number " + n);
                }
            }
        }
        
        public java.lang.String[] variableNames()
        {
            return __fsmVariableNames_body;
        }
        
        public java.lang.String[] variableTypes()
        {
            return __fsmTypes_body;
        }
        
        public java.lang.String[] variableLocalNames()
        {
            return __fsmLocalNames_body;
        }
        
    }
}
