/*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*
  This code is generated by JAC version 5.6 by
  Agent Oriented Software. http://www.agent-software.com.au

    DO NOT ALTER THIS CODE AND DO NOT REMOVE THIS COMMENT
 *=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*/
package NeonAffect;
import aos.jack.jak.plan.Plan;
import aos.jack.jak.plan.PlanFSM;
import aos.jack.jak.plan.ExMap;
import aos.jack.jak.agent.NameSpace;
import aos.jack.jak.agent.Agent;
import aos.jack.jak.event.Event;
import aos.jack.jak.task.Task;
import aos.jack.jak.core.Generator;
import aos.jack.jak.logic.Signature;
import aos.jack.util.thread.Semaphore;
import aos.cojack.configuration.Configuration;
import java.lang.Object;
import aos.jack.jak.cursor.Cursor;
import aos.jack.jak.fsm.FSM;
import aos.jack.jak.core.Jak;

/**
 * 
 */

public class AddEmotionPlan extends aos.jack.jak.plan.Plan {
    private boolean bDebug = false;
    private static java.lang.Class __exClass_0 = aos.jack.jak.fsm.FSM.loadClass("java.lang.Exception");
    public NeonAffect.AddEmotionEvent aee;
    public NeonAffect.Emotion emotion;
    public aos.jack.util.thread.Semaphore mutex4;
    public NeonAffect.NA_Debug debug;
    private static aos.jack.jak.plan.ExMap[] __exMap_body = {
            new aos.jack.jak.plan.ExMap(10,29,30,__exClass_0),
            new aos.jack.jak.plan.ExMap(10,31,32,null)};
    private static java.lang.String[] __tt__body = {
            "NeonAffect/AddEmotionPlan.plan",
            "body",
            "41",
            "42",
            "44",
            "46",
            "48",
            "53",
            "55",
            "57",
            "60",
            "62",
            "66",
            "70",
            "72",
            "75",
            "77",
            "81",
            "84",
            "86",
            "88",
            "90",
            "93",
            "95",
            "99",
            "98",
            "36"};
    private final static java.lang.String[] __planVariableNames = {
            "bDebug",
            "aee",
            "emotion",
            "mutex4",
            "debug"};
    private final static java.lang.String[] __planVariableTypes = {
            "boolean",
            "NeonAffect.AddEmotionEvent",
            "Emotion",
            "aos.jack.util.thread.Semaphore",
            "NeonAffect.NA_Debug"};
    private final static java.lang.String[] __reasoningMethods = {
            "body"};
    private final static java.lang.String[] __fsmVariableNames_body = {
            "$debug",
            "bDebug",
            "strModerator",
            "dValue",
            "lTime",
            "dReservoir",
            "e"};
    private final static java.lang.String[] __fsmTypes_body = {
            "logical boolean",
            "boolean",
            "String",
            "double",
            "long",
            "double",
            "Exception"};
    private final static java.lang.String[] __fsmLocalNames_body = {
            "__local__24_0",
            "__local__24_1",
            "__local__24_2",
            "__local__24_3",
            "__local__24_4",
            "__local__24_5",
            "__local__24_6"};
    static boolean relevant(NeonAffect.AddEmotionEvent aee)
    {
        return true;
    }
    
    public java.lang.String getDocumentation()
    {
        return "/**\n * \n */\n";
    }
    
    public AddEmotionPlan()
    {
    }
    
    private AddEmotionPlan(aos.jack.jak.task.Task __t, NeonAffect.AddEmotionPlan __env)
    {
        __agent = __env.__agent;
        __ns = __env.__ns;
        __planTask = __t;
        __logic = __t.logic;
        aee = __env.aee;
        emotion = __env.emotion;
        mutex4 = __env.mutex4;
        debug = __env.debug;
    }
    
    public boolean init_sentinel(aos.jack.jak.agent.NameSpace __a)
    {
        aee = (NeonAffect.AddEmotionEvent) __a.findEvent("NeonAffect.AddEmotionEvent");
        if (aee == null) {
            warning("AddEmotionEvent aee: is not found in the capability/agent this plan comes from");
            return false;
        }
        emotion = (NeonAffect.Emotion) lookupNamedObject("emotion","NeonAffect.Emotion",aos.jack.jak.agent.Agent.WRITEABLE);
        if (emotion == null) {
            warning("Emotion emotion: is not found in the capability/agent this plan comes from");
            return false;
        }
        mutex4 = (aos.jack.util.thread.Semaphore) lookupNamedObject("mutex4","aos.jack.util.thread.Semaphore",0);
        if (mutex4 == null) {
            warning("Semaphore mutex4: is not found in the capability/agent this plan comes from");
            return false;
        }
        debug = (NeonAffect.NA_Debug) lookupNamedObject("debug","NeonAffect.NA_Debug",0);
        if (debug == null) {
            warning("NA_Debug debug: is not found in the capability/agent this plan comes from");
            return false;
        }
        return true;
    }
    
    public aos.jack.jak.plan.Plan freeze()
    {
        return this;
    }
    
    public aos.jack.jak.plan.Plan unfreeze()
    {
        return this;
    }
    
    public java.lang.Object genObject(int __index)
    {
        switch (__index) {
        }
        aos.jack.jak.core.Jak.error("illegal Object Construction");
        return null;
    }
    
    public aos.jack.jak.cursor.Cursor genCursor(int __index)
        throws java.lang.Exception
    {
        switch (__index) {
        }
        aos.jack.jak.core.Jak.error("illegal Cursor Construction");
        return null;
    }
    
    public aos.jack.jak.fsm.FSM genFSM(int __index)
        throws java.lang.Exception
    {
        switch (__index) {
        }
        aos.jack.jak.core.Jak.error("illegal FSM Construction");
        return null;
    }
    
    public boolean testCondition(int __index)
        throws java.lang.Exception
    {
        switch (__index) {
        }
        aos.jack.jak.core.Jak.error("illegal test Construction");
        return false;
    }
    
    public aos.jack.jak.plan.PlanFSM body()
    {
        return new NeonAffect.AddEmotionPlan.__bodyFSM();
    }
    
    private AddEmotionPlan(NeonAffect.AddEmotionEvent __ev, aos.jack.jak.task.Task __t, NeonAffect.AddEmotionPlan __env)
    {
        this(__t,__env);
        this.aee = __ev;
    }
    
    protected aos.jack.jak.logic.Signature eventSignature(int __log)
    {
        return aee.getSignature(__log);
    }
    
    public java.lang.String handledEvent()
    {
        return "NeonAffect.AddEmotionEvent";
    }
    
    public boolean __relevant(aos.jack.jak.event.Event __e)
    {
        return __ns.isEnabled() && relevant(((NeonAffect.AddEmotionEvent) __e));
    }
    
    public aos.jack.jak.plan.Plan createPlan(aos.jack.jak.event.Event __e, aos.jack.jak.task.Task __t)
    {
        if (!(__e instanceof NeonAffect.AddEmotionEvent)) 
            return null;
        NeonAffect.AddEmotionEvent __e1 = (NeonAffect.AddEmotionEvent) __e;
        return new NeonAffect.AddEmotionPlan(__e1,__t,this);
    }
    
    public java.lang.String[] variableNames()
    {
        return __planVariableNames;
    }
    
    public java.lang.String[] variableTypes()
    {
        return __planVariableTypes;
    }
    
    public java.lang.Object getVariable(int n)
    {
        switch (n) {
            case 0: 
            {
                return aos.util.ToObject.box(bDebug);
            }
            case 1: 
            {
                return aos.util.ToObject.box(aee);
            }
            case 2: 
            {
                return aos.util.ToObject.box(emotion);
            }
            case 3: 
            {
                return aos.util.ToObject.box(mutex4);
            }
            case 4: 
            {
                return aos.util.ToObject.box(debug);
            }
            default: 
            {
                throw new java.lang.IndexOutOfBoundsException("Plan " + this + " does not have variable number " + n);
            }
        }
    }
    
    public java.lang.String[] reasoningMethods()
    {
        return mergeReasoningMethods(__reasoningMethods,super.reasoningMethods());
    }
    
    public aos.jack.jak.cursor.Cursor context()
    {
        try {
            return (((true)?aos.jack.jak.cursor.Cursor.trueCursor:aos.jack.jak.cursor.Cursor.falseCursor));
        }
        catch (java.lang.Exception e) {
            e.printStackTrace();
            return aos.jack.jak.cursor.Cursor.falseCursor;
        }
    }
    
    class __bodyFSM extends aos.jack.jak.plan.PlanFSM implements aos.jack.jak.core.Generator {
        aos.jack.jak.logic.BooleanVariable __local__24_0;
        boolean __local__24_1;
        java.lang.String __local__24_2;
        double __local__24_3;
        long __local__24_4;
        double __local__24_5;
        java.lang.Exception __local__24_6;
        private int __breakLevel = 0;
        public int run(int __status)
            throws java.lang.Throwable
        {
            do {
                try {
                    if (__tothrow != null) 
                        throw __tothrow;
                    if ((aos.jack.jak.core.Jak.debugging & aos.jack.jak.core.Jak.LOG_PLANS) != 0) 
                        aos.util.logging.LogMsg.log(this,aos.jack.jak.core.Jak.LOG_PLANS,__task + "-AddEmotionPlan.body:" + java.lang.Integer.toString(__state));
                    if (__task.nsteps > 0) {
                        __task.nsteps-- ;
                        if (__task.nsteps == 0) 
                            agent.changeFocus();
                    }
                    if (__state < 10) {
                        __status = super.stdrun(NeonAffect.AddEmotionPlan.this,__status);
                        if (__status != CONTINUE || agent.changing_focus) 
                            return __status;
                        continue;
                    }
                    __curstate = __state;
                    switch (__state) {
                        default: 
                        {
                            aos.jack.jak.core.Jak.error("AddEmotionPlan.body: Illegal state");
                            return FAILED_STATE;
                        }
                        //* (41)             logical boolean $debug;
                        case 10: 
                        {
                            __breakLevel = 2;
                            __local__24_0 = (aos.jack.jak.logic.BooleanVariable) __logic.new_variable(java.lang.Boolean.TYPE);
                            __state = 11;
                            break;
                        }
                        //* (42)             debug.get($debug).next();
                        case 11: 
                        {
                            if (debug.get(__local__24_0).next()) 
                                __state = 12;
                             else 
                                throw planfailed;
                            break;
                        }
                        //* (44)             boolean bDebug = $debug.as_boolean();
                        case 12: 
                        {
                            __local__24_1 = __local__24_0.as_boolean();
                            __state = 13;
                            break;
                        }
                        //* (46)             if (bDebug)
                        case 13: 
                        {
                            if (__local__24_1) 
                                __state = 14;
                             else 
                                __state = 15;
                            break;
                        }
                        //* (48)                 System.out.println("Inside AddEmotionPlan.");
                        case 14: 
                        {
                            __breakLevel = 4;
                            __state = 15;
                            java.lang.System.out.println("Inside AddEmotionPlan.");
                            break;
                        }
                        //* (53)             String strModerator = aee.strModerator;
                        case 15: 
                        {
                            __local__24_2 = aee.strModerator;
                            __state = 16;
                            break;
                        }
                        //* (55)             if (bDebug)
                        case 16: 
                        {
                            if (__local__24_1) 
                                __state = 17;
                             else 
                                __state = 18;
                            break;
                        }
                        //* (57)                 System.out.println("Moderator name: [" + strModerator + "]");
                        case 17: 
                        {
                            __breakLevel = 4;
                            __state = 18;
                            java.lang.System.out.println("Moderator name: [" + __local__24_2 + "]");
                            break;
                        }
                        //* (60)             double dValue = aee.dAmount;
                        case 18: 
                        {
                            __local__24_3 = aee.dAmount;
                            __state = 19;
                            break;
                        }
                        //* (62)             long lTime = agent.timer.getTime();
                        case 19: 
                        {
                            __local__24_4 = agent.timer.getTime();
                            __state = 20;
                            break;
                        }
                        //* (66)             double dReservoir = Configuration.moderatorCurrentReservoir(agent.getId(), strModerator, lTime);
                        case 20: 
                        {
                            __local__24_5 = aos.cojack.configuration.Configuration.moderatorCurrentReservoir(agent.getId(),__local__24_2,__local__24_4);
                            __state = 21;
                            break;
                        }
                        //* (70)             if (bDebug)
                        case 21: 
                        {
                            if (__local__24_1) 
                                __state = 22;
                             else 
                                __state = 23;
                            break;
                        }
                        //* (72)                 System.out.println("Injecting " + dValue + "+" + dReservoir + " @ " + lTime+"\n");
                        case 22: 
                        {
                            __breakLevel = 4;
                            __state = 23;
                            java.lang.System.out.println("Injecting " + __local__24_3 + "+" + __local__24_5 + " @ " + __local__24_4 + "\n");
                            break;
                        }
                        //* (75)             if (aee.bIncremental)
                        case 23: 
                        {
                            if (aee.bIncremental) 
                                __state = 24;
                             else 
                                __state = 25;
                            break;
                        }
                        //* (77)                 dReservoir = dReservoir + dValue;
                        case 24: 
                        {
                            __breakLevel = 4;
                            __state = 26;
                            __local__24_5 = __local__24_5 + __local__24_3;
                            break;
                        }
                        //* (81)                 dReservoir = dValue;
                        case 25: 
                        {
                            __breakLevel = 4;
                            __state = 26;
                            __local__24_5 = __local__24_3;
                            break;
                        }
                        //* (84)             Configuration.moderatorReservoirAgentUpdate(agent.getId(), strModerator, dReservoir, lTime);
                        case 26: 
                        {
                            __state = 27;
                            aos.cojack.configuration.Configuration.moderatorReservoirAgentUpdate(agent.getId(),__local__24_2,__local__24_5,__local__24_4);
                            break;
                        }
                        //* (86)             dReservoir = Configuration.moderatorCurrentReservoir(agent.getId(), strModerator, lTime);
                        case 27: 
                        {
                            __state = 28;
                            __local__24_5 = aos.cojack.configuration.Configuration.moderatorCurrentReservoir(agent.getId(),__local__24_2,__local__24_4);
                            break;
                        }
                        //* (88)             if (bDebug)
                        case 28: 
                        {
                            if (__local__24_1) 
                                __state = 29;
                             else 
                                __state = 32;
                            break;
                        }
                        //* (90)                 System.out.println(dReservoir + " is the amount for affect emotion " + dValue + "\n");
                        case 29: 
                        {
                            __breakLevel = 4;
                            __state = 32;
                            java.lang.System.out.println(__local__24_5 + " is the amount for affect emotion " + __local__24_3 + "\n");
                            break;
                        }
                        //* (93)         catch (Exception e)
                        case 30: 
                        {
                            __breakLevel = 2;
                            __state = 31;
                            __local__24_6 = (java.lang.Exception) __current;
                            break;
                        }
                        //* (95)             e.printStackTrace();
                        case 31: 
                        {
                            __breakLevel = 4;
                            __state = 32;
                            __local__24_6.printStackTrace();
                            break;
                        }
                        //* (99)             mutex4.signal();
                        case 32: 
                        {
                            __breakLevel = 2;
                            __state = 33;
                            mutex4.signal();
                            break;
                        }
                        //* (98)         {
                        case 33: 
                        {
                            __state = 34;
                            if (__breakLevel < 2) 
                                __state = 34;
                            __tothrow = __pending;
                            break;
                        }
                        //* (36)     #reasoning method
                        case 34: 
                        {
                            if (__pending == null) 
                                __state = PASSED_STATE;
                            __tothrow = __pending;
                            break;
                        }
                    }
                }
                catch (java.lang.Throwable e) {
                    handleException(e,__exMap_body);
                }
            }
             while (!agent.changing_focus);
            return CONTINUE;
        }
        
        public java.lang.String methodName()
        {
            return "body";
        }
        
        __bodyFSM()
        {
        }
        
        public java.lang.String stateInfo()
        {
            int n = __curstate;
            java.lang.String file = __tt__body[0];
            java.lang.String method = __tt__body[1];
            if (n < 0) 
                n = -n;
            n -= (10 - 2);
            java.lang.String line = (n < 2)?"??":__tt__body[n];
            return file + ":" + line + " " + method + " [" + __curstate + "]";
        }
        
        public java.lang.Object genObject(int __index)
        {
            switch (__index) {
            }
            aos.jack.jak.core.Jak.error("illegal Object Construction");
            return null;
        }
        
        public aos.jack.jak.cursor.Cursor genCursor(int __index)
            throws java.lang.Exception
        {
            switch (__index) {
            }
            aos.jack.jak.core.Jak.error("illegal Cursor Construction");
            return null;
        }
        
        public aos.jack.jak.fsm.FSM genFSM(int __index)
            throws java.lang.Exception
        {
            switch (__index) {
            }
            aos.jack.jak.core.Jak.error("illegal FSM Construction");
            return null;
        }
        
        public boolean testCondition(int __index)
            throws java.lang.Exception
        {
            switch (__index) {
            }
            aos.jack.jak.core.Jak.error("illegal test Construction");
            return false;
        }
        
        public aos.jack.jak.plan.Plan getPlan()
        {
            return NeonAffect.AddEmotionPlan.this;
        }
        
        protected aos.jack.jak.fsm.FSM fail()
        {
            return getPlan().fail();
        }
        
        protected aos.jack.jak.fsm.FSM pass()
        {
            return getPlan().pass();
        }
        
        public void enter()
        {
            __trace = agent.trace("NeonAffect.AddEmotionPlan.body");
        }
        
        public java.lang.Object getVariable(int n)
        {
            switch (n) {
                case 0: 
                {
                    return aos.util.ToObject.box(__local__24_0);
                }
                case 1: 
                {
                    return aos.util.ToObject.box(__local__24_1);
                }
                case 2: 
                {
                    return aos.util.ToObject.box(__local__24_2);
                }
                case 3: 
                {
                    return aos.util.ToObject.box(__local__24_3);
                }
                case 4: 
                {
                    return aos.util.ToObject.box(__local__24_4);
                }
                case 5: 
                {
                    return aos.util.ToObject.box(__local__24_5);
                }
                case 6: 
                {
                    return aos.util.ToObject.box(__local__24_6);
                }
                default: 
                {
                    throw new java.lang.IndexOutOfBoundsException("Reasoning Method " + methodName() + " does not have variable number " + n);
                }
            }
        }
        
        public java.lang.String[] variableNames()
        {
            return __fsmVariableNames_body;
        }
        
        public java.lang.String[] variableTypes()
        {
            return __fsmTypes_body;
        }
        
        public java.lang.String[] variableLocalNames()
        {
            return __fsmLocalNames_body;
        }
        
    }
}
