/*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*
  This code is generated by JAC version 5.6 by
  Agent Oriented Software. http://www.agent-software.com.au

    DO NOT ALTER THIS CODE AND DO NOT REMOVE THIS COMMENT
 *=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*/
package NeonAffect;
import aos.jack.jak.plan.Plan;
import aos.jack.jak.plan.PlanFSM;
import aos.jack.jak.plan.ExMap;
import aos.jack.jak.agent.NameSpace;
import aos.jack.jak.event.Event;
import aos.jack.jak.task.Task;
import aos.jack.jak.core.Generator;
import aos.jack.jak.logic.Signature;
import aos.jack.util.thread.Semaphore;
import java.lang.Object;
import aos.jack.jak.cursor.Cursor;
import aos.jack.jak.fsm.FSM;
import aos.jack.jak.core.Jak;

/**
 * 
 */

public class InitReservoirPlan extends aos.jack.jak.plan.Plan {
    private static java.lang.Class __exClass_0 = aos.jack.jak.fsm.FSM.loadClass("java.lang.Exception");
    public NeonAffect.InitReservoirEvent ire;
    public NeonAffect.NeonAffectAgent enc;
    public aos.jack.util.thread.Semaphore mutex;
    public NeonAffect.PlanContextName planContextName;
    private static aos.jack.jak.plan.ExMap[] __exMap_body = {
            new aos.jack.jak.plan.ExMap(10,10,11,__exClass_0),
            new aos.jack.jak.plan.ExMap(10,12,13,null)};
    private static java.lang.String[] __tt__body = {
            "NeonAffect/InitReservoirPlan.plan",
            "body",
            "38",
            "40",
            "42",
            "46",
            "45",
            "33"};
    private final static java.lang.String[] __planVariableNames = {
            "ire",
            "enc",
            "mutex",
            "planContextName"};
    private final static java.lang.String[] __planVariableTypes = {
            "InitReservoirEvent",
            "NeonAffect.NeonAffectAgent",
            "aos.jack.util.thread.Semaphore",
            "PlanContextName"};
    private final static java.lang.String[] __reasoningMethods = {
            "body"};
    private final static java.lang.String[] __fsmVariableNames_body = {
            "v",
            "e"};
    private final static java.lang.String[] __fsmTypes_body = {
            "double",
            "Exception"};
    private final static java.lang.String[] __fsmLocalNames_body = {
            "__local__1384_0",
            "__local__1384_1"};
    static boolean relevant(NeonAffect.InitReservoirEvent ire)
    {
        return true;
    }
    
    public java.lang.String getDocumentation()
    {
        return "/**\n * \n */\n";
    }
    
    public InitReservoirPlan()
    {
    }
    
    private InitReservoirPlan(aos.jack.jak.task.Task __t, NeonAffect.InitReservoirPlan __env)
    {
        __agent = __env.__agent;
        __ns = __env.__ns;
        __planTask = __t;
        __logic = __t.logic;
        ire = __env.ire;
        enc = (NeonAffect.NeonAffectAgent) __ns.getIF(NeonAffect.NeonAffectAgent.class);
        mutex = __env.mutex;
        planContextName = __env.planContextName;
    }
    
    public boolean init_sentinel(aos.jack.jak.agent.NameSpace __a)
    {
        ire = (NeonAffect.InitReservoirEvent) __a.findEvent("NeonAffect.InitReservoirEvent");
        if (ire == null) {
            warning("InitReservoirEvent ire: is not found in the capability/agent this plan comes from");
            return false;
        }
        mutex = (aos.jack.util.thread.Semaphore) lookupNamedObject("mutex","aos.jack.util.thread.Semaphore",0);
        if (mutex == null) {
            warning("Semaphore mutex: is not found in the capability/agent this plan comes from");
            return false;
        }
        planContextName = (NeonAffect.PlanContextName) lookupNamedObject("planContextName","NeonAffect.PlanContextName",0);
        if (planContextName == null) {
            warning("PlanContextName planContextName: is not found in the capability/agent this plan comes from");
            return false;
        }
        return true;
    }
    
    public aos.jack.jak.plan.Plan freeze()
    {
        return this;
    }
    
    public aos.jack.jak.plan.Plan unfreeze()
    {
        return this;
    }
    
    public java.lang.Object genObject(int __index)
    {
        switch (__index) {
        }
        aos.jack.jak.core.Jak.error("illegal Object Construction");
        return null;
    }
    
    public aos.jack.jak.cursor.Cursor genCursor(int __index)
        throws java.lang.Exception
    {
        switch (__index) {
        }
        aos.jack.jak.core.Jak.error("illegal Cursor Construction");
        return null;
    }
    
    public aos.jack.jak.fsm.FSM genFSM(int __index)
        throws java.lang.Exception
    {
        switch (__index) {
        }
        aos.jack.jak.core.Jak.error("illegal FSM Construction");
        return null;
    }
    
    public boolean testCondition(int __index)
        throws java.lang.Exception
    {
        switch (__index) {
        }
        aos.jack.jak.core.Jak.error("illegal test Construction");
        return false;
    }
    
    public aos.jack.jak.plan.PlanFSM body()
    {
        return new NeonAffect.InitReservoirPlan.__bodyFSM();
    }
    
    private InitReservoirPlan(NeonAffect.InitReservoirEvent __ev, aos.jack.jak.task.Task __t, NeonAffect.InitReservoirPlan __env)
    {
        this(__t,__env);
        this.ire = __ev;
    }
    
    protected aos.jack.jak.logic.Signature eventSignature(int __log)
    {
        return ire.getSignature(__log);
    }
    
    public java.lang.String handledEvent()
    {
        return "NeonAffect.InitReservoirEvent";
    }
    
    public boolean __relevant(aos.jack.jak.event.Event __e)
    {
        return __ns.isEnabled() && relevant(((NeonAffect.InitReservoirEvent) __e));
    }
    
    public aos.jack.jak.plan.Plan createPlan(aos.jack.jak.event.Event __e, aos.jack.jak.task.Task __t)
    {
        if (!(__e instanceof NeonAffect.InitReservoirEvent)) 
            return null;
        NeonAffect.InitReservoirEvent __e1 = (NeonAffect.InitReservoirEvent) __e;
        return new NeonAffect.InitReservoirPlan(__e1,__t,this);
    }
    
    public java.lang.String[] variableNames()
    {
        return __planVariableNames;
    }
    
    public java.lang.String[] variableTypes()
    {
        return __planVariableTypes;
    }
    
    public java.lang.Object getVariable(int n)
    {
        switch (n) {
            case 0: 
            {
                return aos.util.ToObject.box(ire);
            }
            case 1: 
            {
                return aos.util.ToObject.box(enc);
            }
            case 2: 
            {
                return aos.util.ToObject.box(mutex);
            }
            case 3: 
            {
                return aos.util.ToObject.box(planContextName);
            }
            default: 
            {
                throw new java.lang.IndexOutOfBoundsException("Plan " + this + " does not have variable number " + n);
            }
        }
    }
    
    public java.lang.String[] reasoningMethods()
    {
        return mergeReasoningMethods(__reasoningMethods,super.reasoningMethods());
    }
    
    public aos.jack.jak.cursor.Cursor context()
    {
        try {
            return (((true)?aos.jack.jak.cursor.Cursor.trueCursor:aos.jack.jak.cursor.Cursor.falseCursor));
        }
        catch (java.lang.Exception e) {
            e.printStackTrace();
            return aos.jack.jak.cursor.Cursor.falseCursor;
        }
    }
    
    class __bodyFSM extends aos.jack.jak.plan.PlanFSM implements aos.jack.jak.core.Generator {
        double __local__1384_0;
        java.lang.Exception __local__1384_1;
        private int __breakLevel = 0;
        public int run(int __status)
            throws java.lang.Throwable
        {
            do {
                try {
                    if (__tothrow != null) 
                        throw __tothrow;
                    if ((aos.jack.jak.core.Jak.debugging & aos.jack.jak.core.Jak.LOG_PLANS) != 0) 
                        aos.util.logging.LogMsg.log(this,aos.jack.jak.core.Jak.LOG_PLANS,__task + "-InitReservoirPlan.body:" + java.lang.Integer.toString(__state));
                    if (__task.nsteps > 0) {
                        __task.nsteps-- ;
                        if (__task.nsteps == 0) 
                            agent.changeFocus();
                    }
                    if (__state < 10) {
                        __status = super.stdrun(NeonAffect.InitReservoirPlan.this,__status);
                        if (__status != CONTINUE || agent.changing_focus) 
                            return __status;
                        continue;
                    }
                    __curstate = __state;
                    switch (__state) {
                        default: 
                        {
                            aos.jack.jak.core.Jak.error("InitReservoirPlan.body: Illegal state");
                            return FAILED_STATE;
                        }
                        //* (38)             double v = enc.GetReservoirValue();
                        case 10: 
                        {
                            __breakLevel = 2;
                            __local__1384_0 = enc.GetReservoirValue();
                            __state = 13;
                            break;
                        }
                        //* (40)         catch (Exception e)
                        case 11: 
                        {
                            __breakLevel = 2;
                            __state = 12;
                            __local__1384_1 = (java.lang.Exception) __current;
                            break;
                        }
                        //* (42)             e.printStackTrace();            
                        case 12: 
                        {
                            __breakLevel = 4;
                            __state = 13;
                            __local__1384_1.printStackTrace();
                            break;
                        }
                        //* (46)             mutex.signal();
                        case 13: 
                        {
                            __breakLevel = 2;
                            __state = 14;
                            mutex.signal();
                            break;
                        }
                        //* (45)         {
                        case 14: 
                        {
                            __state = 15;
                            if (__breakLevel < 2) 
                                __state = 15;
                            __tothrow = __pending;
                            break;
                        }
                        //* (33)     #reasoning method
                        case 15: 
                        {
                            if (__pending == null) 
                                __state = PASSED_STATE;
                            __tothrow = __pending;
                            break;
                        }
                    }
                }
                catch (java.lang.Throwable e) {
                    handleException(e,__exMap_body);
                }
            }
             while (!agent.changing_focus);
            return CONTINUE;
        }
        
        public java.lang.String methodName()
        {
            return "body";
        }
        
        __bodyFSM()
        {
        }
        
        public java.lang.String stateInfo()
        {
            int n = __curstate;
            java.lang.String file = __tt__body[0];
            java.lang.String method = __tt__body[1];
            if (n < 0) 
                n = -n;
            n -= (10 - 2);
            java.lang.String line = (n < 2)?"??":__tt__body[n];
            return file + ":" + line + " " + method + " [" + __curstate + "]";
        }
        
        public java.lang.Object genObject(int __index)
        {
            switch (__index) {
            }
            aos.jack.jak.core.Jak.error("illegal Object Construction");
            return null;
        }
        
        public aos.jack.jak.cursor.Cursor genCursor(int __index)
            throws java.lang.Exception
        {
            switch (__index) {
            }
            aos.jack.jak.core.Jak.error("illegal Cursor Construction");
            return null;
        }
        
        public aos.jack.jak.fsm.FSM genFSM(int __index)
            throws java.lang.Exception
        {
            switch (__index) {
            }
            aos.jack.jak.core.Jak.error("illegal FSM Construction");
            return null;
        }
        
        public boolean testCondition(int __index)
            throws java.lang.Exception
        {
            switch (__index) {
            }
            aos.jack.jak.core.Jak.error("illegal test Construction");
            return false;
        }
        
        public aos.jack.jak.plan.Plan getPlan()
        {
            return NeonAffect.InitReservoirPlan.this;
        }
        
        protected aos.jack.jak.fsm.FSM fail()
        {
            return getPlan().fail();
        }
        
        protected aos.jack.jak.fsm.FSM pass()
        {
            return getPlan().pass();
        }
        
        public void enter()
        {
            __trace = agent.trace("NeonAffect.InitReservoirPlan.body");
        }
        
        public java.lang.Object getVariable(int n)
        {
            switch (n) {
                case 0: 
                {
                    return aos.util.ToObject.box(__local__1384_0);
                }
                case 1: 
                {
                    return aos.util.ToObject.box(__local__1384_1);
                }
                default: 
                {
                    throw new java.lang.IndexOutOfBoundsException("Reasoning Method " + methodName() + " does not have variable number " + n);
                }
            }
        }
        
        public java.lang.String[] variableNames()
        {
            return __fsmVariableNames_body;
        }
        
        public java.lang.String[] variableTypes()
        {
            return __fsmTypes_body;
        }
        
        public java.lang.String[] variableLocalNames()
        {
            return __fsmLocalNames_body;
        }
        
    }
}
