/*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*
  This code is generated by JAC version 5.6 by
  Agent Oriented Software. http://www.agent-software.com.au

    DO NOT ALTER THIS CODE AND DO NOT REMOVE THIS COMMENT
 *=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*/
package NeonAffect;
import aos.jack.jak.plan.Plan;
import aos.jack.jak.plan.PlanFSM;
import aos.jack.jak.plan.ExMap;
import aos.jack.jak.agent.NameSpace;
import aos.jack.jak.event.Event;
import aos.jack.jak.task.Task;
import aos.jack.jak.core.Generator;
import aos.jack.jak.logic.Signature;
import aos.jack.util.thread.Semaphore;
import CoJACKConfigParserXML.parser;
import java.lang.Object;
import aos.jack.jak.cursor.Cursor;
import aos.jack.jak.fsm.FSM;
import aos.jack.jak.core.Jak;

/**
 * 
 */

public class SetPersonalityTypePlan extends aos.jack.jak.plan.Plan {
    private final java.lang.String strPath = "D:\\projects\\NeonAffect\\data\\cojack_cognitive.xml";
    private static java.lang.Class __exClass_0 = aos.jack.jak.fsm.FSM.loadClass("java.lang.Exception");
    public NeonAffect.SetPersonalityTypeEvent ev1;
    public NeonAffect.NeonAffectAgent enc;
    public NeonAffect.PersonalityType personalityType;
    public aos.jack.util.thread.Semaphore mutex;
    public NeonAffect.NA_Debug debug;
    private static aos.jack.jak.plan.ExMap[] __exMap_body = {
            new aos.jack.jak.plan.ExMap(10,21,22,__exClass_0),
            new aos.jack.jak.plan.ExMap(10,23,24,null)};
    private static java.lang.String[] __tt__body = {
            "NeonAffect/SetPersonalityTypePlan.plan",
            "body",
            "46",
            "47",
            "49",
            "51",
            "53",
            "56",
            "58",
            "60",
            "63",
            "65",
            "67",
            "69",
            "72",
            "74",
            "78",
            "77",
            "41"};
    private final static java.lang.String[] __planVariableNames = {
            "strPath",
            "ev1",
            "enc",
            "personalityType",
            "mutex",
            "debug"};
    private final static java.lang.String[] __planVariableTypes = {
            "String",
            "SetPersonalityTypeEvent",
            "NeonAffect.NeonAffectAgent",
            "NeonAffect.PersonalityType",
            "aos.jack.util.thread.Semaphore",
            "NeonAffect.NA_Debug"};
    private final static java.lang.String[] __reasoningMethods = {
            "body"};
    private final static java.lang.String[] __fsmVariableNames_body = {
            "$debug",
            "bDebug",
            "strPersonalityType",
            "e"};
    private final static java.lang.String[] __fsmTypes_body = {
            "logical boolean",
            "boolean",
            "String",
            "Exception"};
    private final static java.lang.String[] __fsmLocalNames_body = {
            "__local__2458_0",
            "__local__2458_1",
            "__local__2458_2",
            "__local__2458_3"};
    static boolean relevant(NeonAffect.SetPersonalityTypeEvent ev1)
    {
        return true;
    }
    
    public java.lang.String getDocumentation()
    {
        return "/**\n * \n */\n";
    }
    
    public SetPersonalityTypePlan()
    {
    }
    
    private SetPersonalityTypePlan(aos.jack.jak.task.Task __t, NeonAffect.SetPersonalityTypePlan __env)
    {
        __agent = __env.__agent;
        __ns = __env.__ns;
        __planTask = __t;
        __logic = __t.logic;
        ev1 = __env.ev1;
        enc = (NeonAffect.NeonAffectAgent) __ns.getIF(NeonAffect.NeonAffectAgent.class);
        personalityType = __env.personalityType;
        mutex = __env.mutex;
        debug = __env.debug;
    }
    
    public boolean init_sentinel(aos.jack.jak.agent.NameSpace __a)
    {
        ev1 = (NeonAffect.SetPersonalityTypeEvent) __a.findEvent("NeonAffect.SetPersonalityTypeEvent");
        if (ev1 == null) {
            warning("SetPersonalityTypeEvent ev1: is not found in the capability/agent this plan comes from");
            return false;
        }
        personalityType = (NeonAffect.PersonalityType) lookupNamedObject("personalityType","NeonAffect.PersonalityType",0);
        if (personalityType == null) {
            warning("PersonalityType personalityType: is not found in the capability/agent this plan comes from");
            return false;
        }
        mutex = (aos.jack.util.thread.Semaphore) lookupNamedObject("mutex","aos.jack.util.thread.Semaphore",0);
        if (mutex == null) {
            warning("Semaphore mutex: is not found in the capability/agent this plan comes from");
            return false;
        }
        debug = (NeonAffect.NA_Debug) lookupNamedObject("debug","NeonAffect.NA_Debug",0);
        if (debug == null) {
            warning("NA_Debug debug: is not found in the capability/agent this plan comes from");
            return false;
        }
        return true;
    }
    
    public aos.jack.jak.plan.Plan freeze()
    {
        return this;
    }
    
    public aos.jack.jak.plan.Plan unfreeze()
    {
        return this;
    }
    
    public java.lang.Object genObject(int __index)
    {
        switch (__index) {
        }
        aos.jack.jak.core.Jak.error("illegal Object Construction");
        return null;
    }
    
    public aos.jack.jak.cursor.Cursor genCursor(int __index)
        throws java.lang.Exception
    {
        switch (__index) {
        }
        aos.jack.jak.core.Jak.error("illegal Cursor Construction");
        return null;
    }
    
    public aos.jack.jak.fsm.FSM genFSM(int __index)
        throws java.lang.Exception
    {
        switch (__index) {
        }
        aos.jack.jak.core.Jak.error("illegal FSM Construction");
        return null;
    }
    
    public boolean testCondition(int __index)
        throws java.lang.Exception
    {
        switch (__index) {
        }
        aos.jack.jak.core.Jak.error("illegal test Construction");
        return false;
    }
    
    public aos.jack.jak.plan.PlanFSM body()
    {
        return new NeonAffect.SetPersonalityTypePlan.__bodyFSM();
    }
    
    private SetPersonalityTypePlan(NeonAffect.SetPersonalityTypeEvent __ev, aos.jack.jak.task.Task __t, NeonAffect.SetPersonalityTypePlan __env)
    {
        this(__t,__env);
        this.ev1 = __ev;
    }
    
    protected aos.jack.jak.logic.Signature eventSignature(int __log)
    {
        return ev1.getSignature(__log);
    }
    
    public java.lang.String handledEvent()
    {
        return "NeonAffect.SetPersonalityTypeEvent";
    }
    
    public boolean __relevant(aos.jack.jak.event.Event __e)
    {
        return __ns.isEnabled() && relevant(((NeonAffect.SetPersonalityTypeEvent) __e));
    }
    
    public aos.jack.jak.plan.Plan createPlan(aos.jack.jak.event.Event __e, aos.jack.jak.task.Task __t)
    {
        if (!(__e instanceof NeonAffect.SetPersonalityTypeEvent)) 
            return null;
        NeonAffect.SetPersonalityTypeEvent __e1 = (NeonAffect.SetPersonalityTypeEvent) __e;
        return new NeonAffect.SetPersonalityTypePlan(__e1,__t,this);
    }
    
    public java.lang.String[] variableNames()
    {
        return __planVariableNames;
    }
    
    public java.lang.String[] variableTypes()
    {
        return __planVariableTypes;
    }
    
    public java.lang.Object getVariable(int n)
    {
        switch (n) {
            case 0: 
            {
                return aos.util.ToObject.box(strPath);
            }
            case 1: 
            {
                return aos.util.ToObject.box(ev1);
            }
            case 2: 
            {
                return aos.util.ToObject.box(enc);
            }
            case 3: 
            {
                return aos.util.ToObject.box(personalityType);
            }
            case 4: 
            {
                return aos.util.ToObject.box(mutex);
            }
            case 5: 
            {
                return aos.util.ToObject.box(debug);
            }
            default: 
            {
                throw new java.lang.IndexOutOfBoundsException("Plan " + this + " does not have variable number " + n);
            }
        }
    }
    
    public java.lang.String[] reasoningMethods()
    {
        return mergeReasoningMethods(__reasoningMethods,super.reasoningMethods());
    }
    
    public aos.jack.jak.cursor.Cursor context()
    {
        try {
            return (((true)?aos.jack.jak.cursor.Cursor.trueCursor:aos.jack.jak.cursor.Cursor.falseCursor));
        }
        catch (java.lang.Exception e) {
            e.printStackTrace();
            return aos.jack.jak.cursor.Cursor.falseCursor;
        }
    }
    
    class __bodyFSM extends aos.jack.jak.plan.PlanFSM implements aos.jack.jak.core.Generator {
        aos.jack.jak.logic.BooleanVariable __local__2458_0;
        boolean __local__2458_1;
        java.lang.String __local__2458_2;
        java.lang.Exception __local__2458_3;
        private int __breakLevel = 0;
        public int run(int __status)
            throws java.lang.Throwable
        {
            do {
                try {
                    if (__tothrow != null) 
                        throw __tothrow;
                    if ((aos.jack.jak.core.Jak.debugging & aos.jack.jak.core.Jak.LOG_PLANS) != 0) 
                        aos.util.logging.LogMsg.log(this,aos.jack.jak.core.Jak.LOG_PLANS,__task + "-SetPersonalityTypePlan.body:" + java.lang.Integer.toString(__state));
                    if (__task.nsteps > 0) {
                        __task.nsteps-- ;
                        if (__task.nsteps == 0) 
                            agent.changeFocus();
                    }
                    if (__state < 10) {
                        __status = super.stdrun(NeonAffect.SetPersonalityTypePlan.this,__status);
                        if (__status != CONTINUE || agent.changing_focus) 
                            return __status;
                        continue;
                    }
                    __curstate = __state;
                    switch (__state) {
                        default: 
                        {
                            aos.jack.jak.core.Jak.error("SetPersonalityTypePlan.body: Illegal state");
                            return FAILED_STATE;
                        }
                        //* (46)             logical boolean $debug;
                        case 10: 
                        {
                            __breakLevel = 2;
                            __local__2458_0 = (aos.jack.jak.logic.BooleanVariable) __logic.new_variable(java.lang.Boolean.TYPE);
                            __state = 11;
                            break;
                        }
                        //* (47)             debug.get($debug).next();
                        case 11: 
                        {
                            if (debug.get(__local__2458_0).next()) 
                                __state = 12;
                             else 
                                throw planfailed;
                            break;
                        }
                        //* (49)             boolean bDebug = $debug.as_boolean();
                        case 12: 
                        {
                            __local__2458_1 = __local__2458_0.as_boolean();
                            __state = 13;
                            break;
                        }
                        //* (51)             if (bDebug)
                        case 13: 
                        {
                            if (__local__2458_1) 
                                __state = 14;
                             else 
                                __state = 15;
                            break;
                        }
                        //* (53)                 System.out.println("Inside SetPersonalityPlan.");
                        case 14: 
                        {
                            __breakLevel = 4;
                            __state = 15;
                            java.lang.System.out.println("Inside SetPersonalityPlan.");
                            break;
                        }
                        //* (56)             String strPersonalityType = new parser(strPath).GetMBTIPersonalityType("NeonAffectGroup");
                        case 15: 
                        {
                            __local__2458_2 = new CoJACKConfigParserXML.parser(strPath).GetMBTIPersonalityType("NeonAffectGroup");
                            __state = 16;
                            break;
                        }
                        //* (58)             if (bDebug)
                        case 16: 
                        {
                            if (__local__2458_1) 
                                __state = 17;
                             else 
                                __state = 18;
                            break;
                        }
                        //* (60)                 System.out.println("SetPersonalityTypePlan: setting type: [" + strPersonalityType + "]");
                        case 17: 
                        {
                            __breakLevel = 4;
                            __state = 18;
                            java.lang.System.out.println("SetPersonalityTypePlan: setting type: [" + __local__2458_2 + "]");
                            break;
                        }
                        //* (63)             personalityType.add(0, strPersonalityType);
                        case 18: 
                        {
                            __state = 19;
                            personalityType.add(0,__local__2458_2);
                            break;
                        }
                        //* (65)             enc.SetPersonalityType(strPersonalityType);
                        case 19: 
                        {
                            __state = 20;
                            enc.SetPersonalityType(__local__2458_2);
                            break;
                        }
                        //* (67)             if (bDebug)
                        case 20: 
                        {
                            if (__local__2458_1) 
                                __state = 21;
                             else 
                                __state = 24;
                            break;
                        }
                        //* (69)                 System.out.println("Leaving SetPersonalityTypePlan.");
                        case 21: 
                        {
                            __breakLevel = 4;
                            __state = 24;
                            java.lang.System.out.println("Leaving SetPersonalityTypePlan.");
                            break;
                        }
                        //* (72)         catch (Exception e)
                        case 22: 
                        {
                            __breakLevel = 2;
                            __state = 23;
                            __local__2458_3 = (java.lang.Exception) __current;
                            break;
                        }
                        //* (74)             e.printStackTrace();                
                        case 23: 
                        {
                            __breakLevel = 4;
                            __state = 24;
                            __local__2458_3.printStackTrace();
                            break;
                        }
                        //* (78)             mutex.signal();  
                        case 24: 
                        {
                            __breakLevel = 2;
                            __state = 25;
                            mutex.signal();
                            break;
                        }
                        //* (77)         {
                        case 25: 
                        {
                            __state = 26;
                            if (__breakLevel < 2) 
                                __state = 26;
                            __tothrow = __pending;
                            break;
                        }
                        //* (41)     #reasoning method
                        case 26: 
                        {
                            if (__pending == null) 
                                __state = PASSED_STATE;
                            __tothrow = __pending;
                            break;
                        }
                    }
                }
                catch (java.lang.Throwable e) {
                    handleException(e,__exMap_body);
                }
            }
             while (!agent.changing_focus);
            return CONTINUE;
        }
        
        public java.lang.String methodName()
        {
            return "body";
        }
        
        __bodyFSM()
        {
        }
        
        public java.lang.String stateInfo()
        {
            int n = __curstate;
            java.lang.String file = __tt__body[0];
            java.lang.String method = __tt__body[1];
            if (n < 0) 
                n = -n;
            n -= (10 - 2);
            java.lang.String line = (n < 2)?"??":__tt__body[n];
            return file + ":" + line + " " + method + " [" + __curstate + "]";
        }
        
        public java.lang.Object genObject(int __index)
        {
            switch (__index) {
            }
            aos.jack.jak.core.Jak.error("illegal Object Construction");
            return null;
        }
        
        public aos.jack.jak.cursor.Cursor genCursor(int __index)
            throws java.lang.Exception
        {
            switch (__index) {
            }
            aos.jack.jak.core.Jak.error("illegal Cursor Construction");
            return null;
        }
        
        public aos.jack.jak.fsm.FSM genFSM(int __index)
            throws java.lang.Exception
        {
            switch (__index) {
            }
            aos.jack.jak.core.Jak.error("illegal FSM Construction");
            return null;
        }
        
        public boolean testCondition(int __index)
            throws java.lang.Exception
        {
            switch (__index) {
            }
            aos.jack.jak.core.Jak.error("illegal test Construction");
            return false;
        }
        
        public aos.jack.jak.plan.Plan getPlan()
        {
            return NeonAffect.SetPersonalityTypePlan.this;
        }
        
        protected aos.jack.jak.fsm.FSM fail()
        {
            return getPlan().fail();
        }
        
        protected aos.jack.jak.fsm.FSM pass()
        {
            return getPlan().pass();
        }
        
        public void enter()
        {
            __trace = agent.trace("NeonAffect.SetPersonalityTypePlan.body");
        }
        
        public java.lang.Object getVariable(int n)
        {
            switch (n) {
                case 0: 
                {
                    return aos.util.ToObject.box(__local__2458_0);
                }
                case 1: 
                {
                    return aos.util.ToObject.box(__local__2458_1);
                }
                case 2: 
                {
                    return aos.util.ToObject.box(__local__2458_2);
                }
                case 3: 
                {
                    return aos.util.ToObject.box(__local__2458_3);
                }
                default: 
                {
                    throw new java.lang.IndexOutOfBoundsException("Reasoning Method " + methodName() + " does not have variable number " + n);
                }
            }
        }
        
        public java.lang.String[] variableNames()
        {
            return __fsmVariableNames_body;
        }
        
        public java.lang.String[] variableTypes()
        {
            return __fsmTypes_body;
        }
        
        public java.lang.String[] variableLocalNames()
        {
            return __fsmLocalNames_body;
        }
        
    }
}
