/*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*
  This code is generated by JAC version 5.6 by
  Agent Oriented Software. http://www.agent-software.com.au

    DO NOT ALTER THIS CODE AND DO NOT REMOVE THIS COMMENT
 *=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*/
package NeonAffect;
import aos.jack.jak.agent.Capability;
import aos.jack.jak.agent.NameSpace;
import aos.jack.jak.agent.Agent;
import aos.jack.util.thread.Semaphore;

/**
 * 
 */

public class GriefAffectCapability extends aos.jack.jak.agent.Capability {
    public NeonAffect.PlanContextName planContextName;
    public NeonAffect.Behavior behaviorName;
    public aos.jack.util.thread.Semaphore mutex;
    public aos.jack.util.thread.Semaphore mutex2;
    public NeonAffect.NA_Debug debug;
    public NeonAffect.ContextEvent ce;
    public java.lang.String getDocumentation()
    {
        return "/**\n * \n */\n";
    }
    
    public void __init1()
    {
        setNamedCreator("planContextName","NeonAffect.PlanContextName",new aos.jack.jak.agent.DataCreator(false){
            public java.lang.Object create()
            {
                return __named_data_planContextName();
            }
            
        },true);
        setNamedCreator("behaviorName","NeonAffect.Behavior",new aos.jack.jak.agent.DataCreator(false){
            public java.lang.Object create()
            {
                return __named_data_behaviorName();
            }
            
        },true);
        setNamedCreator("mutex","aos.jack.util.thread.Semaphore",new aos.jack.jak.agent.DataCreator(false){
            public java.lang.Object create()
            {
                return __named_data_mutex();
            }
            
        },true);
        setNamedCreator("mutex2","aos.jack.util.thread.Semaphore",new aos.jack.jak.agent.DataCreator(false){
            public java.lang.Object create()
            {
                return __named_data_mutex2();
            }
            
        },true);
        setNamedCreator("debug","NeonAffect.NA_Debug",new aos.jack.jak.agent.DataCreator(false){
            public java.lang.Object create()
            {
                return __named_data_debug();
            }
            
        },true);
    }
    
    public void __init2()
    {
        ce = (NeonAffect.ContextEvent) findEvent("NeonAffect.ContextEvent");
        planContextName = (NeonAffect.PlanContextName) getNamedObject("planContextName","NeonAffect.PlanContextName");
        behaviorName = (NeonAffect.Behavior) getNamedObject("behaviorName","NeonAffect.Behavior");
        mutex = (aos.jack.util.thread.Semaphore) getNamedObject("mutex","aos.jack.util.thread.Semaphore");
        mutex2 = (aos.jack.util.thread.Semaphore) getNamedObject("mutex2","aos.jack.util.thread.Semaphore");
        debug = (NeonAffect.NA_Debug) getNamedObject("debug","NeonAffect.NA_Debug");
        autorun();
    }
    
    synchronized public void __init_desc()
    {
        externals.put("debug","debug");
        externals.put("mutex2","mutex2");
        externals.put("mutex","mutex");
        externals.put("behaviorName","behaviorName");
        externals.put("planContextName","planContextName");
        externals.put("NeonAffect.SetPlanContextEvent","NeonAffect.SetPlanContextEvent");
        externals.put("NeonAffect.Level6NegAffectEvent","NeonAffect.Level6NegAffectEvent");
        addEvent("NeonAffect.Level6NegAffectEvent",aos.jack.jak.agent.Agent.HANDLED_EVENT);
        addEvent("NeonAffect.SetPlanContextEvent",aos.jack.jak.agent.Agent.HANDLED_EVENT);
        addEvent("NeonAffect.ContextEvent",aos.jack.jak.agent.Agent.SENT_EVENT);
        addPlan("NeonAffect.WeakMovementsPlan",0);
        addPlan("NeonAffect.SlackFacePlan",0);
        addPlan("NeonAffect.LossOfBreathPlan",0);
        addPlan("NeonAffect.LashingOutGriefPlan",0);
        addPlan("NeonAffect.TremblingLipsPlan",0);
        addPlan("NeonAffect.IsolationGriefPlan",0);
        addPlan("NeonAffect.WeakVoiceSpeakingPlan",0);
        addPlan("NeonAffect.LosingTrackConversationPlan",0);
        addPlan("NeonAffect.WeakPostureGriefPlan",0);
        addPlan("NeonAffect.CryingGriefPlan",0);
        addPlan("NeonAffect.LosingTrackOfTimeGriefPlan",0);
        addPlan("NeonAffect.NoiseSensitivityGriefPlan",0);
        addPlan("NeonAffect.RedEyesGriefPlan",0);
        addPlan("NeonAffect.CondescendingPlan",0);
        addPlan("NeonAffect.LonelinessPlan",0);
        addPlan("NeonAffect.LackOfMotivationPlan",0);
        addPlan("NeonAffect.ParanoiaGriefPlan",0);
        addPlan("NeonAffect.OverdoingItPlan",0);
        addPlan("NeonAffect.SetPlanContextGriefPlan",0);
    }
    
    public GriefAffectCapability(aos.jack.jak.agent.NameSpace outer)
    {
        super(outer);
    }
    
    synchronized public void __bindNames()
    {
        super.__bindNames();
        __bindToPlan("NeonAffect.WeakMovementsPlan");
        __bindToPlan("NeonAffect.SlackFacePlan");
        __bindToPlan("NeonAffect.LossOfBreathPlan");
        __bindToPlan("NeonAffect.LashingOutGriefPlan");
        __bindToPlan("NeonAffect.TremblingLipsPlan");
        __bindToPlan("NeonAffect.IsolationGriefPlan");
        __bindToPlan("NeonAffect.WeakVoiceSpeakingPlan");
        __bindToPlan("NeonAffect.LosingTrackConversationPlan");
        __bindToPlan("NeonAffect.WeakPostureGriefPlan");
        __bindToPlan("NeonAffect.CryingGriefPlan");
        __bindToPlan("NeonAffect.LosingTrackOfTimeGriefPlan");
        __bindToPlan("NeonAffect.NoiseSensitivityGriefPlan");
        __bindToPlan("NeonAffect.RedEyesGriefPlan");
        __bindToPlan("NeonAffect.CondescendingPlan");
        __bindToPlan("NeonAffect.LonelinessPlan");
        __bindToPlan("NeonAffect.LackOfMotivationPlan");
        __bindToPlan("NeonAffect.ParanoiaGriefPlan");
        __bindToPlan("NeonAffect.OverdoingItPlan");
        __bindToPlan("NeonAffect.SetPlanContextGriefPlan");
    }
    
    private NeonAffect.PlanContextName __named_data_planContextName()
    {
        planContextName = (NeonAffect.PlanContextName) getNamedObject("planContextName","NeonAffect.PlanContextName");
        return planContextName;
    }
    
    private NeonAffect.Behavior __named_data_behaviorName()
    {
        behaviorName = (NeonAffect.Behavior) getNamedObject("behaviorName","NeonAffect.Behavior");
        return behaviorName;
    }
    
    private aos.jack.util.thread.Semaphore __named_data_mutex()
    {
        mutex = (aos.jack.util.thread.Semaphore) getNamedObject("mutex","aos.jack.util.thread.Semaphore");
        return mutex;
    }
    
    private aos.jack.util.thread.Semaphore __named_data_mutex2()
    {
        mutex2 = (aos.jack.util.thread.Semaphore) getNamedObject("mutex2","aos.jack.util.thread.Semaphore");
        return mutex2;
    }
    
    private NeonAffect.NA_Debug __named_data_debug()
    {
        debug = (NeonAffect.NA_Debug) getNamedObject("debug","NeonAffect.NA_Debug");
        return debug;
    }
    
}
