/*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*
  This code is generated by JAC version 5.6 by
  Agent Oriented Software. http://www.agent-software.com.au

    DO NOT ALTER THIS CODE AND DO NOT REMOVE THIS COMMENT
 *=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*/
package NeonAffect;
import aos.jack.jak.event.Event;

/**
 * 
 */

public class ExtremeLevelEvent extends aos.jack.jak.event.Event {
    public int iInitialLevel = 0;
    public int iEndLevel = 0;
    public int iAffect = 0;
    public double dLevelVelocity = 0.0;
    private final static java.lang.String[] __eventVariableNames = {
            "iInitialLevel",
            "iEndLevel",
            "iAffect",
            "dLevelVelocity"};
    private final static java.lang.String[] __eventVariableTypes = {
            "int",
            "int",
            "int",
            "double"};
    public java.lang.String getDocumentation()
    {
        return "/**\n * \n */\n";
    }
    
    public NeonAffect.ExtremeLevelEvent post(int iInitialLevel1, int iEndLevel1, int iAffect1, double dLevelVelocity1)
    {
        NeonAffect.ExtremeLevelEvent tmp = new NeonAffect.ExtremeLevelEvent();
        tmp.init(this);
        return tmp.post_body(iInitialLevel1,iEndLevel1,iAffect1,dLevelVelocity1);
    }
    
    private NeonAffect.ExtremeLevelEvent post_body(int iInitialLevel1, int iEndLevel1, int iAffect1, double dLevelVelocity1)
    {
        iInitialLevel = iInitialLevel1;
        iEndLevel = iEndLevel1;
        iAffect = iAffect1;
        dLevelVelocity = dLevelVelocity1;
        return this;
    }
    
    public ExtremeLevelEvent()
    {
    }
    
    public java.lang.String stateInfo()
    {
        return "NeonAffect/ExtremeLevelEvent.event [" + super.stateInfo() + "]";
    }
    
    public java.lang.String[] variableNames()
    {
        return __eventVariableNames;
    }
    
    public java.lang.String[] variableTypes()
    {
        return __eventVariableTypes;
    }
    
    public java.lang.Object getVariable(int n)
    {
        switch (n) {
            case 0: 
            {
                return aos.util.ToObject.box(iInitialLevel);
            }
            case 1: 
            {
                return aos.util.ToObject.box(iEndLevel);
            }
            case 2: 
            {
                return aos.util.ToObject.box(iAffect);
            }
            case 3: 
            {
                return aos.util.ToObject.box(dLevelVelocity);
            }
            default: 
            {
                throw new java.lang.IndexOutOfBoundsException("Event " + this + " does not have variable number " + n);
            }
        }
    }
    
}
