

/*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*
  This code is generated by JAC version 5.6 by
  Agent Oriented Software. http://www.agent-software.com.au

    DO NOT ALTER THIS CODE AND DO NOT REMOVE THIS COMMENT
 *=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*/
package NeonAffect;
import aos.jack.jak.event.MessageEvent;

/** Automatically generated class from 'null'. */
public class DecideReply extends aos.jack.jak.event.MessageEvent implements aos.apib.Base, java.io.Serializable {

  public static final __SS streamer = new __SS();

  /** Automatically generated method. */
  public aos.apib.StreamerSupport getStreamer()
    { return streamer; }

  /** Automatically generated method. */
  public int hashCode() {
     streamer.setup();
     return aos.apib.Util.hashCode(this);
  }

  /** Automatically generated method. */
  public boolean equals(Object o) {
     if (!(o instanceof aos.apib.Base)) return false;
     return aos.apib.Util.equals(this, (aos.apib.Base)o);
  }

  public boolean	bLevelOnly;
  public boolean	bLevelAndAffect;
  public boolean	bLevelAndExtreme;
  final static java.lang.String[]	__eventVariableNames = {
    "bLevelOnly",
    "bLevelAndAffect",
    "bLevelAndExtreme"};
  final static java.lang.String[]	__eventVariableTypes = {
    "boolean",
    "boolean",
    "boolean"};


public java.lang.String getDocumentation()
{
    return "/**\n * \n */\n";
}



public NeonAffect.DecideReply response(boolean bLevelOnly1, boolean bLevelAndAffect1, boolean bLevelAndExtreme1)
{
    NeonAffect.DecideReply tmp = new NeonAffect.DecideReply();
    tmp.init(this);
    return tmp.response_body(bLevelOnly1,bLevelAndAffect1,bLevelAndExtreme1);
}



private NeonAffect.DecideReply response_body(boolean bLevelOnly1, boolean bLevelAndAffect1, boolean bLevelAndExtreme1)
{
    bLevelOnly = bLevelOnly1;
    bLevelAndAffect = bLevelAndAffect1;
    bLevelAndExtreme = bLevelAndExtreme1;
    return this;
}



public java.lang.String stateInfo()
{
    return "NeonAffect/DecideReply.event [" + super.stateInfo() + "]";
}



public java.lang.String[] variableNames()
{
    return __eventVariableNames;
}



public java.lang.String[] variableTypes()
{
    return __eventVariableTypes;
}



public java.lang.Object getVariable(int n)
{
    switch (n) {
        case 0: 
        {
            return aos.util.ToObject.box(bLevelOnly);
        }
        case 1: 
        {
            return aos.util.ToObject.box(bLevelAndAffect);
        }
        case 2: 
        {
            return aos.util.ToObject.box(bLevelAndExtreme);
        }
        default: 
        {
            throw new java.lang.IndexOutOfBoundsException("Event " + this + " does not have variable number " + n);
        }
    }
}


  /** Automatically generated constructor. */
  public DecideReply() {
    streamer.setup();
    if (!getStreamer().initialized) return;
    __init__DecideReply();
  }

  /** Automatically generated method. */
  void __init__DecideReply() {
	bLevelOnly = false;
	bLevelAndAffect = false;
	bLevelAndExtreme = false;

  }

  /** Automatically generated JACOB streamer class */
  static class __SS extends aos.apib.StreamerSupport {
    DecideReply __def = null;

    /** Return a static instance. */

    public aos.apib.Base getDefaultInstance() { return __def; }

    private String[] fn = {
    ":bLevelOnly",
    ":bLevelAndAffect",
    ":bLevelAndExtreme",
    ":__eventVariableNames",
    ":__eventVariableTypes",
    };

    private String[] dn = {
    ":bLevelOnly",
    ":bLevelAndAffect",
    ":bLevelAndExtreme",
    ":__eventVariableNames",
    ":__eventVariableTypes",
    };

    private boolean[] ftr = {
    false,
    false,
    false,
    false,
    false,
    };

    private boolean[] fst = {
    false,
    false,
    false,
    true,
    true,
    };

    private boolean[] fhd = {
    false,
    false,
    false,
    false,
    false,
    };

    private int[] ft = {
    5,
    5,
    5,
    14,
    14,
    };

    private aos.apib.EnumInfo[] fe = {
	null,
	null,
	null,
	null,
	null,
    };

    private String[] cm = {
    null,
    null,
    null,
    null,
    null,
    };


    private aos.apib.StreamerSupport[][] al = {
	null,
	null,
	null,
	null,
	null,
    };

    private String[] fsubt = {
    null, 
    null, 
    null, 
    "java.lang.String[]",
    "java.lang.String[]",
    };

    /** Construct the streamer. */
    public __SS() {
      __type = "DecideReply";
      __icon = null;
      __comment = "Auto generated by the JACK Agents Compiler";
      __field_names = fn;
      __display_names = dn;
      __field_types = ft;
      __field_static = fst;
      __field_hidden = fhd;
      __field_transient = ftr;
      __field_subtypes = fsubt;
      __field_comments = cm;
      __enuminfos = fe;
      __allowed = al;
      register(__type, this);
    }

    private boolean setup_done = false;

    /** Initialization. */
    protected void setup() {
      if ( setup_done ) return;

      setup_done = true; 

      __def = (DecideReply)newInstance();
      setStreamedType(__def.getClass());
      baseclasses = findBaseStreamer(__def.getClass());
    }

    /** Initialization. */
    protected void init() {
      setup();
      __def.__init__DecideReply();
    }

    /** JACOB method. */
    public boolean isDummy() { return false; }

    /** JACOB method. */
    public aos.apib.Base new_instance() {
      return new DecideReply();
    }

    /** JACOB method. */
    public aos.apib.Base[] new_array(int n) {
      return new DecideReply[n];
    }

    /** JACOB class reading method. */
    public boolean read(aos.apib.InStream in, aos.apib.Base o) {
      int i = -1;
      while ((i = in.nextField(i, this)) >= 0) {
        if ( !readField( in, o, i ) ) {
          return false;
        }
      }
      return true;
    }

    /** JACOB method to read fields. */
    public boolean readField(aos.apib.InStream in, aos.apib.Base o,int i) {
      if ( i > __field_names.length )
        return getBaseClassStreamer().readField( in, o, i - __field_names.length - 1 );
      DecideReply v = (DecideReply)o;
      switch (i) {
      case 0:
	v.bLevelOnly = in.getBool();
	break;
   case 1:
	v.bLevelAndAffect = in.getBool();
	break;
   case 2:
	v.bLevelAndExtreme = in.getBool();
	break;
      case 5:
        in.readBaseClasses(o, this, 0);
        break;
      default:
        if (i >= 0 && i <= 5) break;
        in.error("Reader for DecideReply: illegal field number:"+i);
        return false;
      }
      return true;
    }

    /** JACOB class writing method. */
    public boolean write(aos.apib.OutStream out, aos.apib.Base o) {
      DecideReply v = (DecideReply)o;
      int i = -1;
      while ((i = out.nextField(i, this)) >= 0) {
        switch (i) {
      case 0:
	out.putBool(v.bLevelOnly, i, __def.bLevelOnly, this);
	break;
   case 1:
	out.putBool(v.bLevelAndAffect, i, __def.bLevelAndAffect, this);
	break;
   case 2:
	out.putBool(v.bLevelAndExtreme, i, __def.bLevelAndExtreme, this);
	break;
        case 5:
          out.writeBaseClasses(o, this);
          break;
        default:
          if (i >= 0 && i <= 5) break;
          out.error("Writer for DecideReply: illegal field number:"+i);
          return false;
        }
      }
      return true;
    }

    /** JACOB method. */
    public boolean isDefault(aos.apib.Base o) {
      DecideReply v = (DecideReply)o;

	if (v.bLevelOnly != __def.bLevelOnly) return false;
	if (v.bLevelAndAffect != __def.bLevelAndAffect) return false;
	if (v.bLevelAndExtreme != __def.bLevelAndExtreme) return false;
      if (baseclasses != null && baseclasses.length == 1)
        return baseclasses[0].isDefault(o);
      return true;
    }

    /** JACOB method. */
    public void findNonApib(aos.apib.OutStream out, aos.apib.Base o) {
     DecideReply v = (DecideReply)o;

      if (baseclasses != null && baseclasses.length == 1)
        baseclasses[0].findNonApib(out, o);
    }
  }

}

