/*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*
  This code is generated by JAC version 5.6 by
  Agent Oriented Software. http://www.agent-software.com.au

    DO NOT ALTER THIS CODE AND DO NOT REMOVE THIS COMMENT
 *=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*/
package NeonAffect;
import aos.jack.jak.agent.Capability;
import aos.jack.jak.agent.NameSpace;
import aos.jack.jak.agent.Agent;
import aos.jack.util.thread.Semaphore;

/**
 * 
 */

public class ObsessedAffectCapability extends aos.jack.jak.agent.Capability {
    public NeonAffect.PlanContextName planContextName;
    public NeonAffect.Behavior behaviorName;
    public aos.jack.util.thread.Semaphore mutex;
    public aos.jack.util.thread.Semaphore mutex2;
    public NeonAffect.NA_Debug debug;
    public NeonAffect.ContextEvent ce;
    public java.lang.String getDocumentation()
    {
        return "/**\n * \n */\n";
    }
    
    public void __init1()
    {
        setNamedCreator("planContextName","NeonAffect.PlanContextName",new aos.jack.jak.agent.DataCreator(false){
            public java.lang.Object create()
            {
                return __named_data_planContextName();
            }
            
        },true);
        setNamedCreator("behaviorName","NeonAffect.Behavior",new aos.jack.jak.agent.DataCreator(false){
            public java.lang.Object create()
            {
                return __named_data_behaviorName();
            }
            
        },true);
        setNamedCreator("mutex","aos.jack.util.thread.Semaphore",new aos.jack.jak.agent.DataCreator(false){
            public java.lang.Object create()
            {
                return __named_data_mutex();
            }
            
        },true);
        setNamedCreator("mutex2","aos.jack.util.thread.Semaphore",new aos.jack.jak.agent.DataCreator(false){
            public java.lang.Object create()
            {
                return __named_data_mutex2();
            }
            
        },true);
        setNamedCreator("debug","NeonAffect.NA_Debug",new aos.jack.jak.agent.DataCreator(false){
            public java.lang.Object create()
            {
                return __named_data_debug();
            }
            
        },true);
    }
    
    public void __init2()
    {
        ce = (NeonAffect.ContextEvent) findEvent("NeonAffect.ContextEvent");
        planContextName = (NeonAffect.PlanContextName) getNamedObject("planContextName","NeonAffect.PlanContextName");
        behaviorName = (NeonAffect.Behavior) getNamedObject("behaviorName","NeonAffect.Behavior");
        mutex = (aos.jack.util.thread.Semaphore) getNamedObject("mutex","aos.jack.util.thread.Semaphore");
        mutex2 = (aos.jack.util.thread.Semaphore) getNamedObject("mutex2","aos.jack.util.thread.Semaphore");
        debug = (NeonAffect.NA_Debug) getNamedObject("debug","NeonAffect.NA_Debug");
        autorun();
    }
    
    synchronized public void __init_desc()
    {
        externals.put("debug","debug");
        externals.put("mutex2","mutex2");
        externals.put("mutex","mutex");
        externals.put("behaviorName","behaviorName");
        externals.put("planContextName","planContextName");
        externals.put("NeonAffect.SetPlanContextEvent","NeonAffect.SetPlanContextEvent");
        externals.put("NeonAffect.Level6NegAffectEvent","NeonAffect.Level6NegAffectEvent");
        addEvent("NeonAffect.Level6NegAffectEvent",aos.jack.jak.agent.Agent.HANDLED_EVENT);
        addEvent("NeonAffect.SetPlanContextEvent",aos.jack.jak.agent.Agent.HANDLED_EVENT);
        addEvent("NeonAffect.ContextEvent",aos.jack.jak.agent.Agent.SENT_EVENT);
        addPlan("NeonAffect.AttentiveListeningPlan",0);
        addPlan("NeonAffect.RisingPitchVoicePlan",0);
        addPlan("NeonAffect.IntenseGazeObsessedPlan",0);
        addPlan("NeonAffect.OvertakingConversationPlan",0);
        addPlan("NeonAffect.LongStaringPlan",0);
        addPlan("NeonAffect.TalkLooselyPlan",0);
        addPlan("NeonAffect.AngryWhenBelittledPlan",0);
        addPlan("NeonAffect.DistractedPlan",0);
        addPlan("NeonAffect.SteadfastnessPlan",0);
        addPlan("NeonAffect.FantasizingPlan",0);
        addPlan("NeonAffect.MoodSwingsPlan",0);
        addPlan("NeonAffect.FatiguedObsessedPlan",0);
        addPlan("NeonAffect.InabilityToFunctionPlan",0);
        addPlan("NeonAffect.BecomingIsolatedPlan",0);
        addPlan("NeonAffect.ObsessiveCompulsivePlan",0);
        addPlan("NeonAffect.LossOfSelfPlan",0);
        addPlan("NeonAffect.LossSensationEmotionsPlan",0);
        addPlan("NeonAffect.AngryWhenConfrontedPlan",0);
        addPlan("NeonAffect.SetPlanContextObsessedPlan",0);
    }
    
    public ObsessedAffectCapability(aos.jack.jak.agent.NameSpace outer)
    {
        super(outer);
    }
    
    synchronized public void __bindNames()
    {
        super.__bindNames();
        __bindToPlan("NeonAffect.AttentiveListeningPlan");
        __bindToPlan("NeonAffect.RisingPitchVoicePlan");
        __bindToPlan("NeonAffect.IntenseGazeObsessedPlan");
        __bindToPlan("NeonAffect.OvertakingConversationPlan");
        __bindToPlan("NeonAffect.LongStaringPlan");
        __bindToPlan("NeonAffect.TalkLooselyPlan");
        __bindToPlan("NeonAffect.AngryWhenBelittledPlan");
        __bindToPlan("NeonAffect.DistractedPlan");
        __bindToPlan("NeonAffect.SteadfastnessPlan");
        __bindToPlan("NeonAffect.FantasizingPlan");
        __bindToPlan("NeonAffect.MoodSwingsPlan");
        __bindToPlan("NeonAffect.FatiguedObsessedPlan");
        __bindToPlan("NeonAffect.InabilityToFunctionPlan");
        __bindToPlan("NeonAffect.BecomingIsolatedPlan");
        __bindToPlan("NeonAffect.ObsessiveCompulsivePlan");
        __bindToPlan("NeonAffect.LossOfSelfPlan");
        __bindToPlan("NeonAffect.LossSensationEmotionsPlan");
        __bindToPlan("NeonAffect.AngryWhenConfrontedPlan");
        __bindToPlan("NeonAffect.SetPlanContextObsessedPlan");
    }
    
    private NeonAffect.PlanContextName __named_data_planContextName()
    {
        planContextName = (NeonAffect.PlanContextName) getNamedObject("planContextName","NeonAffect.PlanContextName");
        return planContextName;
    }
    
    private NeonAffect.Behavior __named_data_behaviorName()
    {
        behaviorName = (NeonAffect.Behavior) getNamedObject("behaviorName","NeonAffect.Behavior");
        return behaviorName;
    }
    
    private aos.jack.util.thread.Semaphore __named_data_mutex()
    {
        mutex = (aos.jack.util.thread.Semaphore) getNamedObject("mutex","aos.jack.util.thread.Semaphore");
        return mutex;
    }
    
    private aos.jack.util.thread.Semaphore __named_data_mutex2()
    {
        mutex2 = (aos.jack.util.thread.Semaphore) getNamedObject("mutex2","aos.jack.util.thread.Semaphore");
        return mutex2;
    }
    
    private NeonAffect.NA_Debug __named_data_debug()
    {
        debug = (NeonAffect.NA_Debug) getNamedObject("debug","NeonAffect.NA_Debug");
        return debug;
    }
    
}
