/*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*
  This code is generated by JAC version 5.6 by
  Agent Oriented Software. http://www.agent-software.com.au

    DO NOT ALTER THIS CODE AND DO NOT REMOVE THIS COMMENT
 *=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*/
package NeonAffect;
import aos.jack.jak.agent.Capability;
import aos.jack.jak.agent.NameSpace;
import aos.jack.jak.agent.Agent;
import aos.jack.util.thread.Semaphore;

/**
 * 
 */

public class PeacefulnessAffectCapability extends aos.jack.jak.agent.Capability {
    public NeonAffect.PlanContextName planContextName;
    public NeonAffect.Behavior behaviorName;
    public aos.jack.util.thread.Semaphore mutex;
    public aos.jack.util.thread.Semaphore mutex2;
    public NeonAffect.NA_Debug debug;
    public NeonAffect.ContextEvent ce;
    public java.lang.String getDocumentation()
    {
        return "/**\n * \n */\n";
    }
    
    public void __init1()
    {
        setNamedCreator("planContextName","NeonAffect.PlanContextName",new aos.jack.jak.agent.DataCreator(false){
            public java.lang.Object create()
            {
                return __named_data_planContextName();
            }
            
        },true);
        setNamedCreator("behaviorName","NeonAffect.Behavior",new aos.jack.jak.agent.DataCreator(false){
            public java.lang.Object create()
            {
                return __named_data_behaviorName();
            }
            
        },true);
        setNamedCreator("mutex","aos.jack.util.thread.Semaphore",new aos.jack.jak.agent.DataCreator(false){
            public java.lang.Object create()
            {
                return __named_data_mutex();
            }
            
        },true);
        setNamedCreator("mutex2","aos.jack.util.thread.Semaphore",new aos.jack.jak.agent.DataCreator(false){
            public java.lang.Object create()
            {
                return __named_data_mutex2();
            }
            
        },true);
        setNamedCreator("debug","NeonAffect.NA_Debug",new aos.jack.jak.agent.DataCreator(false){
            public java.lang.Object create()
            {
                return __named_data_debug();
            }
            
        },true);
    }
    
    public void __init2()
    {
        ce = (NeonAffect.ContextEvent) findEvent("NeonAffect.ContextEvent");
        planContextName = (NeonAffect.PlanContextName) getNamedObject("planContextName","NeonAffect.PlanContextName");
        behaviorName = (NeonAffect.Behavior) getNamedObject("behaviorName","NeonAffect.Behavior");
        mutex = (aos.jack.util.thread.Semaphore) getNamedObject("mutex","aos.jack.util.thread.Semaphore");
        mutex2 = (aos.jack.util.thread.Semaphore) getNamedObject("mutex2","aos.jack.util.thread.Semaphore");
        debug = (NeonAffect.NA_Debug) getNamedObject("debug","NeonAffect.NA_Debug");
        autorun();
    }
    
    synchronized public void __init_desc()
    {
        externals.put("debug","debug");
        externals.put("mutex2","mutex2");
        externals.put("mutex","mutex");
        externals.put("behaviorName","behaviorName");
        externals.put("planContextName","planContextName");
        externals.put("NeonAffect.SetPlanContextEvent","NeonAffect.SetPlanContextEvent");
        externals.put("NeonAffect.Level2PosAffectEvent","NeonAffect.Level2PosAffectEvent");
        addEvent("NeonAffect.Level2PosAffectEvent",aos.jack.jak.agent.Agent.HANDLED_EVENT);
        addEvent("NeonAffect.SetPlanContextEvent",aos.jack.jak.agent.Agent.HANDLED_EVENT);
        addEvent("NeonAffect.ContextEvent",aos.jack.jak.agent.Agent.SENT_EVENT);
        addPlan("NeonAffect.RelaxedPosturePeacefulnessPlan",0);
        addPlan("NeonAffect.SmilingPeacefulnessPlan",0);
        addPlan("NeonAffect.NoddingPeacefulnessPlan",0);
        addPlan("NeonAffect.LeanBackPeacefulnessPlan",0);
        addPlan("NeonAffect.DeepBreathPeacefulnessPlan",0);
        addPlan("NeonAffect.UnforcedLaughPlan",0);
        addPlan("NeonAffect.WhistlingHummingPeacefulnessPlan",0);
        addPlan("NeonAffect.BeingHonestPeacefulnessPlan",0);
        addPlan("NeonAffect.SparklingEyesPlan",0);
        addPlan("NeonAffect.EnjoyingMomentPlan",0);
        addPlan("NeonAffect.HalfClosedEyesPlan",0);
        addPlan("NeonAffect.SighPlan",0);
        addPlan("NeonAffect.UnhurriedSpeechPlan",0);
        addPlan("NeonAffect.MeaningfullConversationPlan",0);
        addPlan("NeonAffect.IncludeSelfPlan",0);
        addPlan("NeonAffect.ListeningToOthersPlan",0);
        addPlan("NeonAffect.AvoidingMoodKillersPlan",0);
        addPlan("NeonAffect.SetPlanContextPeacefulnessPlan",0);
    }
    
    public PeacefulnessAffectCapability(aos.jack.jak.agent.NameSpace outer)
    {
        super(outer);
    }
    
    synchronized public void __bindNames()
    {
        super.__bindNames();
        __bindToPlan("NeonAffect.RelaxedPosturePeacefulnessPlan");
        __bindToPlan("NeonAffect.SmilingPeacefulnessPlan");
        __bindToPlan("NeonAffect.NoddingPeacefulnessPlan");
        __bindToPlan("NeonAffect.LeanBackPeacefulnessPlan");
        __bindToPlan("NeonAffect.DeepBreathPeacefulnessPlan");
        __bindToPlan("NeonAffect.UnforcedLaughPlan");
        __bindToPlan("NeonAffect.WhistlingHummingPeacefulnessPlan");
        __bindToPlan("NeonAffect.BeingHonestPeacefulnessPlan");
        __bindToPlan("NeonAffect.SparklingEyesPlan");
        __bindToPlan("NeonAffect.EnjoyingMomentPlan");
        __bindToPlan("NeonAffect.HalfClosedEyesPlan");
        __bindToPlan("NeonAffect.SighPlan");
        __bindToPlan("NeonAffect.UnhurriedSpeechPlan");
        __bindToPlan("NeonAffect.MeaningfullConversationPlan");
        __bindToPlan("NeonAffect.IncludeSelfPlan");
        __bindToPlan("NeonAffect.ListeningToOthersPlan");
        __bindToPlan("NeonAffect.AvoidingMoodKillersPlan");
        __bindToPlan("NeonAffect.SetPlanContextPeacefulnessPlan");
    }
    
    private NeonAffect.PlanContextName __named_data_planContextName()
    {
        planContextName = (NeonAffect.PlanContextName) getNamedObject("planContextName","NeonAffect.PlanContextName");
        return planContextName;
    }
    
    private NeonAffect.Behavior __named_data_behaviorName()
    {
        behaviorName = (NeonAffect.Behavior) getNamedObject("behaviorName","NeonAffect.Behavior");
        return behaviorName;
    }
    
    private aos.jack.util.thread.Semaphore __named_data_mutex()
    {
        mutex = (aos.jack.util.thread.Semaphore) getNamedObject("mutex","aos.jack.util.thread.Semaphore");
        return mutex;
    }
    
    private aos.jack.util.thread.Semaphore __named_data_mutex2()
    {
        mutex2 = (aos.jack.util.thread.Semaphore) getNamedObject("mutex2","aos.jack.util.thread.Semaphore");
        return mutex2;
    }
    
    private NeonAffect.NA_Debug __named_data_debug()
    {
        debug = (NeonAffect.NA_Debug) getNamedObject("debug","NeonAffect.NA_Debug");
        return debug;
    }
    
}
