/*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*
  This code is generated by JAC version 5.6 by
  Agent Oriented Software. http://www.agent-software.com.au

    DO NOT ALTER THIS CODE AND DO NOT REMOVE THIS COMMENT
 *=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*/
package NeonAffect;
import aos.jack.jak.plan.Plan;
import aos.jack.jak.plan.PlanFSM;
import aos.jack.jak.plan.ExMap;
import aos.jack.jak.agent.NameSpace;
import aos.jack.jak.event.Event;
import aos.jack.jak.task.Task;
import aos.jack.jak.core.Generator;
import aos.jack.jak.logic.Signature;
import aos.jack.util.thread.Semaphore;
import java.lang.Object;
import aos.jack.jak.cursor.Cursor;
import aos.jack.jak.fsm.FSM;
import aos.jack.jak.core.Jak;

/**
 * 
 */

public class Level1NegAffectPlan extends aos.jack.jak.plan.Plan {
    private static java.lang.Class __exClass_0 = aos.jack.jak.fsm.FSM.loadClass("java.lang.Exception");
    public NeonAffect.SetAffectCursorsEvent ev1;
    public NeonAffect.Level1NegAffectEvent ev11;
    public NeonAffect.AddAffectHistoryEvent aahe;
    public NeonAffect.LevelCursorEvent lce;
    public NeonAffect.NeonAffectAgent enc;
    public NeonAffect.AffectType affectType;
    public NeonAffect.Emotion emotion;
    public aos.jack.util.thread.Semaphore mutex6;
    public NeonAffect.NA_Debug debug;
    private static aos.jack.jak.plan.ExMap[] __exMap_body = {
            new aos.jack.jak.plan.ExMap(10,28,29,__exClass_0)};
    private static java.lang.String[] __tt__body = {
            "NeonAffect/Level1NegAffectPlan.plan",
            "body",
            "43",
            "44",
            "46",
            "47",
            "49",
            "51",
            "53",
            "56",
            "58",
            "60",
            "73",
            "75",
            "77",
            "80",
            "81",
            "83",
            "85",
            "89",
            "91",
            "94",
            "96",
            "38"};
    private final static java.lang.String[] __planVariableNames = {
            "ev1",
            "ev11",
            "aahe",
            "lce",
            "enc",
            "affectType",
            "emotion",
            "mutex6",
            "debug"};
    private final static java.lang.String[] __planVariableTypes = {
            "SetAffectCursorsEvent",
            "Level1NegAffectEvent",
            "AddAffectHistoryEvent",
            "LevelCursorEvent",
            "NeonAffect.NeonAffectAgent",
            "AffectType",
            "Emotion",
            "aos.jack.util.thread.Semaphore",
            "NeonAffect.NA_Debug"};
    private final static java.lang.String[] __reasoningMethods = {
            "body"};
    private final static java.lang.String[] __fsmVariableNames_body = {
            "$affect",
            "$emotion",
            "$debug",
            "bDebug",
            "c",
            "e"};
    private final static java.lang.String[] __fsmTypes_body = {
            "logical int",
            "logical double",
            "logical boolean",
            "boolean",
            "Level1NegAffect",
            "Exception"};
    private final static java.lang.String[] __fsmLocalNames_body = {
            "__local__1529_0",
            "__local__1529_1",
            "__local__1529_2",
            "__local__1529_3",
            "__local__1529_4",
            "__local__1529_5"};
    static boolean relevant(NeonAffect.SetAffectCursorsEvent ev1)
    {
        return ev1.iCursorNumber == -1;
    }
    
    public java.lang.String getDocumentation()
    {
        return "/**\n * \n */\n";
    }
    
    public Level1NegAffectPlan()
    {
    }
    
    private Level1NegAffectPlan(aos.jack.jak.task.Task __t, NeonAffect.Level1NegAffectPlan __env)
    {
        __agent = __env.__agent;
        __ns = __env.__ns;
        __planTask = __t;
        __logic = __t.logic;
        ev1 = __env.ev1;
        ev11 = __env.ev11;
        aahe = __env.aahe;
        lce = __env.lce;
        enc = (NeonAffect.NeonAffectAgent) __ns.getIF(NeonAffect.NeonAffectAgent.class);
        affectType = __env.affectType;
        emotion = __env.emotion;
        mutex6 = __env.mutex6;
        debug = __env.debug;
    }
    
    public boolean init_sentinel(aos.jack.jak.agent.NameSpace __a)
    {
        ev1 = (NeonAffect.SetAffectCursorsEvent) __a.findEvent("NeonAffect.SetAffectCursorsEvent");
        if (ev1 == null) {
            warning("SetAffectCursorsEvent ev1: is not found in the capability/agent this plan comes from");
            return false;
        }
        ev11 = (NeonAffect.Level1NegAffectEvent) __a.findEvent("NeonAffect.Level1NegAffectEvent");
        if (ev11 == null) {
            warning("Level1NegAffectEvent ev11: is not found in the capability/agent this plan comes from");
            return false;
        }
        aahe = (NeonAffect.AddAffectHistoryEvent) __a.findEvent("NeonAffect.AddAffectHistoryEvent");
        if (aahe == null) {
            warning("AddAffectHistoryEvent aahe: is not found in the capability/agent this plan comes from");
            return false;
        }
        lce = (NeonAffect.LevelCursorEvent) __a.findEvent("NeonAffect.LevelCursorEvent");
        if (lce == null) {
            warning("LevelCursorEvent lce: is not found in the capability/agent this plan comes from");
            return false;
        }
        affectType = (NeonAffect.AffectType) lookupNamedObject("affectType","NeonAffect.AffectType",0);
        if (affectType == null) {
            warning("AffectType affectType: is not found in the capability/agent this plan comes from");
            return false;
        }
        emotion = (NeonAffect.Emotion) lookupNamedObject("emotion","NeonAffect.Emotion",0);
        if (emotion == null) {
            warning("Emotion emotion: is not found in the capability/agent this plan comes from");
            return false;
        }
        mutex6 = (aos.jack.util.thread.Semaphore) lookupNamedObject("mutex6","aos.jack.util.thread.Semaphore",0);
        if (mutex6 == null) {
            warning("Semaphore mutex6: is not found in the capability/agent this plan comes from");
            return false;
        }
        debug = (NeonAffect.NA_Debug) lookupNamedObject("debug","NeonAffect.NA_Debug",0);
        if (debug == null) {
            warning("NA_Debug debug: is not found in the capability/agent this plan comes from");
            return false;
        }
        return true;
    }
    
    public aos.jack.jak.plan.Plan freeze()
    {
        return this;
    }
    
    public aos.jack.jak.plan.Plan unfreeze()
    {
        return this;
    }
    
    public java.lang.Object genObject(int __index)
    {
        switch (__index) {
        }
        aos.jack.jak.core.Jak.error("illegal Object Construction");
        return null;
    }
    
    public aos.jack.jak.cursor.Cursor genCursor(int __index)
        throws java.lang.Exception
    {
        switch (__index) {
        }
        aos.jack.jak.core.Jak.error("illegal Cursor Construction");
        return null;
    }
    
    public aos.jack.jak.fsm.FSM genFSM(int __index)
        throws java.lang.Exception
    {
        switch (__index) {
        }
        aos.jack.jak.core.Jak.error("illegal FSM Construction");
        return null;
    }
    
    public boolean testCondition(int __index)
        throws java.lang.Exception
    {
        switch (__index) {
        }
        aos.jack.jak.core.Jak.error("illegal test Construction");
        return false;
    }
    
    public aos.jack.jak.plan.PlanFSM body()
    {
        return new NeonAffect.Level1NegAffectPlan.__bodyFSM();
    }
    
    private Level1NegAffectPlan(NeonAffect.SetAffectCursorsEvent __ev, aos.jack.jak.task.Task __t, NeonAffect.Level1NegAffectPlan __env)
    {
        this(__t,__env);
        this.ev1 = __ev;
    }
    
    protected aos.jack.jak.logic.Signature eventSignature(int __log)
    {
        return ev1.getSignature(__log);
    }
    
    public java.lang.String handledEvent()
    {
        return "NeonAffect.SetAffectCursorsEvent";
    }
    
    public boolean __relevant(aos.jack.jak.event.Event __e)
    {
        return __ns.isEnabled() && relevant(((NeonAffect.SetAffectCursorsEvent) __e));
    }
    
    public aos.jack.jak.plan.Plan createPlan(aos.jack.jak.event.Event __e, aos.jack.jak.task.Task __t)
    {
        if (!(__e instanceof NeonAffect.SetAffectCursorsEvent)) 
            return null;
        NeonAffect.SetAffectCursorsEvent __e1 = (NeonAffect.SetAffectCursorsEvent) __e;
        return new NeonAffect.Level1NegAffectPlan(__e1,__t,this);
    }
    
    public java.lang.String[] variableNames()
    {
        return __planVariableNames;
    }
    
    public java.lang.String[] variableTypes()
    {
        return __planVariableTypes;
    }
    
    public java.lang.Object getVariable(int n)
    {
        switch (n) {
            case 0: 
            {
                return aos.util.ToObject.box(ev1);
            }
            case 1: 
            {
                return aos.util.ToObject.box(ev11);
            }
            case 2: 
            {
                return aos.util.ToObject.box(aahe);
            }
            case 3: 
            {
                return aos.util.ToObject.box(lce);
            }
            case 4: 
            {
                return aos.util.ToObject.box(enc);
            }
            case 5: 
            {
                return aos.util.ToObject.box(affectType);
            }
            case 6: 
            {
                return aos.util.ToObject.box(emotion);
            }
            case 7: 
            {
                return aos.util.ToObject.box(mutex6);
            }
            case 8: 
            {
                return aos.util.ToObject.box(debug);
            }
            default: 
            {
                throw new java.lang.IndexOutOfBoundsException("Plan " + this + " does not have variable number " + n);
            }
        }
    }
    
    public java.lang.String[] reasoningMethods()
    {
        return mergeReasoningMethods(__reasoningMethods,super.reasoningMethods());
    }
    
    public aos.jack.jak.cursor.Cursor context()
    {
        try {
            return (((true)?aos.jack.jak.cursor.Cursor.trueCursor:aos.jack.jak.cursor.Cursor.falseCursor));
        }
        catch (java.lang.Exception e) {
            e.printStackTrace();
            return aos.jack.jak.cursor.Cursor.falseCursor;
        }
    }
    
    class __bodyFSM extends aos.jack.jak.plan.PlanFSM implements aos.jack.jak.core.Generator {
        aos.jack.jak.logic.IntegerVariable __local__1529_0;
        aos.jack.jak.logic.DoubleVariable __local__1529_1;
        aos.jack.jak.logic.BooleanVariable __local__1529_2;
        boolean __local__1529_3;
        NeonAffect.Level1NegAffect __local__1529_4;
        java.lang.Exception __local__1529_5;
        private int __breakLevel = 0;
        public int run(int __status)
            throws java.lang.Throwable
        {
            do {
                try {
                    if (__tothrow != null) 
                        throw __tothrow;
                    if ((aos.jack.jak.core.Jak.debugging & aos.jack.jak.core.Jak.LOG_PLANS) != 0) 
                        aos.util.logging.LogMsg.log(this,aos.jack.jak.core.Jak.LOG_PLANS,__task + "-Level1NegAffectPlan.body:" + java.lang.Integer.toString(__state));
                    if (__task.nsteps > 0) {
                        __task.nsteps-- ;
                        if (__task.nsteps == 0) 
                            agent.changeFocus();
                    }
                    if (__state < 10) {
                        __status = super.stdrun(NeonAffect.Level1NegAffectPlan.this,__status);
                        if (__status != CONTINUE || agent.changing_focus) 
                            return __status;
                        continue;
                    }
                    __curstate = __state;
                    switch (__state) {
                        default: 
                        {
                            aos.jack.jak.core.Jak.error("Level1NegAffectPlan.body: Illegal state");
                            return FAILED_STATE;
                        }
                        //* (43)             logical int $affect;
                        case 10: 
                        {
                            __breakLevel = 2;
                            __local__1529_0 = (aos.jack.jak.logic.IntegerVariable) __logic.new_variable(java.lang.Integer.TYPE);
                            __state = 11;
                            break;
                        }
                        //* (44)             logical double $emotion;
                        case 11: 
                        {
                            __local__1529_1 = (aos.jack.jak.logic.DoubleVariable) __logic.new_variable(java.lang.Double.TYPE);
                            __state = 12;
                            break;
                        }
                        //* (46)             logical boolean $debug;    
                        case 12: 
                        {
                            __local__1529_2 = (aos.jack.jak.logic.BooleanVariable) __logic.new_variable(java.lang.Boolean.TYPE);
                            __state = 13;
                            break;
                        }
                        //* (47)             debug.get($debug).next();
                        case 13: 
                        {
                            if (debug.get(__local__1529_2).next()) 
                                __state = 14;
                             else 
                                throw planfailed;
                            break;
                        }
                        //* (49)             boolean bDebug = $debug.as_boolean();
                        case 14: 
                        {
                            __local__1529_3 = __local__1529_2.as_boolean();
                            __state = 15;
                            break;
                        }
                        //* (51)             if (bDebug)
                        case 15: 
                        {
                            if (__local__1529_3) 
                                __state = 16;
                             else 
                                __state = 17;
                            break;
                        }
                        //* (53)                 System.out.println("Inside Level1NegAffectPlan.");
                        case 16: 
                        {
                            __breakLevel = 4;
                            __state = 17;
                            java.lang.System.out.println("Inside Level1NegAffectPlan.");
                            break;
                        }
                        //* (56)             Level1NegAffect c = new Level1NegAffect(enc.emotionCursorVar, enc.GetAgent());
                        case 17: 
                        {
                            __local__1529_4 = (NeonAffect.Level1NegAffect) genCursor(0);
                            __state = 18;
                            break;
                        }
                        //* (58)             while(true)
                        case 18: 
                        {
                            if (true) 
                                __state = 19;
                             else 
                                __state = 27;
                            break;
                        }
                        //* (60)                 @wait_for(c);
                        case 19: 
                        {
                            __breakLevel = 6;
                            __task.push(new aos.jack.jak.fsm.WaitForFSM(getAgent(),__task,this,1));
                            __state = -__state;
                            __subtask_pass = 20;
                            __subtask_fail = 4;
                            return SUBTASK;
                        }
                        //* (73)                 enc.SetCursorAck(c.GetCursorType(), c.GetLevel(), true);
                        case 20: 
                        {
                            __state = 21;
                            /*
                affectType.get($affect).next();
                int iAffect = $affect.as_int();
                
                emotion.get($emotion).next();
                double dEmotion = $emotion.as_double();
                
                @subtask(aahe.post(-1, System.currentTimeMillis(), iAffect, dEmotion));
                @subtask(ev11.post(iAffect));
                */

                            enc.SetCursorAck(__local__1529_4.GetCursorType(),__local__1529_4.GetLevel(),true);
                            break;
                        }
                        //* (75)                 if (bDebug)
                        case 21: 
                        {
                            if (__local__1529_3) 
                                __state = 22;
                             else 
                                __state = 23;
                            break;
                        }
                        //* (77)                     System.out.println("Level1NegAffectPlan: after wait_for.");
                        case 22: 
                        {
                            __breakLevel = 8;
                            __state = 23;
                            java.lang.System.out.println("Level1NegAffectPlan: after wait_for.");
                            break;
                        }
                        //* (80)                 @post(lce.post(CursorEnum.iLEVEL_CURSOR_NEG_1));
                        case 23: 
                        {
                            __state = 24;
                            agent.postEvent(lce.post(NeonAffect.CursorEnum.iLEVEL_CURSOR_NEG_1));
                            break;
                        }
                        //* (81)                 @wait_for(mutex6.planWait());
                        case 24: 
                        {
                            __task.push(new aos.jack.jak.fsm.WaitForFSM(getAgent(),__task,this,2));
                            __state = -__state;
                            __subtask_pass = 25;
                            __subtask_fail = 4;
                            return SUBTASK;
                        }
                        //* (83)                 if (bDebug)
                        case 25: 
                        {
                            if (__local__1529_3) 
                                __state = 26;
                             else 
                                __state = 18;
                            break;
                        }
                        //* (85)                     System.out.println("Level1NegAffectPlan: after level subtask call.");
                        case 26: 
                        {
                            __breakLevel = 8;
                            __state = 18;
                            java.lang.System.out.println("Level1NegAffectPlan: after level subtask call.");
                            break;
                        }
                        //* (89)             if (bDebug)
                        case 27: 
                        {
                            if (__local__1529_3) 
                                __state = 28;
                             else 
                                __state = 31;
                            break;
                        }
                        //* (91)                 System.out.println("After Level1NegAffectPlan wait_for.");
                        case 28: 
                        {
                            __breakLevel = 4;
                            __state = 31;
                            java.lang.System.out.println("After Level1NegAffectPlan wait_for.");
                            break;
                        }
                        //* (94)         catch (Exception e)
                        case 29: 
                        {
                            __breakLevel = 2;
                            __state = 30;
                            __local__1529_5 = (java.lang.Exception) __current;
                            break;
                        }
                        //* (96)             e.printStackTrace();          
                        case 30: 
                        {
                            __breakLevel = 4;
                            __state = 31;
                            __local__1529_5.printStackTrace();
                            break;
                        }
                        //* (38)     #reasoning method
                        case 31: 
                        {
                            if (__pending == null) 
                                __state = PASSED_STATE;
                            __tothrow = __pending;
                            break;
                        }
                    }
                }
                catch (java.lang.Throwable e) {
                    handleException(e,__exMap_body);
                }
            }
             while (!agent.changing_focus);
            return CONTINUE;
        }
        
        public java.lang.String methodName()
        {
            return "body";
        }
        
        __bodyFSM()
        {
        }
        
        public java.lang.String stateInfo()
        {
            int n = __curstate;
            java.lang.String file = __tt__body[0];
            java.lang.String method = __tt__body[1];
            if (n < 0) 
                n = -n;
            n -= (10 - 2);
            java.lang.String line = (n < 2)?"??":__tt__body[n];
            return file + ":" + line + " " + method + " [" + __curstate + "]";
        }
        
        public java.lang.Object genObject(int __index)
        {
            switch (__index) {
            }
            aos.jack.jak.core.Jak.error("illegal Object Construction");
            return null;
        }
        
        public aos.jack.jak.cursor.Cursor genCursor(int __index)
            throws java.lang.Exception
        {
            switch (__index) {
                case 0: 
                {
                    return (new NeonAffect.Level1NegAffect(enc.emotionCursorVar,enc.GetAgent()));
                }
                case 1: 
                {
                    return (__local__1529_4);
                }
                case 2: 
                {
                    return (mutex6.planWait());
                }
            }
            aos.jack.jak.core.Jak.error("illegal Cursor Construction");
            return null;
        }
        
        public aos.jack.jak.fsm.FSM genFSM(int __index)
            throws java.lang.Exception
        {
            switch (__index) {
            }
            aos.jack.jak.core.Jak.error("illegal FSM Construction");
            return null;
        }
        
        public boolean testCondition(int __index)
            throws java.lang.Exception
        {
            switch (__index) {
            }
            aos.jack.jak.core.Jak.error("illegal test Construction");
            return false;
        }
        
        public aos.jack.jak.plan.Plan getPlan()
        {
            return NeonAffect.Level1NegAffectPlan.this;
        }
        
        protected aos.jack.jak.fsm.FSM fail()
        {
            return getPlan().fail();
        }
        
        protected aos.jack.jak.fsm.FSM pass()
        {
            return getPlan().pass();
        }
        
        public void enter()
        {
            __trace = agent.trace("NeonAffect.Level1NegAffectPlan.body");
        }
        
        public java.lang.Object getVariable(int n)
        {
            switch (n) {
                case 0: 
                {
                    return aos.util.ToObject.box(__local__1529_0);
                }
                case 1: 
                {
                    return aos.util.ToObject.box(__local__1529_1);
                }
                case 2: 
                {
                    return aos.util.ToObject.box(__local__1529_2);
                }
                case 3: 
                {
                    return aos.util.ToObject.box(__local__1529_3);
                }
                case 4: 
                {
                    return aos.util.ToObject.box(__local__1529_4);
                }
                case 5: 
                {
                    return aos.util.ToObject.box(__local__1529_5);
                }
                default: 
                {
                    throw new java.lang.IndexOutOfBoundsException("Reasoning Method " + methodName() + " does not have variable number " + n);
                }
            }
        }
        
        public java.lang.String[] variableNames()
        {
            return __fsmVariableNames_body;
        }
        
        public java.lang.String[] variableTypes()
        {
            return __fsmTypes_body;
        }
        
        public java.lang.String[] variableLocalNames()
        {
            return __fsmLocalNames_body;
        }
        
    }
}
