/*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*
  This code is generated by JAC version 5.6 by
  Agent Oriented Software. http://www.agent-software.com.au

    DO NOT ALTER THIS CODE AND DO NOT REMOVE THIS COMMENT
 *=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*/
package NeonAffect;
import aos.jack.jak.core.Jak;
import aos.jack.jak.event.EventRecipient;
import aos.jack.jak.beliefset.OpenWorld;
import aos.jack.jak.beliefset.OpenWorldCursor;
import aos.jack.jak.beliefset.BeliefSetCursor;
import aos.jack.jak.beliefset.Tuple;
import aos.jack.jak.beliefset.BeliefSet;
import aos.jack.jak.logic.ChoicePoint;
import aos.jack.jak.logic.Variable;
import aos.jack.jak.cursor.BeliefState;
import aos.jack.plugin.view.rt.CleanupCursor;
import aos.jack.jak.beliefset.BeliefSetException;
import java.lang.Object;
import aos.jack.jak.cursor.Cursor;

/**
 * 
 */

public class CancelPlan extends aos.jack.jak.beliefset.OpenWorld {
    static public NeonAffect.CancelPlan__Tuple __hole = new NeonAffect.CancelPlan__Tuple(true);
    public NeonAffect.CancelPlan__Tuple[][] __tables;
    CancelPlan(boolean bCancel1)
    {
        try {
            //insert default

            add(bCancel1);
        }
        catch (aos.jack.jak.beliefset.BeliefSetException e) {
            e.printStackTrace();
        }
    }
    
    public java.lang.String getDocumentation()
    {
        return "/**\n * \n */\n";
    }
    
    public boolean attach(aos.jack.jak.event.EventRecipient __h)
    {
        java.lang.Object __o = __h;
        if (!super.attach(__h)) 
            return false;
        return true;
    }
    
    public aos.jack.jak.beliefset.BeliefSetCursor get(aos.jack.jak.logic.BooleanVariable __v0)
        throws aos.jack.jak.beliefset.BeliefSetException
    {
        NeonAffect.CancelPlan__Tuple __t = new NeonAffect.CancelPlan__Tuple();
        NeonAffect.CancelPlan.__Cursor __c = new NeonAffect.CancelPlan.__Cursor(__t);
        if (!__v0.check_unifiable(java.lang.Boolean.TYPE)) 
            throw new aos.jack.jak.beliefset.BeliefSetException("CancelPlan:get:O: arg 0 bCancel Incorrect Variable type");
        if (__v0.isGround()) {
            try {
                __t.bCancel = __v0.as_boolean();
            }
            catch (java.lang.Exception e) {
                throw new aos.jack.jak.beliefset.BeliefSetException("CancelPlan:get:O: got " + e.toString());
            }
        }
         else 
            __c.bCancel = __v0;
        __c.init(-1,this);
        return __c;
    }
    
    boolean getValue()
        throws aos.jack.jak.beliefset.BeliefSetException
    {
        NeonAffect.CancelPlan.__complex_3 __c = new NeonAffect.CancelPlan.__complex_3();
        try {
            return __c.__complex_3_getValue();
        }
        catch (java.lang.Exception __e) {
            throw new aos.jack.jak.beliefset.BeliefSetException("getValue got exception " + __e);
        }
    }
    
    int Reset()
        throws aos.jack.jak.beliefset.BeliefSetException
    {
        NeonAffect.CancelPlan.__complex_4 __c = new NeonAffect.CancelPlan.__complex_4();
        try {
            return __c.__complex_4_Reset();
        }
        catch (java.lang.Exception __e) {
            throw new aos.jack.jak.beliefset.BeliefSetException("Reset got exception " + __e);
        }
    }
    
    public int keyIndex()
    {
        return 0;
    }
    
    public int fullIndex()
    {
        return -1;
    }
    
    public int nIndexes()
    {
        return 1;
    }
    
    public aos.jack.jak.beliefset.Tuple newTuple()
    {
        return new NeonAffect.CancelPlan__Tuple();
    }
    
    public aos.jack.jak.beliefset.Tuple getTuple(int t, int l)
    {
        return __tables[t][l];
    }
    
    public aos.jack.jak.beliefset.Tuple[] newTable(int t)
    {
        return new NeonAffect.CancelPlan__Tuple[t];
    }
    
    public aos.jack.jak.beliefset.Tuple[][] newTables(int t)
    {
        return new NeonAffect.CancelPlan__Tuple[t][];
    }
    
    public aos.jack.jak.beliefset.Tuple[] getTable(int t)
    {
        return __tables[t];
    }
    
    public aos.jack.jak.beliefset.Tuple[][] getTables()
    {
        return __tables;
    }
    
    public void setTables(aos.jack.jak.beliefset.Tuple[][] t)
    {
        __tables = (NeonAffect.CancelPlan__Tuple[][]) t;
    }
    
    public aos.jack.jak.beliefset.BeliefSetCursor newCursor(aos.jack.jak.beliefset.Tuple __t)
    {
        if (__t instanceof NeonAffect.CancelPlan__Tuple) 
            return new NeonAffect.CancelPlan.__Cursor((NeonAffect.CancelPlan__Tuple) __t);
        return null;
    }
    
    public void add(boolean __v0)
        throws aos.jack.jak.beliefset.BeliefSetException
    {
        add(__v0,aos.jack.jak.cursor.Cursor.TRUE);
    }
    
    public void add(boolean __v0, aos.jack.jak.cursor.BeliefState __d)
        throws aos.jack.jak.beliefset.BeliefSetException
    {
        NeonAffect.CancelPlan__Tuple __t = new NeonAffect.CancelPlan__Tuple();
        __t.bCancel = __v0;
        super.assertTuple(__t,__d);
    }
    
    public void remove(boolean __v0)
        throws aos.jack.jak.beliefset.BeliefSetException
    {
        remove(__v0,aos.jack.jak.cursor.Cursor.TRUE);
    }
    
    public void remove(boolean __v0, aos.jack.jak.cursor.BeliefState __d)
        throws aos.jack.jak.beliefset.BeliefSetException
    {
        NeonAffect.CancelPlan__Tuple __t = new NeonAffect.CancelPlan__Tuple();
        __t.bCancel = __v0;
        super.retractTuple(__t,__d);
    }
    
    class __Cursor extends aos.jack.jak.beliefset.OpenWorldCursor {
        public NeonAffect.CancelPlan__Tuple __tuple = null;
        public aos.jack.jak.logic.Variable bCancel;
        public __Cursor()
        {
            __tuple = __hole;
        }
        
        public __Cursor(NeonAffect.CancelPlan__Tuple __t)
        {
            super();
            __tuple = __t;
        }
        
        public int match(int __ti, int __st, int __c, boolean __k, int __ind)
        {
            NeonAffect.CancelPlan__Tuple[] __tab = __tables[__ti];
            NeonAffect.CancelPlan__Tuple __t;
            int __sz = __tab.length;
            int __i;
            if ((aos.jack.jak.core.Jak.debugging & aos.jack.jak.core.Jak.LOG_DB) != 0) {
                aos.jack.jak.core.Jak.log.log("CancelPlan__Tuple:match:" + __ti + ":" + __st + ":" + __c + ":" + __k + ":" + __ind);
                aos.jack.jak.core.Jak.log.log("Tuple=" + __tuple);
                aos.jack.jak.core.Jak.log.log("Outputs are");
                aos.jack.jak.core.Jak.log.log("  bCancel:" + bCancel);
            }
            for (__i = __st; __c > 0; __i = (__i + 1) % __sz, __c-- ) {
                __t = __tab[__i];
                if (__t == null) {
                    if (__ind < 0) 
                        continue;
                    return -1;
                }
                if (__t == __hole) 
                    continue;
                if (__t.isFree) {
                    __tab[__i] = __hole;
                    continue;
                }
                if ((aos.jack.jak.core.Jak.debugging & aos.jack.jak.core.Jak.LOG_DB) != 0) 
                    aos.jack.jak.core.Jak.log.log("t" + __i + ":" + __t);
                try {
                    if (cp != null) 
                        cp.backtrack();
                    if (__k) 
                        return __i;
                    if (bCancel == null) {
                        if (__tuple.bCancel != __t.bCancel) 
                            continue;
                    }
                     else {
                        if (!bCancel.unify(__t.bCancel)) 
                            continue;
                    }
                }
                catch (java.lang.Exception e) {
                    continue;
                }
                return __i;
            }
            return -1;
        }
        
        public int hash(int __i)
        {
            return (__tuple == null?0:__tuple.hash(__i));
        }
        
        public aos.jack.jak.logic.ChoicePoint getChoicePoint()
        {
            if (bCancel != null) 
                return bCancel.getEnv().newChoicePoint();
            return null;
        }
        
        public boolean isKeyGround()
        {
            return true;
        }
        
    }
    class __complex_3 extends aos.jack.plugin.view.rt.CleanupCursor {
        aos.jack.jak.logic.BooleanVariable __local_2;
        boolean __local_3;
        public java.lang.Object genObject(int __index)
        {
            switch (__index) {
            }
            aos.jack.jak.core.Jak.error("illegal Object Construction");
            return null;
        }
        
        public aos.jack.jak.cursor.Cursor genCursor(int __index)
            throws java.lang.Exception
        {
            switch (__index) {
                case 0: 
                {
                    return (get(__local_2));
                }
            }
            aos.jack.jak.core.Jak.error("illegal Cursor Construction");
            return null;
        }
        
        public aos.jack.jak.fsm.FSM genFSM(int __index)
            throws java.lang.Exception
        {
            switch (__index) {
            }
            aos.jack.jak.core.Jak.error("illegal FSM Construction");
            return null;
        }
        
        public boolean testCondition(int __index)
            throws java.lang.Exception
        {
            switch (__index) {
            }
            aos.jack.jak.core.Jak.error("illegal test Construction");
            return false;
        }
        
        public __complex_3()
        {
            super();
        }
        
        boolean __complex_3_getValue()
            throws java.lang.Exception
        {
            __local_2 = (aos.jack.jak.logic.BooleanVariable) new_variable(java.lang.Boolean.TYPE);
            try {
                genCursor(0).next();
            }
            catch (aos.jack.jak.beliefset.BeliefSetException e) {
                java.lang.System.err.println("Error initializing data in Debug.");
                java.lang.System.exit(1);
            }
            __local_3 = __local_2.as_boolean();
            return __local_3;
        }
        
    }
    class __complex_4 extends aos.jack.plugin.view.rt.CleanupCursor {
        public java.lang.Object genObject(int __index)
        {
            switch (__index) {
            }
            aos.jack.jak.core.Jak.error("illegal Object Construction");
            return null;
        }
        
        public aos.jack.jak.cursor.Cursor genCursor(int __index)
            throws java.lang.Exception
        {
            switch (__index) {
            }
            aos.jack.jak.core.Jak.error("illegal Cursor Construction");
            return null;
        }
        
        public aos.jack.jak.fsm.FSM genFSM(int __index)
            throws java.lang.Exception
        {
            switch (__index) {
            }
            aos.jack.jak.core.Jak.error("illegal FSM Construction");
            return null;
        }
        
        public boolean testCondition(int __index)
            throws java.lang.Exception
        {
            switch (__index) {
            }
            aos.jack.jak.core.Jak.error("illegal test Construction");
            return false;
        }
        
        public __complex_4()
        {
            super();
        }
        
        int __complex_4_Reset()
            throws java.lang.Exception
        {
            try {
                add(false);
            }
            catch (aos.jack.jak.beliefset.BeliefSetException e) {
                e.printStackTrace();
            }
            return 0;
        }
        
    }
}
