/*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*
  This code is generated by JAC version 5.6 by
  Agent Oriented Software. http://www.agent-software.com.au

    DO NOT ALTER THIS CODE AND DO NOT REMOVE THIS COMMENT
 *=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*/
package NeonAffect;
import aos.jack.jak.core.Jak;
import aos.jack.jak.event.EventRecipient;
import aos.jack.jak.beliefset.OpenWorld;
import aos.jack.jak.beliefset.OpenWorldCursor;
import aos.jack.jak.beliefset.BeliefSetCursor;
import aos.jack.jak.beliefset.Tuple;
import aos.jack.jak.beliefset.BeliefSet;
import aos.jack.jak.logic.ChoicePoint;
import aos.jack.jak.logic.Variable;
import aos.jack.jak.cursor.BeliefState;
import aos.jack.plugin.view.rt.CleanupCursor;
import aos.jack.jak.beliefset.BeliefSetException;
import java.lang.Object;
import aos.jack.jak.cursor.Cursor;

/**
 * 
 */

public class Emotion extends aos.jack.jak.beliefset.OpenWorld {
    private aos.jack.jak.logic.DoubleVariable $emotion;
    static public NeonAffect.Emotion__Tuple __hole = new NeonAffect.Emotion__Tuple(true);
    public NeonAffect.Emotion__Tuple[][] __tables;
    Emotion()
    {
        try {
            //insert default value

            add(0,0.0d);
        }
        catch (aos.jack.jak.beliefset.BeliefSetException e) {
            e.printStackTrace();
        }
    }
    
    public java.lang.String getDocumentation()
    {
        return "/**\n * \n */\n";
    }
    
    public boolean attach(aos.jack.jak.event.EventRecipient __h)
    {
        java.lang.Object __o = __h;
        if (!super.attach(__h)) 
            return false;
        return true;
    }
    
    public aos.jack.jak.beliefset.BeliefSetCursor get(int __v0, aos.jack.jak.logic.DoubleVariable __v1)
        throws aos.jack.jak.beliefset.BeliefSetException
    {
        NeonAffect.Emotion__Tuple __t = new NeonAffect.Emotion__Tuple();
        NeonAffect.Emotion.__Cursor __c = new NeonAffect.Emotion.__Cursor(__t);
        __t.id = __v0;
        if (!__v1.check_unifiable(java.lang.Double.TYPE)) 
            throw new aos.jack.jak.beliefset.BeliefSetException("Emotion:get:IO: arg 1 dAmount Incorrect Variable type");
        if (__v1.isGround()) {
            try {
                __t.dAmount = __v1.as_double();
            }
            catch (java.lang.Exception e) {
                throw new aos.jack.jak.beliefset.BeliefSetException("Emotion:get:IO: got " + e.toString());
            }
        }
         else 
            __c.dAmount = __v1;
        __c.init(0,this);
        return __c;
    }
    
    double GetValue()
        throws aos.jack.jak.beliefset.BeliefSetException
    {
        NeonAffect.Emotion.__complex_5 __c = new NeonAffect.Emotion.__complex_5();
        try {
            return __c.__complex_5_GetValue();
        }
        catch (java.lang.Exception __e) {
            throw new aos.jack.jak.beliefset.BeliefSetException("GetValue got exception " + __e);
        }
    }
    
    public int keyIndex()
    {
        return 0;
    }
    
    public int fullIndex()
    {
        return 0;
    }
    
    public int nIndexes()
    {
        return 1;
    }
    
    public aos.jack.jak.beliefset.Tuple newTuple()
    {
        return new NeonAffect.Emotion__Tuple();
    }
    
    public aos.jack.jak.beliefset.Tuple getTuple(int t, int l)
    {
        return __tables[t][l];
    }
    
    public aos.jack.jak.beliefset.Tuple[] newTable(int t)
    {
        return new NeonAffect.Emotion__Tuple[t];
    }
    
    public aos.jack.jak.beliefset.Tuple[][] newTables(int t)
    {
        return new NeonAffect.Emotion__Tuple[t][];
    }
    
    public aos.jack.jak.beliefset.Tuple[] getTable(int t)
    {
        return __tables[t];
    }
    
    public aos.jack.jak.beliefset.Tuple[][] getTables()
    {
        return __tables;
    }
    
    public void setTables(aos.jack.jak.beliefset.Tuple[][] t)
    {
        __tables = (NeonAffect.Emotion__Tuple[][]) t;
    }
    
    public aos.jack.jak.beliefset.BeliefSetCursor newCursor(aos.jack.jak.beliefset.Tuple __t)
    {
        if (__t instanceof NeonAffect.Emotion__Tuple) 
            return new NeonAffect.Emotion.__Cursor((NeonAffect.Emotion__Tuple) __t);
        return null;
    }
    
    public void add(int __v0, double __v1)
        throws aos.jack.jak.beliefset.BeliefSetException
    {
        add(__v0,__v1,aos.jack.jak.cursor.Cursor.TRUE);
    }
    
    public void add(int __v0, double __v1, aos.jack.jak.cursor.BeliefState __d)
        throws aos.jack.jak.beliefset.BeliefSetException
    {
        NeonAffect.Emotion__Tuple __t = new NeonAffect.Emotion__Tuple();
        __t.id = __v0;
        __t.dAmount = __v1;
        super.assertTuple(__t,__d);
    }
    
    public void remove(int __v0, double __v1)
        throws aos.jack.jak.beliefset.BeliefSetException
    {
        remove(__v0,__v1,aos.jack.jak.cursor.Cursor.TRUE);
    }
    
    public void remove(int __v0, double __v1, aos.jack.jak.cursor.BeliefState __d)
        throws aos.jack.jak.beliefset.BeliefSetException
    {
        NeonAffect.Emotion__Tuple __t = new NeonAffect.Emotion__Tuple();
        __t.id = __v0;
        __t.dAmount = __v1;
        super.retractTuple(__t,__d);
    }
    
    class __Cursor extends aos.jack.jak.beliefset.OpenWorldCursor {
        public NeonAffect.Emotion__Tuple __tuple = null;
        public aos.jack.jak.logic.Variable id;
        public aos.jack.jak.logic.Variable dAmount;
        public __Cursor()
        {
            __tuple = __hole;
        }
        
        public __Cursor(NeonAffect.Emotion__Tuple __t)
        {
            super();
            __tuple = __t;
        }
        
        public int match(int __ti, int __st, int __c, boolean __k, int __ind)
        {
            NeonAffect.Emotion__Tuple[] __tab = __tables[__ti];
            NeonAffect.Emotion__Tuple __t;
            int __sz = __tab.length;
            int __i;
            if ((aos.jack.jak.core.Jak.debugging & aos.jack.jak.core.Jak.LOG_DB) != 0) {
                aos.jack.jak.core.Jak.log.log("Emotion__Tuple:match:" + __ti + ":" + __st + ":" + __c + ":" + __k + ":" + __ind);
                aos.jack.jak.core.Jak.log.log("Tuple=" + __tuple);
                aos.jack.jak.core.Jak.log.log("Outputs are");
                aos.jack.jak.core.Jak.log.log("  id:" + id);
                aos.jack.jak.core.Jak.log.log("  dAmount:" + dAmount);
            }
            for (__i = __st; __c > 0; __i = (__i + 1) % __sz, __c-- ) {
                __t = __tab[__i];
                if (__t == null) {
                    if (__ind < 0) 
                        continue;
                    return -1;
                }
                if (__t == __hole) 
                    continue;
                if (__t.isFree) {
                    __tab[__i] = __hole;
                    continue;
                }
                if ((aos.jack.jak.core.Jak.debugging & aos.jack.jak.core.Jak.LOG_DB) != 0) 
                    aos.jack.jak.core.Jak.log.log("t" + __i + ":" + __t);
                try {
                    if (cp != null) 
                        cp.backtrack();
                    if (id == null) {
                        if (__tuple.id != __t.id) 
                            continue;
                    }
                     else {
                        if (!id.unify(__t.id)) 
                            continue;
                    }
                    if (__k) 
                        return __i;
                    if (dAmount == null) {
                        if (__tuple.dAmount != __t.dAmount) 
                            continue;
                    }
                     else {
                        if (!dAmount.unify(__t.dAmount)) 
                            continue;
                    }
                }
                catch (java.lang.Exception e) {
                    continue;
                }
                return __i;
            }
            return -1;
        }
        
        public int hash(int __i)
        {
            return (__tuple == null?0:__tuple.hash(__i));
        }
        
        public aos.jack.jak.logic.ChoicePoint getChoicePoint()
        {
            if (id != null) 
                return id.getEnv().newChoicePoint();
            if (dAmount != null) 
                return dAmount.getEnv().newChoicePoint();
            return null;
        }
        
        public boolean isKeyGround()
        {
            if (id != null) 
                return false;
            return true;
        }
        
    }
    class __complex_5 extends aos.jack.plugin.view.rt.CleanupCursor {
        double __local_2;
        boolean __local_3;
        public java.lang.Object genObject(int __index)
        {
            switch (__index) {
            }
            aos.jack.jak.core.Jak.error("illegal Object Construction");
            return null;
        }
        
        public aos.jack.jak.cursor.Cursor genCursor(int __index)
            throws java.lang.Exception
        {
            switch (__index) {
                case 0: 
                {
                    return (get(0,$emotion));
                }
            }
            aos.jack.jak.core.Jak.error("illegal Cursor Construction");
            return null;
        }
        
        public aos.jack.jak.fsm.FSM genFSM(int __index)
            throws java.lang.Exception
        {
            switch (__index) {
            }
            aos.jack.jak.core.Jak.error("illegal FSM Construction");
            return null;
        }
        
        public boolean testCondition(int __index)
            throws java.lang.Exception
        {
            switch (__index) {
            }
            aos.jack.jak.core.Jak.error("illegal test Construction");
            return false;
        }
        
        public __complex_5()
        {
            super();
        }
        
        double __complex_5_GetValue()
            throws java.lang.Exception
        {
            __local_2 = 0d;
            try {
                __local_3 = true;
                if (__local_3) {
                    java.lang.System.out.println("Inside Level4PosEvent.");
                }
                genCursor(0).next();
                __local_2 = $emotion.as_double();
                if (__local_3) {
                    java.lang.System.out.println("After grabbing emotion: " + java.lang.Double.toString(__local_2));
                }
            }
            catch (java.lang.Exception e) {
                e.printStackTrace();
            }
            return __local_2;
        }
        
    }
}
