/*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*
  This code is generated by JAC version 5.6 by
  Agent Oriented Software. http://www.agent-software.com.au

    DO NOT ALTER THIS CODE AND DO NOT REMOVE THIS COMMENT
 *=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*/
package NeonAffect;
import aos.jack.jak.event.Event;

/**
 * 
 */

public class SetAffectCursorsEvent extends aos.jack.jak.event.Event {
    public int iCursorNumber = 0;
    private final static java.lang.String[] __eventVariableNames = {
            "iCursorNumber"};
    private final static java.lang.String[] __eventVariableTypes = {
            "int"};
    public java.lang.String getDocumentation()
    {
        return "/**\n * \n */\n";
    }
    
    public NeonAffect.SetAffectCursorsEvent post(int iCursorNumber1)
    {
        NeonAffect.SetAffectCursorsEvent tmp = new NeonAffect.SetAffectCursorsEvent();
        tmp.init(this);
        return tmp.post_body(iCursorNumber1);
    }
    
    private NeonAffect.SetAffectCursorsEvent post_body(int iCursorNumber1)
    {
        iCursorNumber = iCursorNumber1;
        return this;
    }
    
    public SetAffectCursorsEvent()
    {
    }
    
    public java.lang.String stateInfo()
    {
        return "NeonAffect/SetAffectCursorsEvent.event [" + super.stateInfo() + "]";
    }
    
    public java.lang.String[] variableNames()
    {
        return __eventVariableNames;
    }
    
    public java.lang.String[] variableTypes()
    {
        return __eventVariableTypes;
    }
    
    public java.lang.Object getVariable(int n)
    {
        switch (n) {
            case 0: 
            {
                return aos.util.ToObject.box(iCursorNumber);
            }
            default: 
            {
                throw new java.lang.IndexOutOfBoundsException("Event " + this + " does not have variable number " + n);
            }
        }
    }
    
}
