/*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*
  This code is generated by JAC version 5.6 by
  Agent Oriented Software. http://www.agent-software.com.au

    DO NOT ALTER THIS CODE AND DO NOT REMOVE THIS COMMENT
 *=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*/
package NeonAffect;
import aos.jack.jak.agent.Capability;
import aos.jack.jak.agent.NameSpace;
import aos.jack.jak.agent.Agent;
import aos.jack.util.thread.Semaphore;

/**
 * 
 */

public class InjusticeAffectCapability extends aos.jack.jak.agent.Capability {
    public NeonAffect.PlanContextName planContextName;
    public NeonAffect.Behavior behaviorName;
    public aos.jack.util.thread.Semaphore mutex;
    public aos.jack.util.thread.Semaphore mutex2;
    public NeonAffect.NA_Debug debug;
    public NeonAffect.ContextEvent ce;
    public java.lang.String getDocumentation()
    {
        return "/**\n * \n */\n";
    }
    
    public void __init1()
    {
        setNamedCreator("planContextName","NeonAffect.PlanContextName",new aos.jack.jak.agent.DataCreator(false){
            public java.lang.Object create()
            {
                return __named_data_planContextName();
            }
            
        },true);
        setNamedCreator("behaviorName","NeonAffect.Behavior",new aos.jack.jak.agent.DataCreator(false){
            public java.lang.Object create()
            {
                return __named_data_behaviorName();
            }
            
        },true);
        setNamedCreator("mutex","aos.jack.util.thread.Semaphore",new aos.jack.jak.agent.DataCreator(false){
            public java.lang.Object create()
            {
                return __named_data_mutex();
            }
            
        },true);
        setNamedCreator("mutex2","aos.jack.util.thread.Semaphore",new aos.jack.jak.agent.DataCreator(false){
            public java.lang.Object create()
            {
                return __named_data_mutex2();
            }
            
        },true);
        setNamedCreator("debug","NeonAffect.NA_Debug",new aos.jack.jak.agent.DataCreator(false){
            public java.lang.Object create()
            {
                return __named_data_debug();
            }
            
        },true);
    }
    
    public void __init2()
    {
        ce = (NeonAffect.ContextEvent) findEvent("NeonAffect.ContextEvent");
        planContextName = (NeonAffect.PlanContextName) getNamedObject("planContextName","NeonAffect.PlanContextName");
        behaviorName = (NeonAffect.Behavior) getNamedObject("behaviorName","NeonAffect.Behavior");
        mutex = (aos.jack.util.thread.Semaphore) getNamedObject("mutex","aos.jack.util.thread.Semaphore");
        mutex2 = (aos.jack.util.thread.Semaphore) getNamedObject("mutex2","aos.jack.util.thread.Semaphore");
        debug = (NeonAffect.NA_Debug) getNamedObject("debug","NeonAffect.NA_Debug");
        autorun();
    }
    
    synchronized public void __init_desc()
    {
        externals.put("debug","debug");
        externals.put("mutex2","mutex2");
        externals.put("mutex","mutex");
        externals.put("behaviorName","behaviorName");
        externals.put("planContextName","planContextName");
        externals.put("NeonAffect.SetPlanContextEvent","NeonAffect.SetPlanContextEvent");
        externals.put("NeonAffect.Level4NegAffectEvent","NeonAffect.Level4NegAffectEvent");
        addEvent("NeonAffect.Level4NegAffectEvent",aos.jack.jak.agent.Agent.HANDLED_EVENT);
        addEvent("NeonAffect.SetPlanContextEvent",aos.jack.jak.agent.Agent.HANDLED_EVENT);
        addEvent("NeonAffect.ContextEvent",aos.jack.jak.agent.Agent.SENT_EVENT);
        addPlan("NeonAffect.ArguingInjusticePlan",0);
        addPlan("NeonAffect.BlameInjusticePlan",0);
        addPlan("NeonAffect.ComplainInjusticePlan",0);
        addPlan("NeonAffect.DemandExplanationPlan",0);
        addPlan("NeonAffect.GaspInjusticePlan",0);
        addPlan("NeonAffect.HandsOnHipsInjusticePlan",0);
        addPlan("NeonAffect.RaisingVoiceInjusticePlan",0);
        addPlan("NeonAffect.RefusingToObeyInjusticePlan",0);
        addPlan("NeonAffect.RollingEyesInjusticePlan",0);
        addPlan("NeonAffect.SarcasmInjusticePlan",0);
        addPlan("NeonAffect.StiffPostureInjusticePlan",0);
        addPlan("NeonAffect.SwearingInjusticePlan",0);
        addPlan("NeonAffect.TakingRevengeInjusticePlan",0);
        addPlan("NeonAffect.WithdrawingFromOthersInjusticePlan",0);
        addPlan("NeonAffect.SetPlanContextInjusticePlan",0);
    }
    
    public InjusticeAffectCapability(aos.jack.jak.agent.NameSpace outer)
    {
        super(outer);
    }
    
    synchronized public void __bindNames()
    {
        super.__bindNames();
        __bindToPlan("NeonAffect.ArguingInjusticePlan");
        __bindToPlan("NeonAffect.BlameInjusticePlan");
        __bindToPlan("NeonAffect.ComplainInjusticePlan");
        __bindToPlan("NeonAffect.DemandExplanationPlan");
        __bindToPlan("NeonAffect.GaspInjusticePlan");
        __bindToPlan("NeonAffect.HandsOnHipsInjusticePlan");
        __bindToPlan("NeonAffect.RaisingVoiceInjusticePlan");
        __bindToPlan("NeonAffect.RefusingToObeyInjusticePlan");
        __bindToPlan("NeonAffect.RollingEyesInjusticePlan");
        __bindToPlan("NeonAffect.SarcasmInjusticePlan");
        __bindToPlan("NeonAffect.StiffPostureInjusticePlan");
        __bindToPlan("NeonAffect.SwearingInjusticePlan");
        __bindToPlan("NeonAffect.TakingRevengeInjusticePlan");
        __bindToPlan("NeonAffect.WithdrawingFromOthersInjusticePlan");
        __bindToPlan("NeonAffect.SetPlanContextInjusticePlan");
    }
    
    private NeonAffect.PlanContextName __named_data_planContextName()
    {
        planContextName = (NeonAffect.PlanContextName) getNamedObject("planContextName","NeonAffect.PlanContextName");
        return planContextName;
    }
    
    private NeonAffect.Behavior __named_data_behaviorName()
    {
        behaviorName = (NeonAffect.Behavior) getNamedObject("behaviorName","NeonAffect.Behavior");
        return behaviorName;
    }
    
    private aos.jack.util.thread.Semaphore __named_data_mutex()
    {
        mutex = (aos.jack.util.thread.Semaphore) getNamedObject("mutex","aos.jack.util.thread.Semaphore");
        return mutex;
    }
    
    private aos.jack.util.thread.Semaphore __named_data_mutex2()
    {
        mutex2 = (aos.jack.util.thread.Semaphore) getNamedObject("mutex2","aos.jack.util.thread.Semaphore");
        return mutex2;
    }
    
    private NeonAffect.NA_Debug __named_data_debug()
    {
        debug = (NeonAffect.NA_Debug) getNamedObject("debug","NeonAffect.NA_Debug");
        return debug;
    }
    
}
