/*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*
  This code is generated by JAC version 5.6 by
  Agent Oriented Software. http://www.agent-software.com.au

    DO NOT ALTER THIS CODE AND DO NOT REMOVE THIS COMMENT
 *=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*/
package NeonAffect;
import aos.jack.jak.agent.Capability;
import aos.jack.jak.agent.NameSpace;
import aos.jack.jak.agent.Agent;
import aos.jack.util.thread.Semaphore;

/**
 * 
 */

public class AffectionateAffectCapability extends aos.jack.jak.agent.Capability {
    public NeonAffect.PlanContextName planContextName;
    public NeonAffect.Behavior behaviorName;
    public aos.jack.util.thread.Semaphore mutex;
    public aos.jack.util.thread.Semaphore mutex2;
    public NeonAffect.NA_Debug debug;
    public NeonAffect.ContextEvent ce;
    public java.lang.String getDocumentation()
    {
        return "/**\n * \n */\n";
    }
    
    public void __init1()
    {
        setNamedCreator("planContextName","NeonAffect.PlanContextName",new aos.jack.jak.agent.DataCreator(false){
            public java.lang.Object create()
            {
                return __named_data_planContextName();
            }
            
        },true);
        setNamedCreator("behaviorName","NeonAffect.Behavior",new aos.jack.jak.agent.DataCreator(false){
            public java.lang.Object create()
            {
                return __named_data_behaviorName();
            }
            
        },true);
        setNamedCreator("mutex","aos.jack.util.thread.Semaphore",new aos.jack.jak.agent.DataCreator(false){
            public java.lang.Object create()
            {
                return __named_data_mutex();
            }
            
        },true);
        setNamedCreator("mutex2","aos.jack.util.thread.Semaphore",new aos.jack.jak.agent.DataCreator(false){
            public java.lang.Object create()
            {
                return __named_data_mutex2();
            }
            
        },true);
        setNamedCreator("debug","NeonAffect.NA_Debug",new aos.jack.jak.agent.DataCreator(false){
            public java.lang.Object create()
            {
                return __named_data_debug();
            }
            
        },true);
    }
    
    public void __init2()
    {
        ce = (NeonAffect.ContextEvent) findEvent("NeonAffect.ContextEvent");
        planContextName = (NeonAffect.PlanContextName) getNamedObject("planContextName","NeonAffect.PlanContextName");
        behaviorName = (NeonAffect.Behavior) getNamedObject("behaviorName","NeonAffect.Behavior");
        mutex = (aos.jack.util.thread.Semaphore) getNamedObject("mutex","aos.jack.util.thread.Semaphore");
        mutex2 = (aos.jack.util.thread.Semaphore) getNamedObject("mutex2","aos.jack.util.thread.Semaphore");
        debug = (NeonAffect.NA_Debug) getNamedObject("debug","NeonAffect.NA_Debug");
        autorun();
    }
    
    synchronized public void __init_desc()
    {
        externals.put("debug","debug");
        externals.put("mutex2","mutex2");
        externals.put("mutex","mutex");
        externals.put("behaviorName","behaviorName");
        externals.put("planContextName","planContextName");
        externals.put("NeonAffect.SetPlanContextEvent","NeonAffect.SetPlanContextEvent");
        externals.put("NeonAffect.Level4PosAffectEvent","NeonAffect.Level4PosAffectEvent");
        addEvent("NeonAffect.Level4PosAffectEvent",aos.jack.jak.agent.Agent.HANDLED_EVENT);
        addEvent("NeonAffect.SetPlanContextEvent",aos.jack.jak.agent.Agent.HANDLED_EVENT);
        addEvent("NeonAffect.ContextEvent",aos.jack.jak.agent.Agent.SENT_EVENT);
        addPlan("NeonAffect.AnticipatingNeedsPlan",0);
        addPlan("NeonAffect.BlowingKissPlan",0);
        addPlan("NeonAffect.BlushingAffectionatePlan",0);
        addPlan("NeonAffect.ExpressingAppreciationPlan",0);
        addPlan("NeonAffect.ExpressingLovePlan",0);
        addPlan("NeonAffect.EyeContactAffectionatePlan",0);
        addPlan("NeonAffect.GentleCaressAffectionatePlan",0);
        addPlan("NeonAffect.GiveComplementsAffectionatePlan",0);
        addPlan("NeonAffect.GivingPraisePlan",0);
        addPlan("NeonAffect.HuggingPlan",0);
        addPlan("NeonAffect.OfferingToHelpAffectionatePlan",0);
        addPlan("NeonAffect.OfferingWordsSupportPlan",0);
        addPlan("NeonAffect.PrioritizingPartnerPlan",0);
        addPlan("NeonAffect.SharingSecretsAffectionatePlan",0);
        addPlan("NeonAffect.ShowingConcernPlan",0);
        addPlan("NeonAffect.ShowingDevotionPlan",0);
        addPlan("NeonAffect.SmilingAffectionatePlan",0);
        addPlan("NeonAffect.SpeakingKindlyPlan",0);
        addPlan("NeonAffect.SpeakingSoftlyAffectionatePlan",0);
        addPlan("NeonAffect.SpendingQualityTimePlan",0);
        addPlan("NeonAffect.SurprisingWithAffectionPlan",0);
        addPlan("NeonAffect.WinkAffectionatePlan",0);
        addPlan("NeonAffect.WisperingPlan",0);
        addPlan("NeonAffect.SetPlanContextAffectionatePlan",0);
    }
    
    public AffectionateAffectCapability(aos.jack.jak.agent.NameSpace outer)
    {
        super(outer);
    }
    
    synchronized public void __bindNames()
    {
        super.__bindNames();
        __bindToPlan("NeonAffect.AnticipatingNeedsPlan");
        __bindToPlan("NeonAffect.BlowingKissPlan");
        __bindToPlan("NeonAffect.BlushingAffectionatePlan");
        __bindToPlan("NeonAffect.ExpressingAppreciationPlan");
        __bindToPlan("NeonAffect.ExpressingLovePlan");
        __bindToPlan("NeonAffect.EyeContactAffectionatePlan");
        __bindToPlan("NeonAffect.GentleCaressAffectionatePlan");
        __bindToPlan("NeonAffect.GiveComplementsAffectionatePlan");
        __bindToPlan("NeonAffect.GivingPraisePlan");
        __bindToPlan("NeonAffect.HuggingPlan");
        __bindToPlan("NeonAffect.OfferingToHelpAffectionatePlan");
        __bindToPlan("NeonAffect.OfferingWordsSupportPlan");
        __bindToPlan("NeonAffect.PrioritizingPartnerPlan");
        __bindToPlan("NeonAffect.SharingSecretsAffectionatePlan");
        __bindToPlan("NeonAffect.ShowingConcernPlan");
        __bindToPlan("NeonAffect.ShowingDevotionPlan");
        __bindToPlan("NeonAffect.SmilingAffectionatePlan");
        __bindToPlan("NeonAffect.SpeakingKindlyPlan");
        __bindToPlan("NeonAffect.SpeakingSoftlyAffectionatePlan");
        __bindToPlan("NeonAffect.SpendingQualityTimePlan");
        __bindToPlan("NeonAffect.SurprisingWithAffectionPlan");
        __bindToPlan("NeonAffect.WinkAffectionatePlan");
        __bindToPlan("NeonAffect.WisperingPlan");
        __bindToPlan("NeonAffect.SetPlanContextAffectionatePlan");
    }
    
    private NeonAffect.PlanContextName __named_data_planContextName()
    {
        planContextName = (NeonAffect.PlanContextName) getNamedObject("planContextName","NeonAffect.PlanContextName");
        return planContextName;
    }
    
    private NeonAffect.Behavior __named_data_behaviorName()
    {
        behaviorName = (NeonAffect.Behavior) getNamedObject("behaviorName","NeonAffect.Behavior");
        return behaviorName;
    }
    
    private aos.jack.util.thread.Semaphore __named_data_mutex()
    {
        mutex = (aos.jack.util.thread.Semaphore) getNamedObject("mutex","aos.jack.util.thread.Semaphore");
        return mutex;
    }
    
    private aos.jack.util.thread.Semaphore __named_data_mutex2()
    {
        mutex2 = (aos.jack.util.thread.Semaphore) getNamedObject("mutex2","aos.jack.util.thread.Semaphore");
        return mutex2;
    }
    
    private NeonAffect.NA_Debug __named_data_debug()
    {
        debug = (NeonAffect.NA_Debug) getNamedObject("debug","NeonAffect.NA_Debug");
        return debug;
    }
    
}
