/*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*
  This code is generated by JAC version 5.6 by
  Agent Oriented Software. http://www.agent-software.com.au

    DO NOT ALTER THIS CODE AND DO NOT REMOVE THIS COMMENT
 *=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*/
package NeonAffect;
import aos.jack.jak.agent.Capability;
import aos.jack.jak.agent.NameSpace;
import aos.jack.jak.agent.Agent;
import aos.jack.util.thread.Semaphore;

/**
 * 
 */

public class CapableAffectCapability extends aos.jack.jak.agent.Capability {
    public NeonAffect.PlanContextName planContextName;
    public NeonAffect.Behavior behaviorName;
    public aos.jack.util.thread.Semaphore mutex;
    public aos.jack.util.thread.Semaphore mutex2;
    public NeonAffect.NA_Debug debug;
    public NeonAffect.ContextEvent ce;
    public java.lang.String getDocumentation()
    {
        return "/**\n * \n */\n";
    }
    
    public void __init1()
    {
        setNamedCreator("planContextName","NeonAffect.PlanContextName",new aos.jack.jak.agent.DataCreator(false){
            public java.lang.Object create()
            {
                return __named_data_planContextName();
            }
            
        },true);
        setNamedCreator("behaviorName","NeonAffect.Behavior",new aos.jack.jak.agent.DataCreator(false){
            public java.lang.Object create()
            {
                return __named_data_behaviorName();
            }
            
        },true);
        setNamedCreator("mutex","aos.jack.util.thread.Semaphore",new aos.jack.jak.agent.DataCreator(false){
            public java.lang.Object create()
            {
                return __named_data_mutex();
            }
            
        },true);
        setNamedCreator("mutex2","aos.jack.util.thread.Semaphore",new aos.jack.jak.agent.DataCreator(false){
            public java.lang.Object create()
            {
                return __named_data_mutex2();
            }
            
        },true);
        setNamedCreator("debug","NeonAffect.NA_Debug",new aos.jack.jak.agent.DataCreator(false){
            public java.lang.Object create()
            {
                return __named_data_debug();
            }
            
        },true);
    }
    
    public void __init2()
    {
        ce = (NeonAffect.ContextEvent) findEvent("NeonAffect.ContextEvent");
        planContextName = (NeonAffect.PlanContextName) getNamedObject("planContextName","NeonAffect.PlanContextName");
        behaviorName = (NeonAffect.Behavior) getNamedObject("behaviorName","NeonAffect.Behavior");
        mutex = (aos.jack.util.thread.Semaphore) getNamedObject("mutex","aos.jack.util.thread.Semaphore");
        mutex2 = (aos.jack.util.thread.Semaphore) getNamedObject("mutex2","aos.jack.util.thread.Semaphore");
        debug = (NeonAffect.NA_Debug) getNamedObject("debug","NeonAffect.NA_Debug");
        autorun();
    }
    
    synchronized public void __init_desc()
    {
        externals.put("debug","debug");
        externals.put("mutex2","mutex2");
        externals.put("mutex","mutex");
        externals.put("behaviorName","behaviorName");
        externals.put("planContextName","planContextName");
        externals.put("NeonAffect.SetPlanContextEvent","NeonAffect.SetPlanContextEvent");
        externals.put("NeonAffect.Level3PosAffectEvent","NeonAffect.Level3PosAffectEvent");
        addEvent("NeonAffect.Level3PosAffectEvent",aos.jack.jak.agent.Agent.HANDLED_EVENT);
        addEvent("NeonAffect.SetPlanContextEvent",aos.jack.jak.agent.Agent.HANDLED_EVENT);
        addEvent("NeonAffect.ContextEvent",aos.jack.jak.agent.Agent.SENT_EVENT);
        addPlan("NeonAffect.AdaptabilityPlan",0);
        addPlan("NeonAffect.AnsweringQuestionsPlan",0);
        addPlan("NeonAffect.AttentionToDetailPlan",0);
        addPlan("NeonAffect.CalmExteriorCapablePlan",0);
        addPlan("NeonAffect.ConfidentPosturePlan",0);
        addPlan("NeonAffect.ConfidentVoiceCapablePlan",0);
        addPlan("NeonAffect.DecisionMakingPlan",0);
        addPlan("NeonAffect.DetailedExplanationsCapablePlan",0);
        addPlan("NeonAffect.EfficientlyManagingTasksPlan",0);
        addPlan("NeonAffect.EyeContactCapabilePlan",0);
        addPlan("NeonAffect.GivingEncouragementPlan",0);
        addPlan("NeonAffect.ListeningIntentlyCapablePlan",0);
        addPlan("NeonAffect.MaintainComposurePlan",0);
        addPlan("NeonAffect.NoddingCapablePlan",0);
        addPlan("NeonAffect.OfferingAdvicePlan",0);
        addPlan("NeonAffect.ProblemSolvingPlan",0);
        addPlan("NeonAffect.ResourcefulnessPlan",0);
        addPlan("NeonAffect.SharingExperienceCapablePlan",0);
        addPlan("NeonAffect.SmilingSincerelyPlan",0);
        addPlan("NeonAffect.TakingInitiativePlan",0);
        addPlan("NeonAffect.SetPlanContextCapablePlan",0);
    }
    
    public CapableAffectCapability(aos.jack.jak.agent.NameSpace outer)
    {
        super(outer);
    }
    
    synchronized public void __bindNames()
    {
        super.__bindNames();
        __bindToPlan("NeonAffect.AdaptabilityPlan");
        __bindToPlan("NeonAffect.AnsweringQuestionsPlan");
        __bindToPlan("NeonAffect.AttentionToDetailPlan");
        __bindToPlan("NeonAffect.CalmExteriorCapablePlan");
        __bindToPlan("NeonAffect.ConfidentPosturePlan");
        __bindToPlan("NeonAffect.ConfidentVoiceCapablePlan");
        __bindToPlan("NeonAffect.DecisionMakingPlan");
        __bindToPlan("NeonAffect.DetailedExplanationsCapablePlan");
        __bindToPlan("NeonAffect.EfficientlyManagingTasksPlan");
        __bindToPlan("NeonAffect.EyeContactCapabilePlan");
        __bindToPlan("NeonAffect.GivingEncouragementPlan");
        __bindToPlan("NeonAffect.ListeningIntentlyCapablePlan");
        __bindToPlan("NeonAffect.MaintainComposurePlan");
        __bindToPlan("NeonAffect.NoddingCapablePlan");
        __bindToPlan("NeonAffect.OfferingAdvicePlan");
        __bindToPlan("NeonAffect.ProblemSolvingPlan");
        __bindToPlan("NeonAffect.ResourcefulnessPlan");
        __bindToPlan("NeonAffect.SharingExperienceCapablePlan");
        __bindToPlan("NeonAffect.SmilingSincerelyPlan");
        __bindToPlan("NeonAffect.TakingInitiativePlan");
        __bindToPlan("NeonAffect.SetPlanContextCapablePlan");
    }
    
    private NeonAffect.PlanContextName __named_data_planContextName()
    {
        planContextName = (NeonAffect.PlanContextName) getNamedObject("planContextName","NeonAffect.PlanContextName");
        return planContextName;
    }
    
    private NeonAffect.Behavior __named_data_behaviorName()
    {
        behaviorName = (NeonAffect.Behavior) getNamedObject("behaviorName","NeonAffect.Behavior");
        return behaviorName;
    }
    
    private aos.jack.util.thread.Semaphore __named_data_mutex()
    {
        mutex = (aos.jack.util.thread.Semaphore) getNamedObject("mutex","aos.jack.util.thread.Semaphore");
        return mutex;
    }
    
    private aos.jack.util.thread.Semaphore __named_data_mutex2()
    {
        mutex2 = (aos.jack.util.thread.Semaphore) getNamedObject("mutex2","aos.jack.util.thread.Semaphore");
        return mutex2;
    }
    
    private NeonAffect.NA_Debug __named_data_debug()
    {
        debug = (NeonAffect.NA_Debug) getNamedObject("debug","NeonAffect.NA_Debug");
        return debug;
    }
    
}
