/*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*
  This code is generated by JAC version 5.6 by
  Agent Oriented Software. http://www.agent-software.com.au

    DO NOT ALTER THIS CODE AND DO NOT REMOVE THIS COMMENT
 *=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*/
package NeonAffect;
import aos.jack.jak.agent.Capability;
import aos.jack.jak.agent.NameSpace;
import aos.jack.jak.agent.Agent;
import aos.jack.util.thread.Semaphore;

/**
 * 
 */

public class DissatisfiedAffectCapability extends aos.jack.jak.agent.Capability {
    public NeonAffect.PlanContextName planContextName;
    public NeonAffect.Behavior behaviorName;
    public aos.jack.util.thread.Semaphore mutex;
    public aos.jack.util.thread.Semaphore mutex2;
    public NeonAffect.NA_Debug debug;
    public NeonAffect.ContextEvent ce;
    public java.lang.String getDocumentation()
    {
        return "/**\n * \n */\n";
    }
    
    public void __init1()
    {
        setNamedCreator("planContextName","NeonAffect.PlanContextName",new aos.jack.jak.agent.DataCreator(false){
            public java.lang.Object create()
            {
                return __named_data_planContextName();
            }
            
        },true);
        setNamedCreator("behaviorName","NeonAffect.Behavior",new aos.jack.jak.agent.DataCreator(false){
            public java.lang.Object create()
            {
                return __named_data_behaviorName();
            }
            
        },true);
        setNamedCreator("mutex","aos.jack.util.thread.Semaphore",new aos.jack.jak.agent.DataCreator(false){
            public java.lang.Object create()
            {
                return __named_data_mutex();
            }
            
        },true);
        setNamedCreator("mutex2","aos.jack.util.thread.Semaphore",new aos.jack.jak.agent.DataCreator(false){
            public java.lang.Object create()
            {
                return __named_data_mutex2();
            }
            
        },true);
        setNamedCreator("debug","NeonAffect.NA_Debug",new aos.jack.jak.agent.DataCreator(false){
            public java.lang.Object create()
            {
                return __named_data_debug();
            }
            
        },true);
    }
    
    public void __init2()
    {
        ce = (NeonAffect.ContextEvent) findEvent("NeonAffect.ContextEvent");
        planContextName = (NeonAffect.PlanContextName) getNamedObject("planContextName","NeonAffect.PlanContextName");
        behaviorName = (NeonAffect.Behavior) getNamedObject("behaviorName","NeonAffect.Behavior");
        mutex = (aos.jack.util.thread.Semaphore) getNamedObject("mutex","aos.jack.util.thread.Semaphore");
        mutex2 = (aos.jack.util.thread.Semaphore) getNamedObject("mutex2","aos.jack.util.thread.Semaphore");
        debug = (NeonAffect.NA_Debug) getNamedObject("debug","NeonAffect.NA_Debug");
        autorun();
    }
    
    synchronized public void __init_desc()
    {
        externals.put("debug","debug");
        externals.put("mutex2","mutex2");
        externals.put("mutex","mutex");
        externals.put("behaviorName","behaviorName");
        externals.put("planContextName","planContextName");
        externals.put("NeonAffect.SetPlanContextEvent","NeonAffect.SetPlanContextEvent");
        externals.put("NeonAffect.Level1NegAffectEvent","NeonAffect.Level1NegAffectEvent");
        addEvent("NeonAffect.Level1NegAffectEvent",aos.jack.jak.agent.Agent.HANDLED_EVENT);
        addEvent("NeonAffect.SetPlanContextEvent",aos.jack.jak.agent.Agent.HANDLED_EVENT);
        addEvent("NeonAffect.ContextEvent",aos.jack.jak.agent.Agent.SENT_EVENT);
        addPlan("NeonAffect.AnalyzingShortComingsPlan",0);
        addPlan("NeonAffect.ArmsCrossedDissatisfiedPlan",0);
        addPlan("NeonAffect.ClosedBodyPosturePlan",0);
        addPlan("NeonAffect.ComplainDissatisfiedPlan",0);
        addPlan("NeonAffect.ContemplatingImprovementsPlan",0);
        addPlan("NeonAffect.DisengageFromInteractionPlan",0);
        addPlan("NeonAffect.DwellingOnNegativePlan",0);
        addPlan("NeonAffect.ExpressingDisappointmentDissatisfiedPlan",0);
        addPlan("NeonAffect.FrownDissatisfiedPlan",0);
        addPlan("NeonAffect.LipsPursedDissatisfiedPlan",0);
        addPlan("NeonAffect.LookAwayDissatisfiedPlan",0);
        addPlan("NeonAffect.NegativeLanguageDissatisfiedPlan",0);
        addPlan("NeonAffect.PointingOutShortComingsPlan",0);
        addPlan("NeonAffect.ReplayingPastLetDownsPlan",0);
        addPlan("NeonAffect.RollingEyesDissatisfiedPlan",0);
        addPlan("NeonAffect.SeekingAlternativeOptionsPlan",0);
        addPlan("NeonAffect.ShakingHeadDissatisfiedPlan",0);
        addPlan("NeonAffect.SighDissatisfiedPlan",0);
        addPlan("NeonAffect.VerbalizingFrustrationPlan",0);
        addPlan("NeonAffect.VoicingCriticismPlan",0);
        addPlan("NeonAffect.SetPlanContextDissatisfiedPlan",0);
    }
    
    public DissatisfiedAffectCapability(aos.jack.jak.agent.NameSpace outer)
    {
        super(outer);
    }
    
    synchronized public void __bindNames()
    {
        super.__bindNames();
        __bindToPlan("NeonAffect.AnalyzingShortComingsPlan");
        __bindToPlan("NeonAffect.ArmsCrossedDissatisfiedPlan");
        __bindToPlan("NeonAffect.ClosedBodyPosturePlan");
        __bindToPlan("NeonAffect.ComplainDissatisfiedPlan");
        __bindToPlan("NeonAffect.ContemplatingImprovementsPlan");
        __bindToPlan("NeonAffect.DisengageFromInteractionPlan");
        __bindToPlan("NeonAffect.DwellingOnNegativePlan");
        __bindToPlan("NeonAffect.ExpressingDisappointmentDissatisfiedPlan");
        __bindToPlan("NeonAffect.FrownDissatisfiedPlan");
        __bindToPlan("NeonAffect.LipsPursedDissatisfiedPlan");
        __bindToPlan("NeonAffect.LookAwayDissatisfiedPlan");
        __bindToPlan("NeonAffect.NegativeLanguageDissatisfiedPlan");
        __bindToPlan("NeonAffect.PointingOutShortComingsPlan");
        __bindToPlan("NeonAffect.ReplayingPastLetDownsPlan");
        __bindToPlan("NeonAffect.RollingEyesDissatisfiedPlan");
        __bindToPlan("NeonAffect.SeekingAlternativeOptionsPlan");
        __bindToPlan("NeonAffect.ShakingHeadDissatisfiedPlan");
        __bindToPlan("NeonAffect.SighDissatisfiedPlan");
        __bindToPlan("NeonAffect.VerbalizingFrustrationPlan");
        __bindToPlan("NeonAffect.VoicingCriticismPlan");
        __bindToPlan("NeonAffect.SetPlanContextDissatisfiedPlan");
    }
    
    private NeonAffect.PlanContextName __named_data_planContextName()
    {
        planContextName = (NeonAffect.PlanContextName) getNamedObject("planContextName","NeonAffect.PlanContextName");
        return planContextName;
    }
    
    private NeonAffect.Behavior __named_data_behaviorName()
    {
        behaviorName = (NeonAffect.Behavior) getNamedObject("behaviorName","NeonAffect.Behavior");
        return behaviorName;
    }
    
    private aos.jack.util.thread.Semaphore __named_data_mutex()
    {
        mutex = (aos.jack.util.thread.Semaphore) getNamedObject("mutex","aos.jack.util.thread.Semaphore");
        return mutex;
    }
    
    private aos.jack.util.thread.Semaphore __named_data_mutex2()
    {
        mutex2 = (aos.jack.util.thread.Semaphore) getNamedObject("mutex2","aos.jack.util.thread.Semaphore");
        return mutex2;
    }
    
    private NeonAffect.NA_Debug __named_data_debug()
    {
        debug = (NeonAffect.NA_Debug) getNamedObject("debug","NeonAffect.NA_Debug");
        return debug;
    }
    
}
