/*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*
  This code is generated by JAC version 5.6 by
  Agent Oriented Software. http://www.agent-software.com.au

    DO NOT ALTER THIS CODE AND DO NOT REMOVE THIS COMMENT
 *=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*/
package NeonAffect;
import aos.jack.jak.agent.Capability;
import aos.jack.jak.agent.NameSpace;
import aos.jack.jak.agent.Agent;
import aos.jack.util.thread.Semaphore;

/**
 * 
 */

public class FearlessnessAffectCapability extends aos.jack.jak.agent.Capability {
    public NeonAffect.PlanContextName planContextName;
    public NeonAffect.Behavior behaviorName;
    public aos.jack.util.thread.Semaphore mutex;
    public aos.jack.util.thread.Semaphore mutex2;
    public NeonAffect.NA_Debug debug;
    public NeonAffect.ContextEvent ce;
    public java.lang.String getDocumentation()
    {
        return "/**\n * \n */\n";
    }
    
    public void __init1()
    {
        setNamedCreator("planContextName","NeonAffect.PlanContextName",new aos.jack.jak.agent.DataCreator(false){
            public java.lang.Object create()
            {
                return __named_data_planContextName();
            }
            
        },true);
        setNamedCreator("behaviorName","NeonAffect.Behavior",new aos.jack.jak.agent.DataCreator(false){
            public java.lang.Object create()
            {
                return __named_data_behaviorName();
            }
            
        },true);
        setNamedCreator("mutex","aos.jack.util.thread.Semaphore",new aos.jack.jak.agent.DataCreator(false){
            public java.lang.Object create()
            {
                return __named_data_mutex();
            }
            
        },true);
        setNamedCreator("mutex2","aos.jack.util.thread.Semaphore",new aos.jack.jak.agent.DataCreator(false){
            public java.lang.Object create()
            {
                return __named_data_mutex2();
            }
            
        },true);
        setNamedCreator("debug","NeonAffect.NA_Debug",new aos.jack.jak.agent.DataCreator(false){
            public java.lang.Object create()
            {
                return __named_data_debug();
            }
            
        },true);
    }
    
    public void __init2()
    {
        ce = (NeonAffect.ContextEvent) findEvent("NeonAffect.ContextEvent");
        planContextName = (NeonAffect.PlanContextName) getNamedObject("planContextName","NeonAffect.PlanContextName");
        behaviorName = (NeonAffect.Behavior) getNamedObject("behaviorName","NeonAffect.Behavior");
        mutex = (aos.jack.util.thread.Semaphore) getNamedObject("mutex","aos.jack.util.thread.Semaphore");
        mutex2 = (aos.jack.util.thread.Semaphore) getNamedObject("mutex2","aos.jack.util.thread.Semaphore");
        debug = (NeonAffect.NA_Debug) getNamedObject("debug","NeonAffect.NA_Debug");
        autorun();
    }
    
    synchronized public void __init_desc()
    {
        externals.put("debug","debug");
        externals.put("mutex2","mutex2");
        externals.put("mutex","mutex");
        externals.put("behaviorName","behaviorName");
        externals.put("planContextName","planContextName");
        externals.put("NeonAffect.SetPlanContextEvent","NeonAffect.SetPlanContextEvent");
        externals.put("NeonAffect.Level5PosAffectEvent","NeonAffect.Level5PosAffectEvent");
        addEvent("NeonAffect.Level5PosAffectEvent",aos.jack.jak.agent.Agent.HANDLED_EVENT);
        addEvent("NeonAffect.SetPlanContextEvent",aos.jack.jak.agent.Agent.HANDLED_EVENT);
        addEvent("NeonAffect.ContextEvent",aos.jack.jak.agent.Agent.SENT_EVENT);
        addPlan("NeonAffect.CalmExteriorPlan",0);
        addPlan("NeonAffect.GoodPostureFearlessnessPlan",0);
        addPlan("NeonAffect.LeanInFearlessnessPlan",0);
        addPlan("NeonAffect.AskQuestionsFearlessnessPlan",0);
        addPlan("NeonAffect.PositiveSelfTalkPlan",0);
        addPlan("NeonAffect.NoddingFearlessPlan",0);
        addPlan("NeonAffect.BeingDirectPlan",0);
        addPlan("NeonAffect.DeepBreathFearlessPlan",0);
        addPlan("NeonAffect.ToThePointSpeechPlan",0);
        addPlan("NeonAffect.EvenSeriousTonePlan",0);
        addPlan("NeonAffect.CalmingSpeechPlan",0);
        addPlan("NeonAffect.ImpatienceFromSpeechPlan",0);
        addPlan("NeonAffect.SelfSufficentPlan",0);
        addPlan("NeonAffect.ObservingBeforeReactingPlan",0);
        addPlan("NeonAffect.ImaginingWorstCaseScenarioPlan",0);
        addPlan("NeonAffect.TryNewThingsFearlessnessPlan",0);
        addPlan("NeonAffect.TakingOnChallengesPlan",0);
        addPlan("NeonAffect.NoProcrastinationFearlessnessPlan",0);
        addPlan("NeonAffect.NoiseSensitivityFearlessnessPlan",0);
        addPlan("NeonAffect.AvoidingDistractionsPlan",0);
        addPlan("NeonAffect.ThinkingLogicallyPlan",0);
        addPlan("NeonAffect.HesitationFearlessnessPlan",0);
        addPlan("NeonAffect.AskPermissionPlan",0);
        addPlan("NeonAffect.AvoidingEyeContactFearlessnessPlan",0);
        addPlan("NeonAffect.SetPlanContextFearlessnessPlan",0);
    }
    
    public FearlessnessAffectCapability(aos.jack.jak.agent.NameSpace outer)
    {
        super(outer);
    }
    
    synchronized public void __bindNames()
    {
        super.__bindNames();
        __bindToPlan("NeonAffect.CalmExteriorPlan");
        __bindToPlan("NeonAffect.GoodPostureFearlessnessPlan");
        __bindToPlan("NeonAffect.LeanInFearlessnessPlan");
        __bindToPlan("NeonAffect.AskQuestionsFearlessnessPlan");
        __bindToPlan("NeonAffect.PositiveSelfTalkPlan");
        __bindToPlan("NeonAffect.NoddingFearlessPlan");
        __bindToPlan("NeonAffect.BeingDirectPlan");
        __bindToPlan("NeonAffect.DeepBreathFearlessPlan");
        __bindToPlan("NeonAffect.ToThePointSpeechPlan");
        __bindToPlan("NeonAffect.EvenSeriousTonePlan");
        __bindToPlan("NeonAffect.CalmingSpeechPlan");
        __bindToPlan("NeonAffect.ImpatienceFromSpeechPlan");
        __bindToPlan("NeonAffect.SelfSufficentPlan");
        __bindToPlan("NeonAffect.ObservingBeforeReactingPlan");
        __bindToPlan("NeonAffect.ImaginingWorstCaseScenarioPlan");
        __bindToPlan("NeonAffect.TryNewThingsFearlessnessPlan");
        __bindToPlan("NeonAffect.TakingOnChallengesPlan");
        __bindToPlan("NeonAffect.NoProcrastinationFearlessnessPlan");
        __bindToPlan("NeonAffect.NoiseSensitivityFearlessnessPlan");
        __bindToPlan("NeonAffect.AvoidingDistractionsPlan");
        __bindToPlan("NeonAffect.ThinkingLogicallyPlan");
        __bindToPlan("NeonAffect.HesitationFearlessnessPlan");
        __bindToPlan("NeonAffect.AskPermissionPlan");
        __bindToPlan("NeonAffect.AvoidingEyeContactFearlessnessPlan");
        __bindToPlan("NeonAffect.SetPlanContextFearlessnessPlan");
    }
    
    private NeonAffect.PlanContextName __named_data_planContextName()
    {
        planContextName = (NeonAffect.PlanContextName) getNamedObject("planContextName","NeonAffect.PlanContextName");
        return planContextName;
    }
    
    private NeonAffect.Behavior __named_data_behaviorName()
    {
        behaviorName = (NeonAffect.Behavior) getNamedObject("behaviorName","NeonAffect.Behavior");
        return behaviorName;
    }
    
    private aos.jack.util.thread.Semaphore __named_data_mutex()
    {
        mutex = (aos.jack.util.thread.Semaphore) getNamedObject("mutex","aos.jack.util.thread.Semaphore");
        return mutex;
    }
    
    private aos.jack.util.thread.Semaphore __named_data_mutex2()
    {
        mutex2 = (aos.jack.util.thread.Semaphore) getNamedObject("mutex2","aos.jack.util.thread.Semaphore");
        return mutex2;
    }
    
    private NeonAffect.NA_Debug __named_data_debug()
    {
        debug = (NeonAffect.NA_Debug) getNamedObject("debug","NeonAffect.NA_Debug");
        return debug;
    }
    
}
