/*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*
  This code is generated by JAC version 5.6 by
  Agent Oriented Software. http://www.agent-software.com.au

    DO NOT ALTER THIS CODE AND DO NOT REMOVE THIS COMMENT
 *=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*/
package NeonAffect;
import aos.jack.jak.agent.Capability;
import aos.jack.jak.agent.NameSpace;
import aos.jack.jak.agent.Agent;
import aos.jack.util.thread.Semaphore;

/**
 * 
 */

public class IrritationAffectCapability extends aos.jack.jak.agent.Capability {
    public NeonAffect.PlanContextName planContextName;
    public NeonAffect.Behavior behaviorName;
    public aos.jack.util.thread.Semaphore mutex;
    public aos.jack.util.thread.Semaphore mutex2;
    public NeonAffect.NA_Debug debug;
    public NeonAffect.ContextEvent ce;
    public java.lang.String getDocumentation()
    {
        return "/**\n * \n */\n";
    }
    
    public void __init1()
    {
        setNamedCreator("planContextName","NeonAffect.PlanContextName",new aos.jack.jak.agent.DataCreator(false){
            public java.lang.Object create()
            {
                return __named_data_planContextName();
            }
            
        },true);
        setNamedCreator("behaviorName","NeonAffect.Behavior",new aos.jack.jak.agent.DataCreator(false){
            public java.lang.Object create()
            {
                return __named_data_behaviorName();
            }
            
        },true);
        setNamedCreator("mutex","aos.jack.util.thread.Semaphore",new aos.jack.jak.agent.DataCreator(false){
            public java.lang.Object create()
            {
                return __named_data_mutex();
            }
            
        },true);
        setNamedCreator("mutex2","aos.jack.util.thread.Semaphore",new aos.jack.jak.agent.DataCreator(false){
            public java.lang.Object create()
            {
                return __named_data_mutex2();
            }
            
        },true);
        setNamedCreator("debug","NeonAffect.NA_Debug",new aos.jack.jak.agent.DataCreator(false){
            public java.lang.Object create()
            {
                return __named_data_debug();
            }
            
        },true);
    }
    
    public void __init2()
    {
        ce = (NeonAffect.ContextEvent) findEvent("NeonAffect.ContextEvent");
        planContextName = (NeonAffect.PlanContextName) getNamedObject("planContextName","NeonAffect.PlanContextName");
        behaviorName = (NeonAffect.Behavior) getNamedObject("behaviorName","NeonAffect.Behavior");
        mutex = (aos.jack.util.thread.Semaphore) getNamedObject("mutex","aos.jack.util.thread.Semaphore");
        mutex2 = (aos.jack.util.thread.Semaphore) getNamedObject("mutex2","aos.jack.util.thread.Semaphore");
        debug = (NeonAffect.NA_Debug) getNamedObject("debug","NeonAffect.NA_Debug");
        autorun();
    }
    
    synchronized public void __init_desc()
    {
        externals.put("debug","debug");
        externals.put("mutex2","mutex2");
        externals.put("mutex","mutex");
        externals.put("behaviorName","behaviorName");
        externals.put("planContextName","planContextName");
        externals.put("NeonAffect.SetPlanContextEvent","NeonAffect.SetPlanContextEvent");
        externals.put("NeonAffect.Level1NegAffectEvent","NeonAffect.Level1NegAffectEvent");
        addEvent("NeonAffect.Level1NegAffectEvent",aos.jack.jak.agent.Agent.HANDLED_EVENT);
        addEvent("NeonAffect.SetPlanContextEvent",aos.jack.jak.agent.Agent.HANDLED_EVENT);
        addEvent("NeonAffect.ContextEvent",aos.jack.jak.agent.Agent.SENT_EVENT);
        addPlan("NeonAffect.PurseLipsIrritationPlan",0);
        addPlan("NeonAffect.SternLookHeadForwardPlan",0);
        addPlan("NeonAffect.RubbingBackOfNeckPlan",0);
        addPlan("NeonAffect.IntentivelyWatchingPlan",0);
        addPlan("NeonAffect.FrownIrritationPlan",0);
        addPlan("NeonAffect.CrossingArmsIrritationPlan",0);
        addPlan("NeonAffect.SpeakingInChallengingTonePlan",0);
        addPlan("NeonAffect.SmilingHardPlan",0);
        addPlan("NeonAffect.AskingPointedQuestionsPlan",0);
        addPlan("NeonAffect.ChangeSubjectPlan",0);
        addPlan("NeonAffect.ForcingLaughPlan",0);
        addPlan("NeonAffect.RaisingVoiceIrritationPlan",0);
        addPlan("NeonAffect.InterruptingSelfPlan",0);
        addPlan("NeonAffect.GoingSilentPlan",0);
        addPlan("NeonAffect.ExhaleThroughNoseIrritationPlan",0);
        addPlan("NeonAffect.InterruptingPlan",0);
        addPlan("NeonAffect.RepeatMannerismPlan",0);
        addPlan("NeonAffect.ClenchingTeethIrritationPlan",0);
        addPlan("NeonAffect.DivertNegativityPlan",0);
        addPlan("NeonAffect.WishingShutupPlan",0);
        addPlan("NeonAffect.CloudedJudgementPlan",0);
        addPlan("NeonAffect.JudgementalPlan",0);
        addPlan("NeonAffect.ChallengeViewpointPlan",0);
        addPlan("NeonAffect.SwearingPlan",0);
        addPlan("NeonAffect.NegativeLanguagePlan",0);
        addPlan("NeonAffect.SarcasmIrritationPlan",0);
        addPlan("NeonAffect.InsultPlan",0);
        addPlan("NeonAffect.SetPlanContextIrritationPlan",0);
    }
    
    public IrritationAffectCapability(aos.jack.jak.agent.NameSpace outer)
    {
        super(outer);
    }
    
    synchronized public void __bindNames()
    {
        super.__bindNames();
        __bindToPlan("NeonAffect.PurseLipsIrritationPlan");
        __bindToPlan("NeonAffect.SternLookHeadForwardPlan");
        __bindToPlan("NeonAffect.RubbingBackOfNeckPlan");
        __bindToPlan("NeonAffect.IntentivelyWatchingPlan");
        __bindToPlan("NeonAffect.FrownIrritationPlan");
        __bindToPlan("NeonAffect.CrossingArmsIrritationPlan");
        __bindToPlan("NeonAffect.SpeakingInChallengingTonePlan");
        __bindToPlan("NeonAffect.SmilingHardPlan");
        __bindToPlan("NeonAffect.AskingPointedQuestionsPlan");
        __bindToPlan("NeonAffect.ChangeSubjectPlan");
        __bindToPlan("NeonAffect.ForcingLaughPlan");
        __bindToPlan("NeonAffect.RaisingVoiceIrritationPlan");
        __bindToPlan("NeonAffect.InterruptingSelfPlan");
        __bindToPlan("NeonAffect.GoingSilentPlan");
        __bindToPlan("NeonAffect.ExhaleThroughNoseIrritationPlan");
        __bindToPlan("NeonAffect.InterruptingPlan");
        __bindToPlan("NeonAffect.RepeatMannerismPlan");
        __bindToPlan("NeonAffect.ClenchingTeethIrritationPlan");
        __bindToPlan("NeonAffect.DivertNegativityPlan");
        __bindToPlan("NeonAffect.WishingShutupPlan");
        __bindToPlan("NeonAffect.CloudedJudgementPlan");
        __bindToPlan("NeonAffect.JudgementalPlan");
        __bindToPlan("NeonAffect.ChallengeViewpointPlan");
        __bindToPlan("NeonAffect.SwearingPlan");
        __bindToPlan("NeonAffect.NegativeLanguagePlan");
        __bindToPlan("NeonAffect.SarcasmIrritationPlan");
        __bindToPlan("NeonAffect.InsultPlan");
        __bindToPlan("NeonAffect.SetPlanContextIrritationPlan");
    }
    
    private NeonAffect.PlanContextName __named_data_planContextName()
    {
        planContextName = (NeonAffect.PlanContextName) getNamedObject("planContextName","NeonAffect.PlanContextName");
        return planContextName;
    }
    
    private NeonAffect.Behavior __named_data_behaviorName()
    {
        behaviorName = (NeonAffect.Behavior) getNamedObject("behaviorName","NeonAffect.Behavior");
        return behaviorName;
    }
    
    private aos.jack.util.thread.Semaphore __named_data_mutex()
    {
        mutex = (aos.jack.util.thread.Semaphore) getNamedObject("mutex","aos.jack.util.thread.Semaphore");
        return mutex;
    }
    
    private aos.jack.util.thread.Semaphore __named_data_mutex2()
    {
        mutex2 = (aos.jack.util.thread.Semaphore) getNamedObject("mutex2","aos.jack.util.thread.Semaphore");
        return mutex2;
    }
    
    private NeonAffect.NA_Debug __named_data_debug()
    {
        debug = (NeonAffect.NA_Debug) getNamedObject("debug","NeonAffect.NA_Debug");
        return debug;
    }
    
}
