/*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*
  This code is generated by JAC version 5.6 by
  Agent Oriented Software. http://www.agent-software.com.au

    DO NOT ALTER THIS CODE AND DO NOT REMOVE THIS COMMENT
 *=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*/
package NeonAffect;
import aos.jack.jak.agent.Capability;
import aos.jack.jak.agent.NameSpace;
import aos.jack.jak.agent.Agent;
import aos.jack.util.thread.Semaphore;

/**
 * 
 */

public class SatisfactionAffectCapability extends aos.jack.jak.agent.Capability {
    public NeonAffect.PlanContextName planContextName;
    public NeonAffect.Behavior behaviorName;
    public aos.jack.util.thread.Semaphore mutex;
    public aos.jack.util.thread.Semaphore mutex2;
    public NeonAffect.NA_Debug debug;
    public NeonAffect.ContextEvent ce;
    public java.lang.String getDocumentation()
    {
        return "/**\n * \n */\n";
    }
    
    public void __init1()
    {
        setNamedCreator("planContextName","NeonAffect.PlanContextName",new aos.jack.jak.agent.DataCreator(false){
            public java.lang.Object create()
            {
                return __named_data_planContextName();
            }
            
        },true);
        setNamedCreator("behaviorName","NeonAffect.Behavior",new aos.jack.jak.agent.DataCreator(false){
            public java.lang.Object create()
            {
                return __named_data_behaviorName();
            }
            
        },true);
        setNamedCreator("mutex","aos.jack.util.thread.Semaphore",new aos.jack.jak.agent.DataCreator(false){
            public java.lang.Object create()
            {
                return __named_data_mutex();
            }
            
        },true);
        setNamedCreator("mutex2","aos.jack.util.thread.Semaphore",new aos.jack.jak.agent.DataCreator(false){
            public java.lang.Object create()
            {
                return __named_data_mutex2();
            }
            
        },true);
        setNamedCreator("debug","NeonAffect.NA_Debug",new aos.jack.jak.agent.DataCreator(false){
            public java.lang.Object create()
            {
                return __named_data_debug();
            }
            
        },true);
    }
    
    public void __init2()
    {
        ce = (NeonAffect.ContextEvent) findEvent("NeonAffect.ContextEvent");
        planContextName = (NeonAffect.PlanContextName) getNamedObject("planContextName","NeonAffect.PlanContextName");
        behaviorName = (NeonAffect.Behavior) getNamedObject("behaviorName","NeonAffect.Behavior");
        mutex = (aos.jack.util.thread.Semaphore) getNamedObject("mutex","aos.jack.util.thread.Semaphore");
        mutex2 = (aos.jack.util.thread.Semaphore) getNamedObject("mutex2","aos.jack.util.thread.Semaphore");
        debug = (NeonAffect.NA_Debug) getNamedObject("debug","NeonAffect.NA_Debug");
        autorun();
    }
    
    synchronized public void __init_desc()
    {
        externals.put("debug","debug");
        externals.put("mutex2","mutex2");
        externals.put("mutex","mutex");
        externals.put("behaviorName","behaviorName");
        externals.put("planContextName","planContextName");
        externals.put("NeonAffect.SetPlanContextEvent","NeonAffect.SetPlanContextEvent");
        externals.put("NeonAffect.Level3PosAffectEvent","NeonAffect.Level3PosAffectEvent");
        addEvent("NeonAffect.Level3PosAffectEvent",aos.jack.jak.agent.Agent.HANDLED_EVENT);
        addEvent("NeonAffect.SetPlanContextEvent",aos.jack.jak.agent.Agent.HANDLED_EVENT);
        addEvent("NeonAffect.ContextEvent",aos.jack.jak.agent.Agent.SENT_EVENT);
        addPlan("NeonAffect.CrispNodPlan",0);
        addPlan("NeonAffect.ThumbsUpSatisfactionPlan",0);
        addPlan("NeonAffect.CockySmilePlan",0);
        addPlan("NeonAffect.StraightPosturePlan",0);
        addPlan("NeonAffect.ClappingPlan",0);
        addPlan("NeonAffect.LoudCheeringPlan",0);
        addPlan("NeonAffect.BraggingPlan",0);
        addPlan("NeonAffect.DeepSighPlan",0);
        addPlan("NeonAffect.WhistlingHummingPlan",0);
        addPlan("NeonAffect.DeepBreathPlan",0);
        addPlan("NeonAffect.UnhurriedMovementPlan",0);
        addPlan("NeonAffect.DirectMannerPlan",0);
        addPlan("NeonAffect.OfferingCongratulationsPlan",0);
        addPlan("NeonAffect.IncreasedConfidencePlan",0);
        addPlan("NeonAffect.HyperAwarenessOfOthersPlan",0);
        addPlan("NeonAffect.ContentmentPlan",0);
        addPlan("NeonAffect.GratificationPlan",0);
        addPlan("NeonAffect.SetPlanContextSatisfactionPlan",0);
    }
    
    public SatisfactionAffectCapability(aos.jack.jak.agent.NameSpace outer)
    {
        super(outer);
    }
    
    synchronized public void __bindNames()
    {
        super.__bindNames();
        __bindToPlan("NeonAffect.CrispNodPlan");
        __bindToPlan("NeonAffect.ThumbsUpSatisfactionPlan");
        __bindToPlan("NeonAffect.CockySmilePlan");
        __bindToPlan("NeonAffect.StraightPosturePlan");
        __bindToPlan("NeonAffect.ClappingPlan");
        __bindToPlan("NeonAffect.LoudCheeringPlan");
        __bindToPlan("NeonAffect.BraggingPlan");
        __bindToPlan("NeonAffect.DeepSighPlan");
        __bindToPlan("NeonAffect.WhistlingHummingPlan");
        __bindToPlan("NeonAffect.DeepBreathPlan");
        __bindToPlan("NeonAffect.UnhurriedMovementPlan");
        __bindToPlan("NeonAffect.DirectMannerPlan");
        __bindToPlan("NeonAffect.OfferingCongratulationsPlan");
        __bindToPlan("NeonAffect.IncreasedConfidencePlan");
        __bindToPlan("NeonAffect.HyperAwarenessOfOthersPlan");
        __bindToPlan("NeonAffect.ContentmentPlan");
        __bindToPlan("NeonAffect.GratificationPlan");
        __bindToPlan("NeonAffect.SetPlanContextSatisfactionPlan");
    }
    
    private NeonAffect.PlanContextName __named_data_planContextName()
    {
        planContextName = (NeonAffect.PlanContextName) getNamedObject("planContextName","NeonAffect.PlanContextName");
        return planContextName;
    }
    
    private NeonAffect.Behavior __named_data_behaviorName()
    {
        behaviorName = (NeonAffect.Behavior) getNamedObject("behaviorName","NeonAffect.Behavior");
        return behaviorName;
    }
    
    private aos.jack.util.thread.Semaphore __named_data_mutex()
    {
        mutex = (aos.jack.util.thread.Semaphore) getNamedObject("mutex","aos.jack.util.thread.Semaphore");
        return mutex;
    }
    
    private aos.jack.util.thread.Semaphore __named_data_mutex2()
    {
        mutex2 = (aos.jack.util.thread.Semaphore) getNamedObject("mutex2","aos.jack.util.thread.Semaphore");
        return mutex2;
    }
    
    private NeonAffect.NA_Debug __named_data_debug()
    {
        debug = (NeonAffect.NA_Debug) getNamedObject("debug","NeonAffect.NA_Debug");
        return debug;
    }
    
}
