/*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*
  This code is generated by JAC version 5.6 by
  Agent Oriented Software. http://www.agent-software.com.au

    DO NOT ALTER THIS CODE AND DO NOT REMOVE THIS COMMENT
 *=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*/
package NeonAffect;
import aos.jack.jak.event.Event;

/**
 * 
 */

public class AddAffectHistoryEvent extends aos.jack.jak.event.Event {
    public int iLevel;
    public int iAffect;
    public double dValue;
    public long time;
    private final static java.lang.String[] __eventVariableNames = {
            "iLevel",
            "iAffect",
            "dValue",
            "time"};
    private final static java.lang.String[] __eventVariableTypes = {
            "int",
            "int",
            "double",
            "long"};
    public java.lang.String getDocumentation()
    {
        return "/**\n * \n */\n";
    }
    
    public NeonAffect.AddAffectHistoryEvent post(int iLevel1, long time1, int iAffect1, double dValue1)
    {
        NeonAffect.AddAffectHistoryEvent tmp = new NeonAffect.AddAffectHistoryEvent();
        tmp.init(this);
        return tmp.post_body(iLevel1,time1,iAffect1,dValue1);
    }
    
    private NeonAffect.AddAffectHistoryEvent post_body(int iLevel1, long time1, int iAffect1, double dValue1)
    {
        try {
            iLevel = iLevel1;
            iAffect = iAffect1;
            dValue = dValue1;
            time = time1;
        }
        catch (java.lang.Exception e) {
            e.printStackTrace();
        }
        return this;
    }
    
    public AddAffectHistoryEvent()
    {
    }
    
    public java.lang.String stateInfo()
    {
        return "NeonAffect/AddAffectHistoryEvent.event [" + super.stateInfo() + "]";
    }
    
    public java.lang.String[] variableNames()
    {
        return __eventVariableNames;
    }
    
    public java.lang.String[] variableTypes()
    {
        return __eventVariableTypes;
    }
    
    public java.lang.Object getVariable(int n)
    {
        switch (n) {
            case 0: 
            {
                return aos.util.ToObject.box(iLevel);
            }
            case 1: 
            {
                return aos.util.ToObject.box(iAffect);
            }
            case 2: 
            {
                return aos.util.ToObject.box(dValue);
            }
            case 3: 
            {
                return aos.util.ToObject.box(time);
            }
            default: 
            {
                throw new java.lang.IndexOutOfBoundsException("Event " + this + " does not have variable number " + n);
            }
        }
    }
    
}
