/*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*
  This code is generated by JAC version 5.6 by
  Agent Oriented Software. http://www.agent-software.com.au

    DO NOT ALTER THIS CODE AND DO NOT REMOVE THIS COMMENT
 *=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*/
package NeonAffect;
import aos.jack.jak.event.BDIGoalEvent;

/**
 * 
 */

public class GrabReservoirValueEvent extends aos.jack.jak.event.BDIGoalEvent {
    public java.lang.String getDocumentation()
    {
        return "/**\n * \n */\n";
    }
    
    public NeonAffect.GrabReservoirValueEvent post()
    {
        NeonAffect.GrabReservoirValueEvent tmp = new NeonAffect.GrabReservoirValueEvent();
        tmp.init(this);
        return tmp.post_body();
    }
    
    private NeonAffect.GrabReservoirValueEvent post_body()
    {
        return this;
    }
    
    public GrabReservoirValueEvent()
    {
    }
    
    public java.lang.String stateInfo()
    {
        return "NeonAffect/GrabReservoirValueEvent.event [" + super.stateInfo() + "]";
    }
    
}
