/*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*
  This code is generated by JAC version 5.6 by
  Agent Oriented Software. http://www.agent-software.com.au

    DO NOT ALTER THIS CODE AND DO NOT REMOVE THIS COMMENT
 *=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*/
package NeonAffect;
import aos.jack.jak.agent.Capability;
import aos.jack.jak.agent.NameSpace;
import aos.jack.jak.agent.Agent;
import aos.jack.util.thread.Semaphore;

/**
 * 
 */

public class DisappointmentAffectCapability extends aos.jack.jak.agent.Capability {
    public NeonAffect.PlanContextName planContextName;
    public NeonAffect.Behavior behaviorName;
    public aos.jack.util.thread.Semaphore mutex;
    public aos.jack.util.thread.Semaphore mutex2;
    public NeonAffect.NA_Debug debug;
    public NeonAffect.ContextEvent ce;
    public java.lang.String getDocumentation()
    {
        return "/**\n * \n */\n";
    }
    
    public void __init1()
    {
        setNamedCreator("planContextName","NeonAffect.PlanContextName",new aos.jack.jak.agent.DataCreator(false){
            public java.lang.Object create()
            {
                return __named_data_planContextName();
            }
            
        },true);
        setNamedCreator("behaviorName","NeonAffect.Behavior",new aos.jack.jak.agent.DataCreator(false){
            public java.lang.Object create()
            {
                return __named_data_behaviorName();
            }
            
        },true);
        setNamedCreator("mutex","aos.jack.util.thread.Semaphore",new aos.jack.jak.agent.DataCreator(false){
            public java.lang.Object create()
            {
                return __named_data_mutex();
            }
            
        },true);
        setNamedCreator("mutex2","aos.jack.util.thread.Semaphore",new aos.jack.jak.agent.DataCreator(false){
            public java.lang.Object create()
            {
                return __named_data_mutex2();
            }
            
        },true);
        setNamedCreator("debug","NeonAffect.NA_Debug",new aos.jack.jak.agent.DataCreator(false){
            public java.lang.Object create()
            {
                return __named_data_debug();
            }
            
        },true);
    }
    
    public void __init2()
    {
        ce = (NeonAffect.ContextEvent) findEvent("NeonAffect.ContextEvent");
        planContextName = (NeonAffect.PlanContextName) getNamedObject("planContextName","NeonAffect.PlanContextName");
        behaviorName = (NeonAffect.Behavior) getNamedObject("behaviorName","NeonAffect.Behavior");
        mutex = (aos.jack.util.thread.Semaphore) getNamedObject("mutex","aos.jack.util.thread.Semaphore");
        mutex2 = (aos.jack.util.thread.Semaphore) getNamedObject("mutex2","aos.jack.util.thread.Semaphore");
        debug = (NeonAffect.NA_Debug) getNamedObject("debug","NeonAffect.NA_Debug");
        autorun();
    }
    
    synchronized public void __init_desc()
    {
        externals.put("debug","debug");
        externals.put("mutex2","mutex2");
        externals.put("mutex","mutex");
        externals.put("behaviorName","behaviorName");
        externals.put("planContextName","planContextName");
        externals.put("NeonAffect.SetPlanContextEvent","NeonAffect.SetPlanContextEvent");
        externals.put("NeonAffect.Level2NegAffectEvent","NeonAffect.Level2NegAffectEvent");
        addEvent("NeonAffect.Level2NegAffectEvent",aos.jack.jak.agent.Agent.HANDLED_EVENT);
        addEvent("NeonAffect.SetPlanContextEvent",aos.jack.jak.agent.Agent.HANDLED_EVENT);
        addEvent("NeonAffect.ContextEvent",aos.jack.jak.agent.Agent.SENT_EVENT);
        addPlan("NeonAffect.LoweringHeadPlan",0);
        addPlan("NeonAffect.LipsPursedDisappointmentPlan",0);
        addPlan("NeonAffect.BadPostureDiappointmentPlan",0);
        addPlan("NeonAffect.ShakingHeadDisappointmentPlan",0);
        addPlan("NeonAffect.SighDisappointmentPlan",0);
        addPlan("NeonAffect.BreakingEyeContactPlan",0);
        addPlan("NeonAffect.SwallowingHardDisappointmentPlan",0);
        addPlan("NeonAffect.FaceGoingSlackPlan",0);
        addPlan("NeonAffect.TearingDisappointmentPlan",0);
        addPlan("NeonAffect.WinceDisappointmentPlan",0);
        addPlan("NeonAffect.MouthOpenSlighlyPlan",0);
        addPlan("NeonAffect.LookAroundConfusionPlan",0);
        addPlan("NeonAffect.RubbingPackOfNeckDisappointmentPlan",0);
        addPlan("NeonAffect.GoingQuietPlan",0);
        addPlan("NeonAffect.CursingPlan",0);
        addPlan("NeonAffect.BitingLipDisappointmentPlan",0);
        addPlan("NeonAffect.WantingToBeAloneDisappointmentPlan",0);
        addPlan("NeonAffect.WorthlessnessPlan",0);
        addPlan("NeonAffect.FlushedFaceDisappointmentPlan",0);
        addPlan("NeonAffect.PutOneselfDownPlan",0);
        addPlan("NeonAffect.InabilityMoveOnPlan",0);
        addPlan("NeonAffect.SetPlanContextDisappointmentPlan",0);
    }
    
    public DisappointmentAffectCapability(aos.jack.jak.agent.NameSpace outer)
    {
        super(outer);
    }
    
    synchronized public void __bindNames()
    {
        super.__bindNames();
        __bindToPlan("NeonAffect.LoweringHeadPlan");
        __bindToPlan("NeonAffect.LipsPursedDisappointmentPlan");
        __bindToPlan("NeonAffect.BadPostureDiappointmentPlan");
        __bindToPlan("NeonAffect.ShakingHeadDisappointmentPlan");
        __bindToPlan("NeonAffect.SighDisappointmentPlan");
        __bindToPlan("NeonAffect.BreakingEyeContactPlan");
        __bindToPlan("NeonAffect.SwallowingHardDisappointmentPlan");
        __bindToPlan("NeonAffect.FaceGoingSlackPlan");
        __bindToPlan("NeonAffect.TearingDisappointmentPlan");
        __bindToPlan("NeonAffect.WinceDisappointmentPlan");
        __bindToPlan("NeonAffect.MouthOpenSlighlyPlan");
        __bindToPlan("NeonAffect.LookAroundConfusionPlan");
        __bindToPlan("NeonAffect.RubbingPackOfNeckDisappointmentPlan");
        __bindToPlan("NeonAffect.GoingQuietPlan");
        __bindToPlan("NeonAffect.CursingPlan");
        __bindToPlan("NeonAffect.BitingLipDisappointmentPlan");
        __bindToPlan("NeonAffect.WantingToBeAloneDisappointmentPlan");
        __bindToPlan("NeonAffect.WorthlessnessPlan");
        __bindToPlan("NeonAffect.FlushedFaceDisappointmentPlan");
        __bindToPlan("NeonAffect.PutOneselfDownPlan");
        __bindToPlan("NeonAffect.InabilityMoveOnPlan");
        __bindToPlan("NeonAffect.SetPlanContextDisappointmentPlan");
    }
    
    private NeonAffect.PlanContextName __named_data_planContextName()
    {
        planContextName = (NeonAffect.PlanContextName) getNamedObject("planContextName","NeonAffect.PlanContextName");
        return planContextName;
    }
    
    private NeonAffect.Behavior __named_data_behaviorName()
    {
        behaviorName = (NeonAffect.Behavior) getNamedObject("behaviorName","NeonAffect.Behavior");
        return behaviorName;
    }
    
    private aos.jack.util.thread.Semaphore __named_data_mutex()
    {
        mutex = (aos.jack.util.thread.Semaphore) getNamedObject("mutex","aos.jack.util.thread.Semaphore");
        return mutex;
    }
    
    private aos.jack.util.thread.Semaphore __named_data_mutex2()
    {
        mutex2 = (aos.jack.util.thread.Semaphore) getNamedObject("mutex2","aos.jack.util.thread.Semaphore");
        return mutex2;
    }
    
    private NeonAffect.NA_Debug __named_data_debug()
    {
        debug = (NeonAffect.NA_Debug) getNamedObject("debug","NeonAffect.NA_Debug");
        return debug;
    }
    
}
