/*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*
  This code is generated by JAC version 5.6 by
  Agent Oriented Software. http://www.agent-software.com.au

    DO NOT ALTER THIS CODE AND DO NOT REMOVE THIS COMMENT
 *=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*/
package NeonAffect;
import aos.jack.jak.agent.Capability;
import aos.jack.jak.agent.NameSpace;
import aos.jack.jak.agent.Agent;
import aos.jack.util.thread.Semaphore;

/**
 * 
 */

public class HumbledAffectCapability extends aos.jack.jak.agent.Capability {
    public NeonAffect.PlanContextName planContextName;
    public NeonAffect.Behavior behaviorName;
    public aos.jack.util.thread.Semaphore mutex;
    public aos.jack.util.thread.Semaphore mutex2;
    public NeonAffect.NA_Debug debug;
    public NeonAffect.ContextEvent ce;
    public java.lang.String getDocumentation()
    {
        return "/**\n * \n */\n";
    }
    
    public void __init1()
    {
        setNamedCreator("planContextName","NeonAffect.PlanContextName",new aos.jack.jak.agent.DataCreator(false){
            public java.lang.Object create()
            {
                return __named_data_planContextName();
            }
            
        },true);
        setNamedCreator("behaviorName","NeonAffect.Behavior",new aos.jack.jak.agent.DataCreator(false){
            public java.lang.Object create()
            {
                return __named_data_behaviorName();
            }
            
        },true);
        setNamedCreator("mutex","aos.jack.util.thread.Semaphore",new aos.jack.jak.agent.DataCreator(false){
            public java.lang.Object create()
            {
                return __named_data_mutex();
            }
            
        },true);
        setNamedCreator("mutex2","aos.jack.util.thread.Semaphore",new aos.jack.jak.agent.DataCreator(false){
            public java.lang.Object create()
            {
                return __named_data_mutex2();
            }
            
        },true);
        setNamedCreator("debug","NeonAffect.NA_Debug",new aos.jack.jak.agent.DataCreator(false){
            public java.lang.Object create()
            {
                return __named_data_debug();
            }
            
        },true);
    }
    
    public void __init2()
    {
        ce = (NeonAffect.ContextEvent) findEvent("NeonAffect.ContextEvent");
        planContextName = (NeonAffect.PlanContextName) getNamedObject("planContextName","NeonAffect.PlanContextName");
        behaviorName = (NeonAffect.Behavior) getNamedObject("behaviorName","NeonAffect.Behavior");
        mutex = (aos.jack.util.thread.Semaphore) getNamedObject("mutex","aos.jack.util.thread.Semaphore");
        mutex2 = (aos.jack.util.thread.Semaphore) getNamedObject("mutex2","aos.jack.util.thread.Semaphore");
        debug = (NeonAffect.NA_Debug) getNamedObject("debug","NeonAffect.NA_Debug");
        autorun();
    }
    
    synchronized public void __init_desc()
    {
        externals.put("debug","debug");
        externals.put("mutex2","mutex2");
        externals.put("mutex","mutex");
        externals.put("behaviorName","behaviorName");
        externals.put("planContextName","planContextName");
        externals.put("NeonAffect.SetPlanContextEvent","NeonAffect.SetPlanContextEvent");
        externals.put("NeonAffect.Level1PosAffectEvent","NeonAffect.Level1PosAffectEvent");
        addEvent("NeonAffect.Level1PosAffectEvent",aos.jack.jak.agent.Agent.HANDLED_EVENT);
        addEvent("NeonAffect.SetPlanContextEvent",aos.jack.jak.agent.Agent.HANDLED_EVENT);
        addEvent("NeonAffect.ContextEvent",aos.jack.jak.agent.Agent.SENT_EVENT);
        addPlan("NeonAffect.DuckHeadPlan",0);
        addPlan("NeonAffect.LowerChinPlan",0);
        addPlan("NeonAffect.CoverFaceHandsHumbledPlan",0);
        addPlan("NeonAffect.HandsOnHipsPlan",0);
        addPlan("NeonAffect.SlowNodPlan",0);
        addPlan("NeonAffect.QuietVoiceHumbledPlan",0);
        addPlan("NeonAffect.ChokedUpPlan",0);
        addPlan("NeonAffect.HoldingBackTearsPlan",0);
        addPlan("NeonAffect.NotDefendingOneselfPlan",0);
        addPlan("NeonAffect.StayBackgrouindPlan",0);
        addPlan("NeonAffect.ExhaleThroughNoseHumbledPlan",0);
        addPlan("NeonAffect.GoingStillPlan",0);
        addPlan("NeonAffect.ArmsCrossedHumbledPlan",0);
        addPlan("NeonAffect.WinceHumbledPlan",0);
        addPlan("NeonAffect.MindRacingPlan",0);
        addPlan("NeonAffect.RiskAversionPlan",0);
        addPlan("NeonAffect.OverlyCriticalSelfPlan",0);
        addPlan("NeonAffect.TryHarderPlan",0);
        addPlan("NeonAffect.RenewedDeterminismPlan",0);
        addPlan("NeonAffect.DenialPlan",0);
        addPlan("NeonAffect.HatredHumbledPlan",0);
        addPlan("NeonAffect.MakingExcusesPlan",0);
        addPlan("NeonAffect.LaughingHumbledPlan",0);
        addPlan("NeonAffect.ArroganceHumbledPlan",0);
        addPlan("NeonAffect.SetPlanContextHumbledPlan",0);
    }
    
    public HumbledAffectCapability(aos.jack.jak.agent.NameSpace outer)
    {
        super(outer);
    }
    
    synchronized public void __bindNames()
    {
        super.__bindNames();
        __bindToPlan("NeonAffect.DuckHeadPlan");
        __bindToPlan("NeonAffect.LowerChinPlan");
        __bindToPlan("NeonAffect.CoverFaceHandsHumbledPlan");
        __bindToPlan("NeonAffect.HandsOnHipsPlan");
        __bindToPlan("NeonAffect.SlowNodPlan");
        __bindToPlan("NeonAffect.QuietVoiceHumbledPlan");
        __bindToPlan("NeonAffect.ChokedUpPlan");
        __bindToPlan("NeonAffect.HoldingBackTearsPlan");
        __bindToPlan("NeonAffect.NotDefendingOneselfPlan");
        __bindToPlan("NeonAffect.StayBackgrouindPlan");
        __bindToPlan("NeonAffect.ExhaleThroughNoseHumbledPlan");
        __bindToPlan("NeonAffect.GoingStillPlan");
        __bindToPlan("NeonAffect.ArmsCrossedHumbledPlan");
        __bindToPlan("NeonAffect.WinceHumbledPlan");
        __bindToPlan("NeonAffect.MindRacingPlan");
        __bindToPlan("NeonAffect.RiskAversionPlan");
        __bindToPlan("NeonAffect.OverlyCriticalSelfPlan");
        __bindToPlan("NeonAffect.TryHarderPlan");
        __bindToPlan("NeonAffect.RenewedDeterminismPlan");
        __bindToPlan("NeonAffect.DenialPlan");
        __bindToPlan("NeonAffect.HatredHumbledPlan");
        __bindToPlan("NeonAffect.MakingExcusesPlan");
        __bindToPlan("NeonAffect.LaughingHumbledPlan");
        __bindToPlan("NeonAffect.ArroganceHumbledPlan");
        __bindToPlan("NeonAffect.SetPlanContextHumbledPlan");
    }
    
    private NeonAffect.PlanContextName __named_data_planContextName()
    {
        planContextName = (NeonAffect.PlanContextName) getNamedObject("planContextName","NeonAffect.PlanContextName");
        return planContextName;
    }
    
    private NeonAffect.Behavior __named_data_behaviorName()
    {
        behaviorName = (NeonAffect.Behavior) getNamedObject("behaviorName","NeonAffect.Behavior");
        return behaviorName;
    }
    
    private aos.jack.util.thread.Semaphore __named_data_mutex()
    {
        mutex = (aos.jack.util.thread.Semaphore) getNamedObject("mutex","aos.jack.util.thread.Semaphore");
        return mutex;
    }
    
    private aos.jack.util.thread.Semaphore __named_data_mutex2()
    {
        mutex2 = (aos.jack.util.thread.Semaphore) getNamedObject("mutex2","aos.jack.util.thread.Semaphore");
        return mutex2;
    }
    
    private NeonAffect.NA_Debug __named_data_debug()
    {
        debug = (NeonAffect.NA_Debug) getNamedObject("debug","NeonAffect.NA_Debug");
        return debug;
    }
    
}
